export const activitiesCatalog = [
  ["activities-easy-walking", "walking", "footsteps", "easy"],
  ["activities-easy-running", "running", "breathless", "easy"],
  ["activities-easy-jogging", "jogging", "earbuds", "easy"],
  ["activities-easy-sprinting", "sprinting", "adrenaline", "easy"],
  ["activities-easy-jumping", "jumping", "bounce", "easy"],
  ["activities-easy-climbing", "climbing", "heights", "easy"],
  ["activities-easy-crawling", "crawling", "baby", "easy"],
  ["activities-easy-sitting", "sitting", "posture", "easy"],
  ["activities-easy-standing", "standing", "stiffness", "easy"],
  ["activities-easy-kneeling", "kneeling", "proposal", "easy"],
  ["activities-easy-stretching", "stretching", "flexibility", "easy"],
  ["activities-easy-bending", "bending", "creak", "easy"],
  ["activities-easy-lifting", "lifting", "strain", "easy"],
  ["activities-easy-carrying", "carrying", "burden", "easy"],
  ["activities-easy-pushing", "pushing", "resistance", "easy"],
  ["activities-easy-pulling", "pulling", "tug", "easy"],
  ["activities-easy-throwing", "throwing", "aim", "easy"],
  ["activities-easy-catching", "catching", "reflex", "easy"],
  ["activities-easy-kicking", "kicking", "shin", "easy"],
  ["activities-easy-punching", "punching", "knuckles", "easy"],
  ["activities-easy-waving", "waving", "goodbye", "easy"],
  ["activities-easy-pointing", "pointing", "blame", "easy"],
  ["activities-easy-hugging", "hugging", "warmth", "easy"],
  ["activities-easy-kissing", "kissing", "butterflies", "easy"],
  ["activities-easy-laughing", "laughing", "contagious", "easy"],
  ["activities-easy-crying", "crying", "tissues", "easy"],
  ["activities-easy-smiling", "smiling", "dimples", "easy"],
  ["activities-easy-frowning", "frowning", "disappointment", "easy"],
  ["activities-easy-yawning", "yawning", "boredom", "easy"],
  ["activities-easy-sneezing", "sneezing", "germs", "easy"],
  ["activities-easy-coughing", "coughing", "phlegm", "easy"],
  ["activities-easy-breathing", "breathing", "lungs", "easy"],
  ["activities-easy-blinking", "blinking", "eyelashes", "easy"],
  ["activities-easy-thinking", "thinking", "headache", "easy"],
  ["activities-easy-daydreaming", "daydreaming", "clouds", "easy"],
  ["activities-easy-waiting", "waiting", "impatience", "easy"],
  ["activities-easy-listening", "listening", "silence", "easy"],
  ["activities-easy-watching", "watching", "attention", "easy"],
  ["activities-easy-looking", "looking", "focus", "easy"],
  ["activities-easy-observing", "observing", "patterns", "easy"],
  ["activities-easy-remembering", "remembering", "flashback", "easy"],
  ["activities-easy-forgetting", "forgetting", "panic", "easy"],
  ["activities-easy-imagining", "imagining", "fantasy", "easy"],
  ["activities-easy-choosing", "choosing", "options", "easy"],
  ["activities-easy-deciding", "deciding", "stakes", "easy"],
  ["activities-easy-guessing", "guessing", "uncertainty", "easy"],
  ["activities-easy-noticing", "noticing", "clues", "easy"],
  ["activities-easy-searching", "searching", "desperation", "easy"],
  ["activities-easy-finding", "finding", "success", "easy"],
  ["activities-easy-hiding", "hiding", "secrecy", "easy"],
  ["activities-easy-escaping", "escaping", "freedom", "easy"],
  ["activities-easy-chasing", "chasing", "pursuit", "easy"],
  ["activities-easy-following", "following", "footsteps", "easy"],
  ["activities-easy-leading", "leading", "responsibility", "easy"],
  ["activities-easy-helping", "helping", "kindness", "easy"],
  ["activities-easy-sharing", "sharing", "generosity", "easy"],
  ["activities-easy-borrowing", "borrowing", "trust", "easy"],
  ["activities-easy-lending", "lending", "favor", "easy"],
  ["activities-easy-trading", "trading", "bargain", "easy"],
  ["activities-easy-selling", "selling", "persuasion", "easy"],
  ["activities-easy-buying", "buying", "impulse", "easy"],
  ["activities-easy-paying", "paying", "obligation", "easy"],
  ["activities-easy-saving", "saving", "restraint", "easy"],
  ["activities-easy-spending", "spending", "regret", "easy"],
  ["activities-easy-planning", "planning", "anticipation", "easy"],
  ["activities-easy-organizing", "organizing", "control", "easy"],
  ["activities-easy-preparing", "preparing", "readiness", "easy"],
  ["activities-easy-packing", "packing", "departure", "easy"],
  ["activities-easy-unpacking", "unpacking", "settling", "easy"],
  ["activities-easy-sorting", "sorting", "piles", "easy"],
  ["activities-easy-counting", "counting", "accuracy", "easy"],
  ["activities-easy-measuring", "measuring", "precision", "easy"],
  ["activities-easy-checking", "checking", "paranoia", "easy"],
  ["activities-easy-testing", "testing", "proof", "easy"],
  ["activities-easy-practicing", "practicing", "repetition", "easy"],
  ["activities-easy-training", "training", "endurance", "easy"],
  ["activities-easy-learning", "learning", "discovery", "easy"],
  ["activities-easy-teaching", "teaching", "explanation", "easy"],
  ["activities-easy-studying", "studying", "cramming", "easy"],
  ["activities-easy-reading", "reading", "immersion", "easy"],
  ["activities-easy-writing", "writing", "expression", "easy"],
  ["activities-easy-typing", "typing", "clatter", "easy"],
  ["activities-easy-texting", "texting", "thumbs", "easy"],
  ["activities-easy-calling", "calling", "ringtone", "easy"],
  ["activities-easy-speaking", "speaking", "confidence", "easy"],
  ["activities-easy-whispering", "whispering", "secrecy", "easy"],
  ["activities-easy-shouting", "shouting", "volume", "easy"],
  ["activities-easy-arguing", "arguing", "tension", "easy"],
  ["activities-easy-apologizing", "apologizing", "humility", "easy"],
  ["activities-easy-forgiving", "forgiving", "peace", "easy"],
  ["activities-easy-complaining", "complaining", "frustration", "easy"],
  ["activities-easy-explaining", "explaining", "clarity", "easy"],
  ["activities-easy-asking", "asking", "interest", "easy"],
  ["activities-easy-answering", "answering", "confidence", "easy"],
  ["activities-easy-debating", "debating", "disagreement", "easy"],
  ["activities-easy-presenting", "presenting", "nerves", "easy"],
  ["activities-easy-interviewing", "interviewing", "sweat", "easy"],
  ["activities-easy-emailing", "emailing", "inbox", "easy"],
  ["activities-easy-messaging", "messaging", "notifications", "easy"],
  ["activities-easy-scrolling", "scrolling", "dopamine", "easy"],
  ["activities-easy-browsing", "browsing", "wandering", "easy"],
  ["activities-easy-posting", "posting", "attention", "easy"],
  ["activities-easy-commenting", "commenting", "opinions", "easy"],
  ["activities-easy-uploading", "uploading", "progress", "easy"],
  ["activities-easy-downloading", "downloading", "queue", "easy"],
  ["activities-easy-streaming", "streaming", "buffering", "easy"],
  ["activities-easy-coding", "coding", "logic", "easy"],
  ["activities-easy-programming", "programming", "bugs", "easy"],
  ["activities-easy-designing", "designing", "taste", "easy"],
  ["activities-easy-building", "building", "progress", "easy"],
  ["activities-easy-repairing", "repairing", "breakdown", "easy"],
  ["activities-easy-fixing", "fixing", "solution", "easy"],
  ["activities-easy-assembling", "assembling", "instructions", "easy"],
  ["activities-easy-installing", "installing", "setup", "easy"],
  ["activities-easy-charging", "charging", "percentage", "easy"],
  ["activities-easy-printing", "printing", "jams", "easy"],
  ["activities-easy-scanning", "scanning", "beep", "easy"],
  ["activities-easy-recording", "recording", "evidence", "easy"],
  ["activities-easy-filming", "filming", "angles", "easy"],
  ["activities-easy-photographing", "photographing", "lighting", "easy"],
  ["activities-easy-drawing", "drawing", "imagination", "easy"],
  ["activities-easy-sketching", "sketching", "outline", "easy"],
  ["activities-easy-painting", "painting", "color", "easy"],
  ["activities-easy-coloring", "coloring", "crayons", "easy"],
  ["activities-easy-sculpting", "sculpting", "clay", "easy"],
  ["activities-easy-carving", "carving", "shavings", "easy"],
  ["activities-easy-origami", "origami", "folds", "easy"],
  ["activities-easy-knitting", "knitting", "yarn", "easy"],
  ["activities-easy-sewing", "sewing", "stitches", "easy"],
  ["activities-easy-woodworking", "woodworking", "sawdust", "easy"],
  ["activities-easy-makeup", "makeup", "transformation", "easy"],
  ["activities-easy-cosplay", "cosplay", "costume", "easy"],
  ["activities-easy-animation", "animation", "frames", "easy"],
  ["activities-easy-singing", "singing", "melody", "easy"],
  ["activities-easy-humming", "humming", "absentminded", "easy"],
  ["activities-easy-whistling", "whistling", "tune", "easy"],
  ["activities-easy-rapping", "rapping", "flow", "easy"],
  ["activities-easy-dancing", "dancing", "movement", "easy"],
  ["activities-easy-karaoke", "karaoke", "embarrassment", "easy"],
  ["activities-easy-acting", "acting", "pretending", "easy"],
  ["activities-easy-storytelling", "storytelling", "suspense", "easy"],
  ["activities-easy-poetry", "poetry", "emotion", "easy"],
  ["activities-easy-comedy", "comedy", "timing", "easy"],
  ["activities-easy-theater", "theater", "drama", "easy"],
  ["activities-easy-ballet", "ballet", "grace", "easy"],
  ["activities-easy-breakdancing", "breakdancing", "spin", "easy"],
  ["activities-easy-salsa-dancing", "salsa dancing", "hips", "easy"],
  ["activities-easy-tap-dancing", "tap dancing", "clicks", "easy"],
  ["activities-easy-journaling", "journaling", "reflection", "easy"],
  ["activities-easy-public-speaking", "public speaking", "nerves", "easy"],
  ["activities-easy-cleaning", "cleaning", "shine", "easy"],
  ["activities-easy-sweeping", "sweeping", "dust", "easy"],
  ["activities-easy-mopping", "mopping", "puddles", "easy"],
  ["activities-easy-vacuuming", "vacuuming", "noise", "easy"],
  ["activities-easy-dusting", "dusting", "sneezes", "easy"],
  ["activities-easy-washing", "washing", "suds", "easy"],
  ["activities-easy-drying", "drying", "drips", "easy"],
  ["activities-easy-folding", "folding", "creases", "easy"],
  ["activities-easy-ironing", "ironing", "steam", "easy"],
  ["activities-easy-laundry", "laundry", "wrinkles", "easy"],
  ["activities-easy-grocery-shopping", "grocery shopping", "coupons", "easy"],
  ["activities-easy-cooking", "cooking", "aroma", "easy"],
  ["activities-easy-baking", "baking", "rising", "easy"],
  ["activities-easy-grilling", "grilling", "smoke", "easy"],
  ["activities-easy-frying", "frying", "sizzle", "easy"],
  ["activities-easy-boiling", "boiling", "steam", "easy"],
  ["activities-easy-chopping", "chopping", "tempo", "easy"],
  ["activities-easy-mixing", "mixing", "swirl", "easy"],
  ["activities-easy-pouring", "pouring", "spill", "easy"],
  ["activities-easy-serving", "serving", "hospitality", "easy"],
  ["activities-easy-tasting", "tasting", "flavor", "easy"],
  ["activities-easy-eating", "eating", "satisfaction", "easy"],
  ["activities-easy-drinking", "drinking", "thirst", "easy"],
  ["activities-easy-snacking", "snacking", "cravings", "easy"],
  ["activities-easy-fasting", "fasting", "hunger", "easy"],
  ["activities-easy-decorating", "decorating", "flair", "easy"],
  ["activities-easy-lawn-mowing", "lawn mowing", "stripes", "easy"],
  ["activities-easy-recycling", "recycling", "guilt", "easy"],
  ["activities-easy-planting", "planting", "growth", "easy"],
  ["activities-easy-dog-walking", "dog walking", "sniffing", "easy"],
  ["activities-easy-babysitting", "babysitting", "chaos", "easy"],
  ["activities-easy-parenting", "parenting", "exhaustion", "easy"],
  ["activities-easy-bedtime-stories", "bedtime stories", "sleepy", "easy"],
  ["activities-easy-gift-wrapping", "gift wrapping", "ribbons", "easy"],
  ["activities-easy-sleeping", "sleeping", "dreams", "easy"],
  ["activities-easy-napping", "napping", "drool", "easy"],
  ["activities-easy-dreaming", "dreaming", "subconscious", "easy"],
  ["activities-easy-resting", "resting", "recovery", "easy"],
  ["activities-easy-relaxing", "relaxing", "calm", "easy"],
  ["activities-easy-meditating", "meditating", "stillness", "easy"],
  ["activities-easy-praying", "praying", "hope", "easy"],
  ["activities-easy-exercising", "exercising", "sweat", "easy"],
  ["activities-easy-dieting", "dieting", "cravings", "easy"],
  ["activities-easy-showering", "showering", "steam", "easy"],
  ["activities-easy-bathing", "bathing", "soaking", "easy"],
  ["activities-easy-flossing", "flossing", "bleeding", "easy"],
  ["activities-easy-shaving", "shaving", "stubble", "easy"],
  ["activities-easy-dressing", "dressing", "outfit", "easy"],
  ["activities-easy-grooming", "grooming", "neatness", "easy"],
  ["activities-easy-skincare", "skincare", "glow", "easy"],
  ["activities-easy-hair-styling", "hair styling", "volume", "easy"],
  ["activities-easy-nail-painting", "nail painting", "smudges", "easy"],
  ["activities-easy-massage", "massage", "looseness", "easy"],
  ["activities-easy-therapy", "therapy", "honesty", "easy"],
  ["activities-easy-spa-day", "spa day", "robes", "easy"],
  ["activities-easy-yoga", "yoga", "flexibility", "easy"],
  ["activities-easy-weightlifting", "weightlifting", "strain", "easy"],
  ["activities-easy-bodybuilding", "bodybuilding", "gains", "easy"],
  ["activities-easy-pushups", "pushups", "burn", "easy"],
  ["activities-easy-situps", "situps", "abs", "easy"],
  ["activities-easy-squats", "squats", "soreness", "easy"],
  ["activities-easy-jump-rope", "jump rope", "counting", "easy"],
  ["activities-easy-treadmill", "treadmill", "monotony", "easy"],
  ["activities-easy-martial-arts", "martial arts", "respect", "easy"],
  ["activities-easy-karate", "karate", "chops", "easy"],
  ["activities-easy-boxing", "boxing", "bruises", "easy"],
  ["activities-easy-wrestling", "wrestling", "tangles", "easy"],
  ["activities-easy-self-defense", "self defense", "alertness", "easy"],
  ["activities-easy-sauna", "sauna", "sweat", "easy"],
  ["activities-easy-gardening", "gardening", "dirt", "easy"],
  ["activities-easy-hiking", "hiking", "blisters", "easy"],
  ["activities-easy-camping", "camping", "mosquitoes", "easy"],
  ["activities-easy-backpacking", "backpacking", "burden", "easy"],
  ["activities-easy-picnicking", "picnicking", "ants", "easy"],
  ["activities-easy-barbecuing", "barbecuing", "smoke", "easy"],
  ["activities-easy-bonfire", "bonfire", "sparks", "easy"],
  ["activities-easy-fishing", "fishing", "bait", "easy"],
  ["activities-easy-bird-watching", "bird watching", "binoculars", "easy"],
  ["activities-easy-stargazing", "stargazing", "wonder", "easy"],
  ["activities-easy-sunbathing", "sunbathing", "tan", "easy"],
  ["activities-easy-swimming", "swimming", "splash", "easy"],
  ["activities-easy-snorkeling", "snorkeling", "reefs", "easy"],
  ["activities-easy-surfing", "surfing", "wipeout", "easy"],
  ["activities-easy-kayaking", "kayaking", "paddles", "easy"],
  ["activities-easy-boating", "boating", "waves", "easy"],
  ["activities-easy-sailing", "sailing", "wind", "easy"],
  ["activities-easy-skiing", "skiing", "edges", "easy"],
  ["activities-easy-snowboarding", "snowboarding", "powder", "easy"],
  ["activities-easy-sledding", "sledding", "laughter", "easy"],
  ["activities-easy-ice-skating", "ice skating", "glide", "easy"],
  ["activities-easy-roller-skating", "roller skating", "wobble", "easy"],
  ["activities-easy-skateboarding", "skateboarding", "pavement", "easy"],
  ["activities-easy-rock-climbing", "rock climbing", "grip", "easy"],
  ["activities-easy-mountain-biking", "mountain biking", "mud", "easy"],
  ["activities-easy-horseback-riding", "horseback riding", "saddle", "easy"],
  ["activities-easy-skydiving", "skydiving", "terror", "easy"],
  ["activities-easy-road-tripping", "road tripping", "snacks", "easy"],
  ["activities-easy-sightseeing", "sightseeing", "tourists", "easy"],
  ["activities-easy-traveling", "traveling", "passport", "easy"],
  ["activities-easy-commuting", "commuting", "traffic", "easy"],
  ["activities-easy-driving", "driving", "concentration", "easy"],
  ["activities-easy-parking", "parking", "frustration", "easy"],
  ["activities-easy-flying", "flying", "turbulence", "easy"],
  ["activities-easy-cruising", "cruising", "buffet", "easy"],
  ["activities-easy-navigating", "navigating", "confusion", "easy"],
  ["activities-easy-language-learning", "language learning", "accents", "easy"],
  ["activities-easy-volunteering", "volunteering", "service", "easy"],
  ["activities-easy-fundraising", "fundraising", "generosity", "easy"],
  ["activities-easy-donating", "donating", "kindness", "easy"],
  ["activities-easy-protesting", "protesting", "signs", "easy"],
  ["activities-easy-marching", "marching", "cadence", "easy"],
  ["activities-easy-celebrating", "celebrating", "confetti", "easy"],
  ["activities-easy-cheering", "cheering", "applause", "easy"],
  ["activities-easy-clapping", "clapping", "applause", "easy"],
  ["activities-easy-partying", "partying", "hangover", "easy"],
  ["activities-easy-clubbing", "clubbing", "bass", "easy"],
  ["activities-easy-dating", "dating", "butterflies", "easy"],
  ["activities-easy-flirting", "flirting", "chemistry", "easy"],
  ["activities-easy-gossiping", "gossiping", "secrets", "easy"],
  ["activities-easy-chatting", "chatting", "banter", "easy"],
  ["activities-easy-visiting", "visiting", "reunion", "easy"],
  ["activities-easy-hosting", "hosting", "stress", "easy"],
  ["activities-easy-dining-out", "dining out", "bill", "easy"],
  ["activities-easy-movie-night", "movie night", "popcorn", "easy"],
  ["activities-easy-game-night", "game night", "rivalry", "easy"],
  ["activities-easy-sleepover", "sleepover", "whispers", "easy"],
  ["activities-easy-family-reunion", "family reunion", "awkwardness", "easy"],
  ["activities-easy-birthday-party", "birthday party", "candles", "easy"],
  ["activities-easy-wedding-planning", "wedding planning", "stress", "easy"],
  ["activities-easy-baby-shower", "baby shower", "diapers", "easy"],
  ["activities-easy-graduation-party", "graduation party", "caps", "easy"],
  ["activities-easy-people-watching", "people watching", "judgment", "easy"],
  ["activities-easy-window-shopping", "window shopping", "temptation", "easy"],
  ["activities-easy-collecting", "collecting", "obsession", "easy"],
  ["activities-easy-book-collecting", "book collecting", "dust", "easy"],
  ["activities-easy-lego-building", "lego building", "clicks", "easy"],
  ["activities-easy-puzzle-solving", "puzzle solving", "deduction", "easy"],
  ["activities-easy-jigsaw-puzzles", "jigsaw puzzles", "missing", "easy"],
  ["activities-easy-crossword-puzzles", "crossword puzzles", "clues", "easy"],
  ["activities-easy-board-games", "board games", "arguments", "easy"],
  ["activities-easy-card-games", "card games", "bluffing", "easy"],
  ["activities-easy-video-gaming", "video gaming", "rage", "easy"],
  ["activities-easy-mobile-gaming", "mobile gaming", "boredom", "easy"],
  ["activities-easy-arcade-games", "arcade games", "tokens", "easy"],
  ["activities-easy-magic-tricks", "magic tricks", "misdirection", "easy"],
  ["activities-easy-treasure-hunt", "treasure hunt", "clues", "easy"],
  ["activities-easy-bowling", "bowling", "gutters", "easy"],
  ["activities-easy-darts", "darts", "aim", "easy"],
  ["activities-easy-ping-pong", "ping pong", "reflexes", "easy"],
  ["activities-easy-mini-golf", "mini golf", "frustration", "easy"],
  ["activities-easy-frisbee", "frisbee", "wind", "easy"],
  ["activities-easy-kite-flying", "kite flying", "wind", "easy"],
  ["activities-easy-jumping-jacks", "jumping jacks", "counting", "easy"],
  ["activities-easy-movie-watching", "movie watching", "suspense", "easy"],
  ["activities-easy-binge-watching", "binge watching", "hours", "easy"],
  ["activities-easy-audiobooks", "audiobooks", "narration", "easy"],
  [
    "activities-easy-podcast-listening",
    "podcast listening",
    "multitasking",
    "easy",
  ],
  ["activities-easy-radio-listening", "radio listening", "static", "easy"],
  ["activities-easy-news-reading", "news reading", "anxiety", "easy"],
  ["activities-easy-magazine-reading", "magazine reading", "glossy", "easy"],
  ["activities-easy-comic-reading", "comic reading", "panels", "easy"],
  ["activities-easy-meme-making", "meme making", "irony", "easy"],
  ["activities-easy-online-shopping", "online shopping", "impulse", "easy"],
  ["activities-easy-video-calling", "video calling", "lag", "easy"],
  ["activities-easy-note-taking", "note taking", "scribbles", "easy"],
  ["activities-easy-exam-taking", "exam taking", "panic", "easy"],
  ["activities-easy-test-taking", "test taking", "silence", "easy"],
  ["activities-easy-homework", "homework", "procrastination", "easy"],
  ["activities-easy-group-project", "group project", "resentment", "easy"],
  ["activities-easy-essay-writing", "essay writing", "deadlines", "easy"],
  ["activities-easy-problem-solving", "problem solving", "logic", "easy"],
  ["activities-easy-decision-making", "decision making", "tradeoffs", "easy"],
  ["activities-easy-meeting", "meeting", "boredom", "easy"],
  ["activities-easy-job-hunting", "job hunting", "rejection", "easy"],
  ["activities-easy-remote-work", "remote work", "pajamas", "easy"],
  [
    "activities-easy-package-tracking",
    "package tracking",
    "impatience",
    "easy",
  ],
  ["activities-easy-dog-training", "dog training", "treats", "easy"],
  ["activities-easy-dance-class", "dance class", "choreography", "easy"],
  ["activities-easy-cooking-class", "cooking class", "recipes", "easy"],
  ["activities-easy-art-class", "art class", "creativity", "easy"],
  ["activities-easy-music-lesson", "music lesson", "scales", "easy"],
  ["activities-easy-driving-lesson", "driving lesson", "cones", "easy"],
  ["activities-easy-first-aid", "first aid", "bandages", "easy"],
  ["activities-easy-voting", "voting", "stickers", "easy"],
  ["activities-easy-playing-pretend", "playing pretend", "imagination", "easy"],
  ["activities-easy-pillow-fight", "pillow fight", "feathers", "easy"],
  ["activities-easy-swinging", "swinging", "dizziness", "easy"],
  ["activities-easy-sliding", "sliding", "friction", "easy"],
  ["activities-easy-snowball-fight", "snowball fight", "ambush", "easy"],
  ["activities-easy-tree-climbing", "tree climbing", "branches", "easy"],
  ["activities-easy-dress-up", "dress up", "costumes", "easy"],
  ["activities-easy-puppet-show", "puppet show", "voices", "easy"],
  ["activities-easy-face-painting", "face painting", "glitter", "easy"],
  ["activities-easy-archery", "archery", "focus", "easy"],
  ["activities-easy-tattooing", "tattooing", "ink", "easy"],
  ["activities-easy-piercing", "piercing", "needles", "easy"],
  ["activities-easy-hairstyling", "hairstyling", "scissors", "easy"],
  ["activities-easy-carpentry", "carpentry", "sawdust", "easy"],
  ["activities-easy-plumbing", "plumbing", "leaks", "easy"],
  ["activities-easy-car-repair", "car repair", "grease", "easy"],
  ["activities-easy-bike-repair", "bike repair", "chains", "easy"],
  ["activities-easy-computer-repair", "computer repair", "reboots", "easy"],
  ["activities-easy-phone-repair", "phone repair", "cracks", "easy"],
  ["activities-easy-dance-practice", "dance practice", "repetition", "easy"],
  ["activities-easy-music-practice", "music practice", "repetition", "easy"],
  ["activities-easy-sports-practice", "sports practice", "drills", "easy"],
  ["activities-easy-joke-telling", "joke telling", "punchline", "easy"],
  ["activities-easy-surprising", "surprising", "secrecy", "easy"],
  ["activities-easy-proposing", "proposing", "knees", "easy"],
  ["activities-easy-party-planning", "party planning", "logistics", "easy"],
  ["activities-easy-music-listening", "music listening", "mood", "easy"],
  ["activities-easy-playing-tag", "playing tag", "chase", "easy"],
  ["activities-easy-biking", "biking", "breeze", "easy"],
  ["activities-easy-cycling", "cycling", "endurance", "easy"],
  ["activities-easy-running-errands", "running errands", "checklist", "easy"],
  ["activities-easy-errands", "errands", "checklist", "easy"],
  ["activities-easy-photography", "photography", "lighting", "easy"],
  ["activities-easy-crafting", "crafting", "glue", "easy"],
  ["activities-easy-gaming", "gaming", "adrenaline", "easy"],
  ["activities-easy-travel-planning", "travel planning", "itinerary", "easy"],
  ["activities-easy-chores", "chores", "resentment", "easy"],
  ["activities-medium-seeking", "seeking", "longing", "medium"],
  ["activities-medium-budgeting", "budgeting", "limits", "medium"],
  ["activities-medium-scheduling", "scheduling", "juggling", "medium"],
  ["activities-medium-memorizing", "memorizing", "repetition", "medium"],
  ["activities-medium-researching", "researching", "sources", "medium"],
  ["activities-medium-negotiating", "negotiating", "leverage", "medium"],
  ["activities-medium-networking", "networking", "smalltalk", "medium"],
  ["activities-medium-mentoring", "mentoring", "guidance", "medium"],
  ["activities-medium-coaching", "coaching", "encouragement", "medium"],
  ["activities-medium-brainstorming", "brainstorming", "ideas", "medium"],
  ["activities-medium-proofreading", "proofreading", "typos", "medium"],
  ["activities-medium-editing", "editing", "cuts", "medium"],
  ["activities-medium-filing", "filing", "alphabet", "medium"],
  ["activities-medium-photocopying", "photocopying", "duplicates", "medium"],
  ["activities-medium-stapling", "stapling", "corners", "medium"],
  ["activities-medium-subscribing", "subscribing", "commitment", "medium"],
  ["activities-medium-unsubscribing", "unsubscribing", "silence", "medium"],
  ["activities-medium-bookmarking", "bookmarking", "return", "medium"],
  ["activities-medium-pottery", "pottery", "clay", "medium"],
  ["activities-medium-crocheting", "crocheting", "loops", "medium"],
  ["activities-medium-quilting", "quilting", "patches", "medium"],
  ["activities-medium-embroidery", "embroidery", "thread", "medium"],
  ["activities-medium-weaving", "weaving", "pattern", "medium"],
  ["activities-medium-jewelry-making", "jewelry making", "sparkle", "medium"],
  ["activities-medium-candle-making", "candle making", "wax", "medium"],
  ["activities-medium-soap-making", "soap making", "lather", "medium"],
  ["activities-medium-scrapbooking", "scrapbooking", "nostalgia", "medium"],
  [
    "activities-medium-fashion-design",
    "fashion design",
    "silhouette",
    "medium",
  ],
  ["activities-medium-graphic-design", "graphic design", "layout", "medium"],
  ["activities-medium-songwriting", "songwriting", "heartbreak", "medium"],
  ["activities-medium-composing", "composing", "harmony", "medium"],
  ["activities-medium-beatboxing", "beatboxing", "spit", "medium"],
  ["activities-medium-djing", "djing", "bass", "medium"],
  ["activities-medium-improv", "improv", "panic", "medium"],
  ["activities-medium-standup", "standup", "hecklers", "medium"],
  [
    "activities-medium-line-dancing",
    "line dancing",
    "synchronization",
    "medium",
  ],
  ["activities-medium-choir-singing", "choir singing", "harmony", "medium"],
  ["activities-medium-podcasting", "podcasting", "rambling", "medium"],
  ["activities-medium-blogging", "blogging", "opinions", "medium"],
  ["activities-medium-vlogging", "vlogging", "thumbnails", "medium"],
  ["activities-medium-dishwashing", "dishwashing", "suds", "medium"],
  ["activities-medium-meal-prep", "meal prep", "containers", "medium"],
  ["activities-medium-decluttering", "decluttering", "relief", "medium"],
  ["activities-medium-home-repair", "home repair", "surprises", "medium"],
  ["activities-medium-composting", "composting", "rot", "medium"],
  ["activities-medium-weeding", "weeding", "roots", "medium"],
  ["activities-medium-harvesting", "harvesting", "ripeness", "medium"],
  ["activities-medium-pruning", "pruning", "snips", "medium"],
  ["activities-medium-oil-change", "oil change", "grease", "medium"],
  ["activities-medium-bill-paying", "bill paying", "dread", "medium"],
  ["activities-medium-tax-filing", "tax filing", "receipts", "medium"],
  ["activities-medium-couponing", "couponing", "savings", "medium"],
  ["activities-medium-window-cleaning", "window cleaning", "streaks", "medium"],
  ["activities-medium-shoe-polishing", "shoe polishing", "shine", "medium"],
  [
    "activities-medium-breathing-exercises",
    "breathing exercises",
    "calm",
    "medium",
  ],
  [
    "activities-medium-gratitude-practice",
    "gratitude practice",
    "perspective",
    "medium",
  ],
  ["activities-medium-pilates", "pilates", "control", "medium"],
  ["activities-medium-planking", "planking", "shaking", "medium"],
  ["activities-medium-pullups", "pullups", "struggle", "medium"],
  ["activities-medium-spinning", "spinning", "dizziness", "medium"],
  ["activities-medium-aerobics", "aerobics", "energy", "medium"],
  ["activities-medium-zumba", "zumba", "hips", "medium"],
  ["activities-medium-crossfit", "crossfit", "intensity", "medium"],
  ["activities-medium-taekwondo", "taekwondo", "kicks", "medium"],
  ["activities-medium-judo", "judo", "throws", "medium"],
  ["activities-medium-cold-plunge", "cold plunge", "shock", "medium"],
  ["activities-medium-scuba-diving", "scuba diving", "oxygen", "medium"],
  ["activities-medium-paddleboarding", "paddleboarding", "wobble", "medium"],
  ["activities-medium-canoeing", "canoeing", "paddles", "medium"],
  ["activities-medium-rafting", "rafting", "rapids", "medium"],
  ["activities-medium-water-skiing", "water skiing", "wipeout", "medium"],
  ["activities-medium-jet-skiing", "jet skiing", "spray", "medium"],
  ["activities-medium-ziplining", "ziplining", "scream", "medium"],
  ["activities-medium-bungee-jumping", "bungee jumping", "fear", "medium"],
  ["activities-medium-map-reading", "map reading", "confusion", "medium"],
  [
    "activities-medium-souvenir-shopping",
    "souvenir shopping",
    "magnets",
    "medium",
  ],
  ["activities-medium-parading", "parading", "floats", "medium"],
  ["activities-medium-toasting", "toasting", "speeches", "medium"],
  ["activities-medium-brunching", "brunching", "late", "medium"],
  ["activities-medium-housewarming", "housewarming", "plants", "medium"],
  ["activities-medium-bargain-hunting", "bargain hunting", "savings", "medium"],
  ["activities-medium-thrifting", "thrifting", "treasures", "medium"],
  [
    "activities-medium-stamp-collecting",
    "stamp collecting",
    "envelopes",
    "medium",
  ],
  ["activities-medium-coin-collecting", "coin collecting", "change", "medium"],
  [
    "activities-medium-comic-collecting",
    "comic collecting",
    "issues",
    "medium",
  ],
  ["activities-medium-toy-collecting", "toy collecting", "childhood", "medium"],
  [
    "activities-medium-record-collecting",
    "record collecting",
    "vinyl",
    "medium",
  ],
  [
    "activities-medium-plant-collecting",
    "plant collecting",
    "propagation",
    "medium",
  ],
  ["activities-medium-rock-collecting", "rock collecting", "pockets", "medium"],
  ["activities-medium-card-collecting", "card collecting", "binders", "medium"],
  [
    "activities-medium-model-building",
    "model building",
    "miniatures",
    "medium",
  ],
  ["activities-medium-sudoku", "sudoku", "logic", "medium"],
  ["activities-medium-trivia-night", "trivia night", "confidence", "medium"],
  ["activities-medium-escape-room", "escape room", "locks", "medium"],
  ["activities-medium-roleplaying", "roleplaying", "imagination", "medium"],
  ["activities-medium-fortune-telling", "fortune telling", "mystery", "medium"],
  ["activities-medium-scavenger-hunt", "scavenger hunt", "clues", "medium"],
  ["activities-medium-laser-tag", "laser tag", "ambush", "medium"],
  ["activities-medium-paintball", "paintball", "bruises", "medium"],
  ["activities-medium-billiards", "billiards", "angles", "medium"],
  ["activities-medium-hula-hooping", "hula hooping", "hips", "medium"],
  ["activities-medium-concert-going", "concert going", "ringing", "medium"],
  [
    "activities-medium-festival-going",
    "festival going",
    "wristbands",
    "medium",
  ],
  ["activities-medium-museum-visiting", "museum visiting", "silence", "medium"],
  ["activities-medium-book-club", "book club", "opinions", "medium"],
  [
    "activities-medium-content-creation",
    "content creation",
    "algorithm",
    "medium",
  ],
  ["activities-medium-live-streaming", "live streaming", "audience", "medium"],
  ["activities-medium-video-editing", "video editing", "cuts", "medium"],
  ["activities-medium-photo-editing", "photo editing", "filters", "medium"],
  ["activities-medium-digital-art", "digital art", "stylus", "medium"],
  ["activities-medium-web-design", "web design", "layout", "medium"],
  ["activities-medium-game-design", "game design", "mechanics", "medium"],
  ["activities-medium-drone-flying", "drone flying", "buzzing", "medium"],
  ["activities-medium-3d-printing", "3d printing", "layers", "medium"],
  [
    "activities-medium-virtual-reality",
    "virtual reality",
    "dizziness",
    "medium",
  ],
  ["activities-medium-online-dating", "online dating", "swiping", "medium"],
  ["activities-medium-coffee-brewing", "coffee brewing", "caffeine", "medium"],
  ["activities-medium-wine-tasting", "wine tasting", "tannins", "medium"],
  [
    "activities-medium-cake-decorating",
    "cake decorating",
    "frosting",
    "medium",
  ],
  ["activities-medium-cookie-baking", "cookie baking", "warmth", "medium"],
  ["activities-medium-bread-baking", "bread baking", "rising", "medium"],
  ["activities-medium-tutoring", "tutoring", "breakthrough", "medium"],
  ["activities-medium-spelling-bee", "spelling bee", "spotlight", "medium"],
  ["activities-medium-book-report", "book report", "summary", "medium"],
  [
    "activities-medium-project-planning",
    "project planning",
    "milestones",
    "medium",
  ],
  [
    "activities-medium-time-management",
    "time management",
    "deadlines",
    "medium",
  ],
  ["activities-medium-goal-setting", "goal setting", "ambition", "medium"],
  ["activities-medium-team-building", "team building", "trustfalls", "medium"],
  [
    "activities-medium-resume-writing",
    "resume writing",
    "exaggeration",
    "medium",
  ],
  [
    "activities-medium-performance-review",
    "performance review",
    "anxiety",
    "medium",
  ],
  [
    "activities-medium-customer-service",
    "customer service",
    "composure",
    "medium",
  ],
  ["activities-medium-whiteboarding", "whiteboarding", "markers", "medium"],
  ["activities-medium-data-entry", "data entry", "monotony", "medium"],
  [
    "activities-medium-delivery-driving",
    "delivery driving",
    "routes",
    "medium",
  ],
  ["activities-medium-cashiering", "cashiering", "change", "medium"],
  ["activities-medium-waitressing", "waitressing", "tips", "medium"],
  ["activities-medium-bartending", "bartending", "pours", "medium"],
  ["activities-medium-catering", "catering", "trays", "medium"],
  ["activities-medium-lifeguarding", "lifeguarding", "whistle", "medium"],
  ["activities-medium-horse-training", "horse training", "reins", "medium"],
  ["activities-medium-choir-practice", "choir practice", "harmony", "medium"],
  ["activities-medium-bible-study", "bible study", "verses", "medium"],
  [
    "activities-medium-meditation-class",
    "meditation class",
    "stillness",
    "medium",
  ],
  ["activities-medium-blood-donation", "blood donation", "needles", "medium"],
  [
    "activities-medium-community-service",
    "community service",
    "kindness",
    "medium",
  ],
  [
    "activities-medium-neighborhood-watch",
    "neighborhood watch",
    "suspicion",
    "medium",
  ],
  ["activities-medium-town-meeting", "town meeting", "opinions", "medium"],
  ["activities-medium-jury-duty", "jury duty", "boredom", "medium"],
  ["activities-medium-seesawing", "seesawing", "counterweight", "medium"],
  ["activities-medium-chalk-drawing", "chalk drawing", "dust", "medium"],
  ["activities-medium-bubble-blowing", "bubble blowing", "pop", "medium"],
  [
    "activities-medium-sandcastle-building",
    "sandcastle building",
    "tide",
    "medium",
  ],
  ["activities-medium-fort-building", "fort building", "blankets", "medium"],
  ["activities-medium-blanket-fort", "blanket fort", "flashlight", "medium"],
  ["activities-medium-dog-grooming", "dog grooming", "fur", "medium"],
  ["activities-medium-pet-training", "pet training", "treats", "medium"],
  ["activities-medium-canning", "canning", "jars", "medium"],
  ["activities-medium-pickling", "pickling", "vinegar", "medium"],
  ["activities-medium-metal-detecting", "metal detecting", "beeps", "medium"],
  ["activities-medium-fencing", "fencing", "blades", "medium"],
  ["activities-medium-barbering", "barbering", "clippers", "medium"],
  ["activities-medium-tailoring", "tailoring", "alterations", "medium"],
  [
    "activities-medium-electrical-repair",
    "electrical repair",
    "sparks",
    "medium",
  ],
  ["activities-medium-shoe-repair", "shoe repair", "soles", "medium"],
  ["activities-medium-gardening-club", "gardening club", "seedlings", "medium"],
  ["activities-medium-acting-class", "acting class", "pretending", "medium"],
  ["activities-medium-improv-class", "improv class", "panic", "medium"],
  [
    "activities-medium-writing-workshop",
    "writing workshop",
    "revisions",
    "medium",
  ],
  ["activities-medium-city-walking", "city walking", "pavement", "medium"],
  ["activities-medium-nature-walking", "nature walking", "leaves", "medium"],
  ["activities-medium-trail-running", "trail running", "rocks", "medium"],
  ["activities-medium-obstacle-course", "obstacle course", "mud", "medium"],
  ["activities-medium-boot-camp", "boot camp", "yelling", "medium"],
  ["activities-medium-fitness-class", "fitness class", "sweat", "medium"],
  [
    "activities-medium-personal-training",
    "personal training",
    "accountability",
    "medium",
  ],
  ["activities-medium-meal-tracking", "meal tracking", "calories", "medium"],
  ["activities-medium-habit-tracking", "habit tracking", "streaks", "medium"],
  ["activities-medium-affirmations", "affirmations", "confidence", "medium"],
  ["activities-medium-confessing", "confessing", "guilt", "medium"],
  ["activities-medium-confiding", "confiding", "vulnerability", "medium"],
  ["activities-medium-reminiscing", "reminiscing", "stories", "medium"],
  ["activities-medium-prank-calling", "prank calling", "mischief", "medium"],
  ["activities-medium-pranking", "pranking", "mischief", "medium"],
  ["activities-medium-event-planning", "event planning", "logistics", "medium"],
  ["activities-medium-animal-rescue", "animal rescue", "compassion", "medium"],
  ["activities-medium-beach-cleanup", "beach cleanup", "litter", "medium"],
  ["activities-medium-park-cleanup", "park cleanup", "litter", "medium"],
  ["activities-medium-tree-planting", "tree planting", "saplings", "medium"],
  ["activities-medium-fundraising-walk", "fundraising walk", "cause", "medium"],
  ["activities-medium-charity-run", "charity run", "cause", "medium"],
  [
    "activities-medium-marathon-training",
    "marathon training",
    "endurance",
    "medium",
  ],
  ["activities-medium-half-marathon", "half marathon", "endurance", "medium"],
  ["activities-medium-fun-run", "fun run", "costumes", "medium"],
  ["activities-medium-cycling-commute", "cycling commute", "traffic", "medium"],
  ["activities-medium-motorcycling", "motorcycling", "helmet", "medium"],
  ["activities-medium-scootering", "scootering", "wheels", "medium"],
  ["activities-medium-longboarding", "longboarding", "cruising", "medium"],
  ["activities-medium-hunting", "hunting", "camouflage", "medium"],
  ["activities-medium-birding", "birding", "binoculars", "medium"],
  ["activities-medium-restocking", "restocking", "shelves", "medium"],
  ["activities-hard-debugging", "debugging", "frustration", "hard"],
  ["activities-hard-calligraphy", "calligraphy", "ink", "hard"],
  ["activities-hard-metalworking", "metalworking", "sparks", "hard"],
  ["activities-hard-leatherworking", "leatherworking", "stitching", "hard"],
  ["activities-hard-flower-arranging", "flower arranging", "symmetry", "hard"],
  ["activities-hard-music-production", "music production", "layers", "hard"],
  ["activities-hard-calisthenics", "calisthenics", "control", "hard"],
  ["activities-hard-foam-rolling", "foam rolling", "pain", "hard"],
  ["activities-hard-beachcombing", "beachcombing", "treasures", "hard"],
  ["activities-hard-foraging", "foraging", "caution", "hard"],
  ["activities-hard-paragliding", "paragliding", "thermals", "hard"],
  ["activities-hard-tailgating", "tailgating", "coolers", "hard"],
  ["activities-hard-antiquing", "antiquing", "dust", "hard"],
  ["activities-hard-fan-fiction", "fan fiction", "obsession", "hard"],
  ["activities-hard-cosplay-crafting", "cosplay crafting", "glue", "hard"],
  ["activities-hard-app-building", "app building", "bugs", "hard"],
  ["activities-hard-robot-building", "robot building", "wires", "hard"],
  ["activities-hard-beekeeping", "beekeeping", "stings", "hard"],
  ["activities-hard-fishkeeping", "fishkeeping", "algae", "hard"],
  ["activities-hard-aquarium-keeping", "aquarium keeping", "algae", "hard"],
  ["activities-hard-horse-grooming", "horse grooming", "mane", "hard"],
  ["activities-hard-seed-saving", "seed saving", "preservation", "hard"],
  ["activities-hard-home-brewing", "home brewing", "fermentation", "hard"],
  ["activities-hard-cheese-making", "cheese making", "fermentation", "hard"],
  ["activities-hard-ice-fishing", "ice fishing", "stillness", "hard"],
  ["activities-hard-geocaching", "geocaching", "coordinates", "hard"],
  ["activities-hard-orienteering", "orienteering", "compass", "hard"],
  ["activities-hard-paint-pouring", "paint pouring", "marbling", "hard"],
  ["activities-hard-glass-blowing", "glass blowing", "heat", "hard"],
  ["activities-hard-upcycling", "upcycling", "transformation", "hard"],
  ["activities-hard-watch-repair", "watch repair", "tiny", "hard"],
  ["activities-hard-knife-sharpening", "knife sharpening", "edge", "hard"],
  [
    "activities-hard-photography-walk",
    "photography walk",
    "discoveries",
    "hard",
  ],
  ["activities-hard-urban-exploring", "urban exploring", "ruins", "hard"],
  ["activities-hard-train-spotting", "train spotting", "schedules", "hard"],
  ["activities-hard-plane-spotting", "plane spotting", "binoculars", "hard"],
  ["activities-hard-storm-chasing", "storm chasing", "adrenaline", "hard"],
  ["activities-hard-mud-running", "mud running", "chaos", "hard"],
  ["activities-hard-vision-boarding", "vision boarding", "ambition", "hard"],
  ["activities-hard-manifesting", "manifesting", "belief", "hard"],
  ["activities-hard-snowshoeing", "snowshoeing", "crunch", "hard"],
  ["activities-hard-target-practice", "target practice", "focus", "hard"],
] as const;
