export const animalsCatalog = [
  ["animals-easy-dog", "dog", "loyalty", "easy"],
  ["animals-easy-cat", "cat", "judgment", "easy"],
  ["animals-easy-puppy", "puppy", "zoomies", "easy"],
  ["animals-easy-kitten", "kitten", "mischief", "easy"],
  ["animals-easy-horse", "horse", "gallop", "easy"],
  ["animals-easy-pony", "pony", "fairytale", "easy"],
  ["animals-easy-cow", "cow", "bells", "easy"],
  ["animals-easy-bull", "bull", "charge", "easy"],
  ["animals-easy-calf", "calf", "wobbly", "easy"],
  ["animals-easy-pig", "pig", "mud", "easy"],
  ["animals-easy-piglet", "piglet", "squealing", "easy"],
  ["animals-easy-sheep", "sheep", "counting", "easy"],
  ["animals-easy-lamb", "lamb", "innocence", "easy"],
  ["animals-easy-goat", "goat", "climbing", "easy"],
  ["animals-easy-donkey", "donkey", "burden", "easy"],
  ["animals-easy-chicken", "chicken", "coward", "easy"],
  ["animals-easy-hen", "hen", "nesting", "easy"],
  ["animals-easy-rooster", "rooster", "alarm", "easy"],
  ["animals-easy-chick", "chick", "hatching", "easy"],
  ["animals-easy-duck", "duck", "waddle", "easy"],
  ["animals-easy-duckling", "duckling", "following", "easy"],
  ["animals-easy-goose", "goose", "hissing", "easy"],
  ["animals-easy-turkey", "turkey", "leftovers", "easy"],
  ["animals-easy-rabbit", "rabbit", "magic", "easy"],
  ["animals-easy-bunny", "bunny", "cuddly", "easy"],
  ["animals-easy-hamster", "hamster", "spinning", "easy"],
  ["animals-easy-guinea-pig", "guinea pig", "experiment", "easy"],
  ["animals-easy-mouse", "mouse", "trap", "easy"],
  ["animals-easy-rat", "rat", "plague", "easy"],
  ["animals-easy-goldfish", "goldfish", "forgetful", "easy"],
  ["animals-easy-parrot", "parrot", "imitation", "easy"],
  ["animals-easy-turtle", "turtle", "patience", "easy"],
  ["animals-easy-tortoise", "tortoise", "race", "easy"],
  ["animals-easy-frog", "frog", "jumping", "easy"],
  ["animals-easy-toad", "toad", "witchcraft", "easy"],
  ["animals-easy-snake", "snake", "betrayal", "easy"],
  ["animals-easy-lizard", "lizard", "sunbathing", "easy"],
  ["animals-easy-lion", "lion", "courage", "easy"],
  ["animals-easy-tiger", "tiger", "ambush", "easy"],
  ["animals-easy-bear", "bear", "hibernation", "easy"],
  ["animals-easy-panda", "panda", "clumsy", "easy"],
  ["animals-easy-koala", "koala", "sleepy", "easy"],
  ["animals-easy-kangaroo", "kangaroo", "boxing", "easy"],
  ["animals-easy-elephant", "elephant", "memory", "easy"],
  ["animals-easy-giraffe", "giraffe", "reaching", "easy"],
  ["animals-easy-zebra", "zebra", "barcode", "easy"],
  ["animals-easy-rhino", "rhino", "charging", "easy"],
  ["animals-easy-hippo", "hippo", "yawning", "easy"],
  ["animals-easy-cheetah", "cheetah", "blur", "easy"],
  ["animals-easy-leopard", "leopard", "fashion", "easy"],
  ["animals-easy-gorilla", "gorilla", "strength", "easy"],
  ["animals-easy-chimpanzee", "chimpanzee", "clever", "easy"],
  ["animals-easy-monkey", "monkey", "mischief", "easy"],
  ["animals-easy-sloth", "sloth", "delay", "easy"],
  ["animals-easy-camel", "camel", "endurance", "easy"],
  ["animals-easy-reindeer", "reindeer", "sleigh", "easy"],
  ["animals-easy-moose", "moose", "traffic", "easy"],
  ["animals-easy-deer", "deer", "headlights", "easy"],
  ["animals-easy-wolf", "wolf", "moon", "easy"],
  ["animals-easy-fox", "fox", "cunning", "easy"],
  ["animals-easy-raccoon", "raccoon", "trash", "easy"],
  ["animals-easy-skunk", "skunk", "stink", "easy"],
  ["animals-easy-squirrel", "squirrel", "hoarding", "easy"],
  ["animals-easy-chipmunk", "chipmunk", "stuffing", "easy"],
  ["animals-easy-beaver", "beaver", "engineering", "easy"],
  ["animals-easy-otter", "otter", "playful", "easy"],
  ["animals-easy-hedgehog", "hedgehog", "curling", "easy"],
  ["animals-easy-bat", "bat", "vampire", "easy"],
  ["animals-easy-polar-bear", "polar bear", "melting", "easy"],
  ["animals-easy-fish", "fish", "flopping", "easy"],
  ["animals-easy-shark", "shark", "panic", "easy"],
  ["animals-easy-whale", "whale", "singing", "easy"],
  ["animals-easy-dolphin", "dolphin", "intelligence", "easy"],
  ["animals-easy-orca", "orca", "apex", "easy"],
  ["animals-easy-seal", "seal", "slippery", "easy"],
  ["animals-easy-sea-lion", "sea lion", "applause", "easy"],
  ["animals-easy-walrus", "walrus", "lumbering", "easy"],
  ["animals-easy-octopus", "octopus", "escape", "easy"],
  ["animals-easy-squid", "squid", "ink", "easy"],
  ["animals-easy-jellyfish", "jellyfish", "sting", "easy"],
  ["animals-easy-starfish", "starfish", "regeneration", "easy"],
  ["animals-easy-seahorse", "seahorse", "pregnancy", "easy"],
  ["animals-easy-crab", "crab", "sideways", "easy"],
  ["animals-easy-lobster", "lobster", "luxury", "easy"],
  ["animals-easy-shrimp", "shrimp", "smallness", "easy"],
  ["animals-easy-clam", "clam", "silent", "easy"],
  ["animals-easy-oyster", "oyster", "pearls", "easy"],
  ["animals-easy-snail", "snail", "slow", "easy"],
  ["animals-easy-eel", "eel", "electric", "easy"],
  ["animals-easy-salmon", "salmon", "upstream", "easy"],
  ["animals-easy-tuna", "tuna", "canned", "easy"],
  ["animals-easy-piranha", "piranha", "frenzy", "easy"],
  ["animals-easy-stingray", "stingray", "glide", "easy"],
  ["animals-easy-sea-turtle", "sea turtle", "longevity", "easy"],
  ["animals-easy-bird", "bird", "freedom", "easy"],
  ["animals-easy-eagle", "eagle", "patriotism", "easy"],
  ["animals-easy-hawk", "hawk", "focus", "easy"],
  ["animals-easy-falcon", "falcon", "dive", "easy"],
  ["animals-easy-owl", "owl", "wisdom", "easy"],
  ["animals-easy-crow", "crow", "plotting", "easy"],
  ["animals-easy-raven", "raven", "omen", "easy"],
  ["animals-easy-pigeon", "pigeon", "crumbs", "easy"],
  ["animals-easy-dove", "dove", "peace", "easy"],
  ["animals-easy-sparrow", "sparrow", "fragile", "easy"],
  ["animals-easy-robin", "robin", "spring", "easy"],
  ["animals-easy-seagull", "seagull", "theft", "easy"],
  ["animals-easy-pelican", "pelican", "scooping", "easy"],
  ["animals-easy-flamingo", "flamingo", "balance", "easy"],
  ["animals-easy-penguin", "penguin", "tuxedo", "easy"],
  ["animals-easy-ostrich", "ostrich", "denial", "easy"],
  ["animals-easy-peacock", "peacock", "vanity", "easy"],
  ["animals-easy-swan", "swan", "grace", "easy"],
  ["animals-easy-hummingbird", "hummingbird", "hovering", "easy"],
  ["animals-easy-toucan", "toucan", "rainbow", "easy"],
  ["animals-easy-parakeet", "parakeet", "chatter", "easy"],
  ["animals-easy-vulture", "vulture", "cleanup", "easy"],
  ["animals-easy-crocodile", "crocodile", "lurking", "easy"],
  ["animals-easy-alligator", "alligator", "snap", "easy"],
  ["animals-easy-gecko", "gecko", "insurance", "easy"],
  ["animals-easy-iguana", "iguana", "basking", "easy"],
  ["animals-easy-chameleon", "chameleon", "camouflage", "easy"],
  ["animals-easy-cobra", "cobra", "hypnosis", "easy"],
  ["animals-easy-python", "python", "squeeze", "easy"],
  ["animals-easy-anaconda", "anaconda", "giant", "easy"],
  ["animals-easy-rattlesnake", "rattlesnake", "warning", "easy"],
  ["animals-easy-salamander", "salamander", "damp", "easy"],
  ["animals-easy-tadpole", "tadpole", "transformation", "easy"],
  ["animals-easy-butterfly", "butterfly", "transformation", "easy"],
  ["animals-easy-moth", "moth", "temptation", "easy"],
  ["animals-easy-bee", "bee", "busy", "easy"],
  ["animals-easy-wasp", "wasp", "anger", "easy"],
  ["animals-easy-hornet", "hornet", "rage", "easy"],
  ["animals-easy-ant", "ant", "teamwork", "easy"],
  ["animals-easy-termite", "termite", "damage", "easy"],
  ["animals-easy-beetle", "beetle", "armor", "easy"],
  ["animals-easy-ladybug", "ladybug", "luck", "easy"],
  ["animals-easy-firefly", "firefly", "glow", "easy"],
  ["animals-easy-dragonfly", "dragonfly", "hovering", "easy"],
  ["animals-easy-grasshopper", "grasshopper", "leap", "easy"],
  ["animals-easy-cricket", "cricket", "awkward", "easy"],
  ["animals-easy-cockroach", "cockroach", "survival", "easy"],
  ["animals-easy-mosquito", "mosquito", "itch", "easy"],
  ["animals-easy-fly", "fly", "annoyance", "easy"],
  ["animals-easy-gnat", "gnat", "nuisance", "easy"],
  ["animals-easy-flea", "flea", "itching", "easy"],
  ["animals-easy-tick", "tick", "paranoia", "easy"],
  ["animals-easy-spider", "spider", "panic", "easy"],
  ["animals-easy-tarantula", "tarantula", "nightmare", "easy"],
  ["animals-easy-scorpion", "scorpion", "sting", "easy"],
  ["animals-easy-centipede", "centipede", "crawling", "easy"],
  ["animals-easy-worm", "worm", "bait", "easy"],
  ["animals-easy-earthworm", "earthworm", "compost", "easy"],
  ["animals-easy-leech", "leech", "draining", "easy"],
  ["animals-easy-caterpillar", "caterpillar", "change", "easy"],
  ["animals-easy-praying-mantis", "praying mantis", "pose", "easy"],
  ["animals-easy-labrador", "labrador", "fetch", "easy"],
  ["animals-easy-bulldog", "bulldog", "stubborn", "easy"],
  ["animals-easy-poodle", "poodle", "fancy", "easy"],
  ["animals-easy-beagle", "beagle", "sniffing", "easy"],
  ["animals-easy-chihuahua", "chihuahua", "trembling", "easy"],
  ["animals-easy-husky", "husky", "tantrum", "easy"],
  ["animals-easy-pug", "pug", "snoring", "easy"],
  ["animals-easy-terrier", "terrier", "digging", "easy"],
  ["animals-easy-dalmatian", "dalmatian", "firefighters", "easy"],
  ["animals-easy-german-shepherd", "german shepherd", "security", "easy"],
  ["animals-easy-golden-retriever", "golden retriever", "fetch", "easy"],
  ["animals-easy-tabby", "tabby", "lounging", "easy"],
  ["animals-easy-dinosaur", "dinosaur", "extinction", "easy"],
  ["animals-easy-t-rex", "t rex", "footsteps", "easy"],
  ["animals-easy-tyrannosaurus", "tyrannosaurus", "terror", "easy"],
  ["animals-easy-triceratops", "triceratops", "charging", "easy"],
  ["animals-easy-mammoth", "mammoth", "ancient", "easy"],
  ["animals-easy-dodo", "dodo", "gone", "easy"],
  ["animals-medium-mule", "mule", "kick", "medium"],
  ["animals-medium-ferret", "ferret", "sneaky", "medium"],
  ["animals-medium-gerbil", "gerbil", "tunneling", "medium"],
  ["animals-medium-canary", "canary", "warning", "medium"],
  ["animals-medium-jaguar", "jaguar", "luxury", "medium"],
  ["animals-medium-panther", "panther", "shadow", "medium"],
  ["animals-medium-orangutan", "orangutan", "curious", "medium"],
  ["animals-medium-baboon", "baboon", "chaos", "medium"],
  ["animals-medium-lemur", "lemur", "bouncing", "medium"],
  ["animals-medium-anteater", "anteater", "vacuum", "medium"],
  ["animals-medium-armadillo", "armadillo", "curling", "medium"],
  ["animals-medium-meerkat", "meerkat", "lookout", "medium"],
  ["animals-medium-hyena", "hyena", "laughter", "medium"],
  ["animals-medium-warthog", "warthog", "gruff", "medium"],
  ["animals-medium-gazelle", "gazelle", "grace", "medium"],
  ["animals-medium-antelope", "antelope", "agility", "medium"],
  ["animals-medium-wildebeest", "wildebeest", "stampede", "medium"],
  ["animals-medium-buffalo", "buffalo", "roaming", "medium"],
  ["animals-medium-bison", "bison", "frontier", "medium"],
  ["animals-medium-llama", "llama", "spit", "medium"],
  ["animals-medium-alpaca", "alpaca", "softness", "medium"],
  ["animals-medium-yak", "yak", "altitude", "medium"],
  ["animals-medium-elk", "elk", "majesty", "medium"],
  ["animals-medium-boar", "boar", "rampage", "medium"],
  ["animals-medium-capybara", "capybara", "chill", "medium"],
  ["animals-medium-wombat", "wombat", "cubes", "medium"],
  ["animals-medium-platypus", "platypus", "bizarre", "medium"],
  ["animals-medium-dingo", "dingo", "outlaw", "medium"],
  ["animals-medium-wallaby", "wallaby", "bouncing", "medium"],
  ["animals-medium-opossum", "opossum", "fainting", "medium"],
  ["animals-medium-possum", "possum", "playing", "medium"],
  ["animals-medium-coyote", "coyote", "trickster", "medium"],
  ["animals-medium-jackal", "jackal", "scheming", "medium"],
  ["animals-medium-badger", "badger", "persistence", "medium"],
  ["animals-medium-weasel", "weasel", "sneaky", "medium"],
  ["animals-medium-mink", "mink", "luxury", "medium"],
  ["animals-medium-mongoose", "mongoose", "dueling", "medium"],
  ["animals-medium-porcupine", "porcupine", "defensive", "medium"],
  ["animals-medium-mole", "mole", "tunneling", "medium"],
  ["animals-medium-hare", "hare", "racing", "medium"],
  ["animals-medium-bobcat", "bobcat", "stalking", "medium"],
  ["animals-medium-lynx", "lynx", "silence", "medium"],
  ["animals-medium-cougar", "cougar", "prowling", "medium"],
  ["animals-medium-puma", "puma", "agility", "medium"],
  ["animals-medium-wildcat", "wildcat", "feral", "medium"],
  ["animals-medium-red-panda", "red panda", "adorable", "medium"],
  ["animals-medium-brown-bear", "brown bear", "porridge", "medium"],
  ["animals-medium-grizzly-bear", "grizzly bear", "mauling", "medium"],
  ["animals-medium-black-bear", "black bear", "raiding", "medium"],
  ["animals-medium-snow-leopard", "snow leopard", "elusive", "medium"],
  ["animals-medium-mountain-lion", "mountain lion", "stalking", "medium"],
  ["animals-medium-arctic-fox", "arctic fox", "snow", "medium"],
  ["animals-medium-red-fox", "red fox", "cunning", "medium"],
  ["animals-medium-tasmanian-devil", "tasmanian devil", "tantrum", "medium"],
  ["animals-medium-prairie-dog", "prairie dog", "lookout", "medium"],
  ["animals-medium-groundhog", "groundhog", "forecast", "medium"],
  ["animals-medium-gopher", "gopher", "holes", "medium"],
  ["animals-medium-chinchilla", "chinchilla", "softness", "medium"],
  ["animals-medium-aardvark", "aardvark", "snuffling", "medium"],
  ["animals-medium-manatee", "manatee", "gentle", "medium"],
  ["animals-medium-ape", "ape", "evolution", "medium"],
  ["animals-medium-gibbon", "gibbon", "swinging", "medium"],
  ["animals-medium-capuchin", "capuchin", "tools", "medium"],
  ["animals-medium-howler-monkey", "howler monkey", "volume", "medium"],
  ["animals-medium-spider-monkey", "spider monkey", "acrobatics", "medium"],
  ["animals-medium-prawn", "prawn", "cocktail", "medium"],
  ["animals-medium-mussel", "mussel", "flexing", "medium"],
  ["animals-medium-scallop", "scallop", "fancy", "medium"],
  ["animals-medium-slug", "slug", "slime", "medium"],
  ["animals-medium-coral", "coral", "bleaching", "medium"],
  ["animals-medium-sponge", "sponge", "absorbing", "medium"],
  ["animals-medium-trout", "trout", "rainbow", "medium"],
  ["animals-medium-bass", "bass", "lure", "medium"],
  ["animals-medium-cod", "cod", "bland", "medium"],
  ["animals-medium-catfish", "catfish", "deception", "medium"],
  ["animals-medium-carp", "carp", "complaining", "medium"],
  ["animals-medium-koi", "koi", "serenity", "medium"],
  ["animals-medium-clownfish", "clownfish", "lost", "medium"],
  ["animals-medium-angelfish", "angelfish", "graceful", "medium"],
  ["animals-medium-guppy", "guppy", "small", "medium"],
  ["animals-medium-betta", "betta", "fighting", "medium"],
  ["animals-medium-sardine", "sardine", "packed", "medium"],
  ["animals-medium-anchovy", "anchovy", "salty", "medium"],
  ["animals-medium-mackerel", "mackerel", "oily", "medium"],
  ["animals-medium-herring", "herring", "misdirection", "medium"],
  ["animals-medium-swordfish", "swordfish", "fencing", "medium"],
  ["animals-medium-marlin", "marlin", "trophy", "medium"],
  ["animals-medium-barracuda", "barracuda", "menace", "medium"],
  ["animals-medium-flounder", "flounder", "stumbling", "medium"],
  ["animals-medium-halibut", "halibut", "flat", "medium"],
  ["animals-medium-manta-ray", "manta ray", "gliding", "medium"],
  ["animals-medium-hammerhead-shark", "hammerhead shark", "toolbox", "medium"],
  ["animals-medium-pufferfish", "pufferfish", "inflation", "medium"],
  ["animals-medium-blowfish", "blowfish", "poison", "medium"],
  ["animals-medium-lionfish", "lionfish", "invasive", "medium"],
  ["animals-medium-blue-whale", "blue whale", "massive", "medium"],
  ["animals-medium-humpback-whale", "humpback whale", "singing", "medium"],
  ["animals-medium-beluga-whale", "beluga whale", "smile", "medium"],
  ["animals-medium-narwhal", "narwhal", "unicorn", "medium"],
  ["animals-medium-killer-whale", "killer whale", "apex", "medium"],
  ["animals-medium-sea-otter", "sea otter", "holding", "medium"],
  ["animals-medium-sea-urchin", "sea urchin", "ouch", "medium"],
  ["animals-medium-hermit-crab", "hermit crab", "borrowed", "medium"],
  ["animals-medium-king-crab", "king crab", "feast", "medium"],
  ["animals-medium-ray", "ray", "gliding", "medium"],
  ["animals-medium-megalodon", "megalodon", "prehistoric", "medium"],
  ["animals-medium-blobfish", "blobfish", "ugly", "medium"],
  ["animals-medium-axolotl", "axolotl", "regeneration", "medium"],
  ["animals-medium-blue-jay", "blue jay", "loud", "medium"],
  ["animals-medium-cardinal", "cardinal", "pope", "medium"],
  ["animals-medium-finch", "finch", "delicate", "medium"],
  ["animals-medium-swallow", "swallow", "migration", "medium"],
  ["animals-medium-emu", "emu", "sprinting", "medium"],
  ["animals-medium-crane", "crane", "folding", "medium"],
  ["animals-medium-stork", "stork", "delivery", "medium"],
  ["animals-medium-heron", "heron", "stillness", "medium"],
  ["animals-medium-kingfisher", "kingfisher", "diving", "medium"],
  ["animals-medium-woodpecker", "woodpecker", "knocking", "medium"],
  ["animals-medium-macaw", "macaw", "colorful", "medium"],
  ["animals-medium-cockatoo", "cockatoo", "screaming", "medium"],
  ["animals-medium-cockatiel", "cockatiel", "whistling", "medium"],
  ["animals-medium-lovebird", "lovebird", "romance", "medium"],
  ["animals-medium-magpie", "magpie", "shiny", "medium"],
  ["animals-medium-condor", "condor", "soaring", "medium"],
  ["animals-medium-albatross", "albatross", "burden", "medium"],
  ["animals-medium-puffin", "puffin", "awkward", "medium"],
  ["animals-medium-kiwi", "kiwi", "nocturnal", "medium"],
  ["animals-medium-cassowary", "cassowary", "deadly", "medium"],
  ["animals-medium-quail", "quail", "nervous", "medium"],
  ["animals-medium-pheasant", "pheasant", "hunting", "medium"],
  ["animals-medium-partridge", "partridge", "carol", "medium"],
  ["animals-medium-loon", "loon", "haunting", "medium"],
  ["animals-medium-ibis", "ibis", "sacred", "medium"],
  ["animals-medium-egret", "egret", "elegance", "medium"],
  ["animals-medium-viper", "viper", "venom", "medium"],
  ["animals-medium-boa-constrictor", "boa constrictor", "squeeze", "medium"],
  ["animals-medium-newt", "newt", "potion", "medium"],
  ["animals-medium-monitor-lizard", "monitor lizard", "watching", "medium"],
  ["animals-medium-komodo-dragon", "komodo dragon", "bite", "medium"],
  ["animals-medium-bearded-dragon", "bearded dragon", "heatlamp", "medium"],
  ["animals-medium-locust", "locust", "plague", "medium"],
  ["animals-medium-millipede", "millipede", "crawling", "medium"],
  ["animals-medium-mantis", "mantis", "patience", "medium"],
  ["animals-medium-cicada", "cicada", "chorus", "medium"],
  ["animals-medium-silverfish", "silverfish", "books", "medium"],
  ["animals-medium-retriever", "retriever", "fetch", "medium"],
  ["animals-medium-boxer", "boxer", "punching", "medium"],
  ["animals-medium-greyhound", "greyhound", "speed", "medium"],
  ["animals-medium-collie", "collie", "herding", "medium"],
  ["animals-medium-corgi", "corgi", "loaf", "medium"],
  ["animals-medium-mastiff", "mastiff", "guarding", "medium"],
  ["animals-medium-dachshund", "dachshund", "stretch", "medium"],
  ["animals-medium-rottweiler", "rottweiler", "intimidation", "medium"],
  ["animals-medium-pit-bull", "pit bull", "controversy", "medium"],
  ["animals-medium-siamese", "siamese", "vocal", "medium"],
  ["animals-medium-persian", "persian", "fluff", "medium"],
  ["animals-medium-velociraptor", "velociraptor", "strategy", "medium"],
  ["animals-medium-stegosaurus", "stegosaurus", "defense", "medium"],
  ["animals-medium-brontosaurus", "brontosaurus", "towering", "medium"],
  ["animals-medium-pterodactyl", "pterodactyl", "screech", "medium"],
  ["animals-medium-woolly-mammoth", "woolly mammoth", "frozen", "medium"],
  [
    "animals-medium-sabertooth-tiger",
    "sabertooth tiger",
    "prehistoric",
    "medium",
  ],
  ["animals-hard-budgie", "budgie", "chatter", "hard"],
  ["animals-hard-tapir", "tapir", "weird", "hard"],
  ["animals-hard-okapi", "okapi", "confusion", "hard"],
  ["animals-hard-quokka", "quokka", "selfie", "hard"],
  ["animals-hard-echidna", "echidna", "oddball", "hard"],
  ["animals-hard-marten", "marten", "nimble", "hard"],
  ["animals-hard-shrew", "shrew", "twitchy", "hard"],
  ["animals-hard-ocelot", "ocelot", "sleek", "hard"],
  ["animals-hard-serval", "serval", "leaping", "hard"],
  ["animals-hard-caracal", "caracal", "spring", "hard"],
  ["animals-hard-clouded-leopard", "clouded leopard", "mystery", "hard"],
  ["animals-hard-fennec-fox", "fennec fox", "listening", "hard"],
  ["animals-hard-sugar-glider", "sugar glider", "soaring", "hard"],
  ["animals-hard-marmot", "marmot", "whistle", "hard"],
  ["animals-hard-vole", "vole", "nibbles", "hard"],
  ["animals-hard-lemming", "lemming", "cliff", "hard"],
  ["animals-hard-muskrat", "muskrat", "odor", "hard"],
  ["animals-hard-aye-aye", "aye aye", "creepy", "hard"],
  ["animals-hard-pangolin", "pangolin", "curling", "hard"],
  ["animals-hard-dugong", "dugong", "gentle", "hard"],
  ["animals-hard-bonobo", "bonobo", "peace", "hard"],
  ["animals-hard-macaque", "macaque", "boldness", "hard"],
  ["animals-hard-mandrill", "mandrill", "colorful", "hard"],
  ["animals-hard-marmoset", "marmoset", "pocket", "hard"],
  ["animals-hard-tamarin", "tamarin", "mustache", "hard"],
  ["animals-hard-cuttlefish", "cuttlefish", "disguise", "hard"],
  ["animals-hard-porpoise", "porpoise", "shy", "hard"],
  ["animals-hard-sea-cucumber", "sea cucumber", "squishy", "hard"],
  ["animals-hard-horseshoe-crab", "horseshoe crab", "ancient", "hard"],
  ["animals-hard-caiman", "caiman", "snap", "hard"],
  ["animals-hard-caecilian", "caecilian", "burrowing", "hard"],
  ["animals-hard-skink", "skink", "smooth", "hard"],
  ["animals-hard-gila-monster", "gila monster", "poison", "hard"],
  ["animals-hard-terrapin", "terrapin", "sunning", "hard"],
  ["animals-hard-louse", "louse", "itching", "hard"],
  ["animals-hard-silkworm", "silkworm", "weaving", "hard"],
  ["animals-hard-aphid", "aphid", "sap", "hard"],
  ["animals-hard-weevil", "weevil", "holes", "hard"],
  ["animals-hard-earwig", "earwig", "myth", "hard"],
  ["animals-hard-mayfly", "mayfly", "fleeting", "hard"],
  ["animals-hard-damselfly", "damselfly", "delicate", "hard"],
  ["animals-hard-sphynx", "sphynx", "bald", "hard"],
  ["animals-hard-maine-coon", "maine coon", "giant", "hard"],
  ["animals-hard-bengal-cat", "bengal cat", "wildness", "hard"],
  ["animals-hard-ragdoll", "ragdoll", "floppy", "hard"],
] as const;
