export const foodCatalog = [
  ["food-easy-apple", "apple", "gravity", "easy"],
  ["food-easy-banana", "banana", "slippery", "easy"],
  ["food-easy-orange", "orange", "immunity", "easy"],
  ["food-easy-grape", "grape", "bunch", "easy"],
  ["food-easy-strawberry", "strawberry", "blush", "easy"],
  ["food-easy-blueberry", "blueberry", "stain", "easy"],
  ["food-easy-raspberry", "raspberry", "fuzz", "easy"],
  ["food-easy-blackberry", "blackberry", "thorns", "easy"],
  ["food-easy-watermelon", "watermelon", "hydration", "easy"],
  ["food-easy-pineapple", "pineapple", "prickly", "easy"],
  ["food-easy-mango", "mango", "fibers", "easy"],
  ["food-easy-peach", "peach", "velvet", "easy"],
  ["food-easy-pear", "pear", "grainy", "easy"],
  ["food-easy-cherry", "cherry", "lipstick", "easy"],
  ["food-easy-plum", "plum", "wrinkle", "easy"],
  ["food-easy-kiwi", "kiwi", "furry", "easy"],
  ["food-easy-lemon", "lemon", "cleaning", "easy"],
  ["food-easy-lime", "lime", "sting", "easy"],
  ["food-easy-coconut", "coconut", "cracking", "easy"],
  ["food-easy-melon", "melon", "scooping", "easy"],
  ["food-easy-avocado", "avocado", "smash", "easy"],
  ["food-easy-tomato", "tomato", "debate", "easy"],
  ["food-easy-potato", "potato", "buried", "easy"],
  ["food-easy-carrot", "carrot", "vision", "easy"],
  ["food-easy-onion", "onion", "layers", "easy"],
  ["food-easy-garlic", "garlic", "breath", "easy"],
  ["food-easy-lettuce", "lettuce", "wilt", "easy"],
  ["food-easy-spinach", "spinach", "strength", "easy"],
  ["food-easy-cabbage", "cabbage", "shredded", "easy"],
  ["food-easy-broccoli", "broccoli", "punishment", "easy"],
  ["food-easy-cauliflower", "cauliflower", "pale", "easy"],
  ["food-easy-cucumber", "cucumber", "cool", "easy"],
  ["food-easy-eggplant", "eggplant", "spongy", "easy"],
  ["food-easy-pepper", "pepper", "sneeze", "easy"],
  ["food-easy-corn", "corn", "maze", "easy"],
  ["food-easy-peas", "peas", "rolling", "easy"],
  ["food-easy-beans", "beans", "gas", "easy"],
  ["food-easy-mushroom", "mushroom", "umbrellas", "easy"],
  ["food-easy-celery", "celery", "stringy", "easy"],
  ["food-easy-pumpkin", "pumpkin", "midnight", "easy"],
  ["food-easy-olive", "olive", "branch", "easy"],
  ["food-easy-pickle", "pickle", "snap", "easy"],
  ["food-easy-chili", "chili", "sweat", "easy"],
  ["food-easy-ginger", "ginger", "nausea", "easy"],
  ["food-easy-mint", "mint", "freshness", "easy"],
  ["food-easy-cinnamon", "cinnamon", "warmth", "easy"],
  ["food-easy-vanilla", "vanilla", "plain", "easy"],
  ["food-easy-cocoa", "cocoa", "richness", "easy"],
  ["food-easy-salt", "salt", "thirst", "easy"],
  ["food-easy-sugar", "sugar", "addiction", "easy"],
  ["food-easy-honey", "honey", "slow", "easy"],
  ["food-easy-flour", "flour", "dust", "easy"],
  ["food-easy-dough", "dough", "elasticity", "easy"],
  ["food-easy-yeast", "yeast", "rising", "easy"],
  ["food-easy-rice", "rice", "clumping", "easy"],
  ["food-easy-pasta", "pasta", "boiling", "easy"],
  ["food-easy-noodle", "noodle", "slurping", "easy"],
  ["food-easy-bread", "bread", "survival", "easy"],
  ["food-easy-toast", "toast", "pop", "easy"],
  ["food-easy-bagel", "bagel", "chewy", "easy"],
  ["food-easy-biscuit", "biscuit", "crumbly", "easy"],
  ["food-easy-muffin", "muffin", "crumbly", "easy"],
  ["food-easy-pancake", "pancake", "flipping", "easy"],
  ["food-easy-waffle", "waffle", "pockets", "easy"],
  ["food-easy-tortilla", "tortilla", "folding", "easy"],
  ["food-easy-pretzel", "pretzel", "contortion", "easy"],
  ["food-easy-cracker", "cracker", "snap", "easy"],
  ["food-easy-cereal", "cereal", "crunch", "easy"],
  ["food-easy-oatmeal", "oatmeal", "mushy", "easy"],
  ["food-easy-granola", "granola", "rugged", "easy"],
  ["food-easy-almond", "almond", "roasting", "easy"],
  ["food-easy-peanut", "peanut", "allergy", "easy"],
  ["food-easy-walnut", "walnut", "wrinkles", "easy"],
  ["food-easy-egg", "egg", "fragile", "easy"],
  ["food-easy-milk", "milk", "mustache", "easy"],
  ["food-easy-butter", "butter", "melting", "easy"],
  ["food-easy-cheese", "cheese", "trap", "easy"],
  ["food-easy-yogurt", "yogurt", "tangy", "easy"],
  ["food-easy-cream", "cream", "silky", "easy"],
  ["food-easy-cream-cheese", "cream cheese", "smear", "easy"],
  ["food-easy-sour-cream", "sour cream", "tangy", "easy"],
  ["food-easy-cheddar", "cheddar", "sharpness", "easy"],
  ["food-easy-parmesan", "parmesan", "grating", "easy"],
  ["food-easy-ice-cream", "ice cream", "happiness", "easy"],
  ["food-easy-beef", "beef", "muscle", "easy"],
  ["food-easy-pork", "pork", "sizzle", "easy"],
  ["food-easy-chicken", "chicken", "crossing", "easy"],
  ["food-easy-turkey", "turkey", "pardon", "easy"],
  ["food-easy-lamb", "lamb", "wool", "easy"],
  ["food-easy-duck", "duck", "waddle", "easy"],
  ["food-easy-fish", "fish", "hooks", "easy"],
  ["food-easy-salmon", "salmon", "river", "easy"],
  ["food-easy-tuna", "tuna", "mercury", "easy"],
  ["food-easy-shrimp", "shrimp", "tiny", "easy"],
  ["food-easy-crab", "crab", "sideways", "easy"],
  ["food-easy-lobster", "lobster", "luxury", "easy"],
  ["food-easy-bacon", "bacon", "crispy", "easy"],
  ["food-easy-sausage", "sausage", "sizzle", "easy"],
  ["food-easy-ham", "ham", "glossy", "easy"],
  ["food-easy-salami", "salami", "cured", "easy"],
  ["food-easy-pepperoni", "pepperoni", "grease", "easy"],
  ["food-easy-hot-dog", "hot dog", "stadium", "easy"],
  ["food-easy-meatball", "meatball", "rolling", "easy"],
  ["food-easy-steak", "steak", "searing", "easy"],
  ["food-easy-ribs", "ribs", "bones", "easy"],
  ["food-easy-burger", "burger", "layers", "easy"],
  ["food-easy-cheeseburger", "cheeseburger", "melty", "easy"],
  ["food-easy-sandwich", "sandwich", "stacked", "easy"],
  ["food-easy-wrap", "wrap", "portable", "easy"],
  ["food-easy-burrito", "burrito", "stuffed", "easy"],
  ["food-easy-taco", "taco", "folding", "easy"],
  ["food-easy-nachos", "nachos", "loaded", "easy"],
  ["food-easy-salsa", "salsa", "dancing", "easy"],
  ["food-easy-guacamole", "guacamole", "chunky", "easy"],
  ["food-easy-hummus", "hummus", "smooth", "easy"],
  ["food-easy-pizza", "pizza", "delivery", "easy"],
  ["food-easy-lasagna", "lasagna", "layers", "easy"],
  ["food-easy-spaghetti", "spaghetti", "tangled", "easy"],
  ["food-easy-macaroni", "macaroni", "crafts", "easy"],
  ["food-easy-ravioli", "ravioli", "pillows", "easy"],
  ["food-easy-sushi", "sushi", "delicate", "easy"],
  ["food-easy-ramen", "ramen", "broke", "easy"],
  ["food-easy-dumpling", "dumpling", "pinch", "easy"],
  ["food-easy-curry", "curry", "aroma", "easy"],
  ["food-easy-tofu", "tofu", "squishy", "easy"],
  ["food-easy-soup", "soup", "comfort", "easy"],
  ["food-easy-stew", "stew", "hearty", "easy"],
  ["food-easy-salad", "salad", "freshness", "easy"],
  ["food-easy-omelet", "omelet", "folding", "easy"],
  ["food-easy-hashbrown", "hashbrown", "crispy", "easy"],
  ["food-easy-fries", "fries", "soggy", "easy"],
  ["food-easy-chips", "chips", "salty", "easy"],
  ["food-easy-popcorn", "popcorn", "suspense", "easy"],
  ["food-easy-french-fries", "french fries", "salty", "easy"],
  ["food-easy-stuffing", "stuffing", "packed", "easy"],
  ["food-easy-gravy", "gravy", "pouring", "easy"],
  ["food-easy-cheesecake", "cheesecake", "dense", "easy"],
  ["food-easy-cupcake", "cupcake", "tiny", "easy"],
  ["food-easy-brownie", "brownie", "fudgy", "easy"],
  ["food-easy-cookie", "cookie", "sneak", "easy"],
  ["food-easy-gingerbread", "gingerbread", "fairytale", "easy"],
  ["food-easy-donut", "donut", "glazed", "easy"],
  ["food-easy-pudding", "pudding", "wiggle", "easy"],
  ["food-easy-jello", "jello", "jiggle", "easy"],
  ["food-easy-marshmallow", "marshmallow", "puffy", "easy"],
  ["food-easy-fudge", "fudge", "dense", "easy"],
  ["food-easy-caramel", "caramel", "sticky", "easy"],
  ["food-easy-lollipop", "lollipop", "patience", "easy"],
  ["food-easy-chocolate", "chocolate", "melting", "easy"],
  ["food-easy-candy", "candy", "cavities", "easy"],
  ["food-easy-mints", "mints", "breath", "easy"],
  ["food-easy-jellybean", "jellybean", "counting", "easy"],
  ["food-easy-cotton-candy", "cotton candy", "cloud", "easy"],
  ["food-easy-popsicle", "popsicle", "melting", "easy"],
  ["food-easy-snow-cone", "snow cone", "staining", "easy"],
  ["food-easy-milkshake", "milkshake", "thick", "easy"],
  ["food-easy-smoothie", "smoothie", "silky", "easy"],
  ["food-easy-juice", "juice", "squeeze", "easy"],
  ["food-easy-lemonade", "lemonade", "pucker", "easy"],
  ["food-easy-water", "water", "survival", "easy"],
  ["food-easy-soda", "soda", "burp", "easy"],
  ["food-easy-cola", "cola", "fizz", "easy"],
  ["food-easy-root-beer", "root beer", "nostalgia", "easy"],
  ["food-easy-ginger-ale", "ginger ale", "nausea", "easy"],
  ["food-easy-coffee", "coffee", "jitters", "easy"],
  ["food-easy-espresso", "espresso", "intensity", "easy"],
  ["food-easy-latte", "latte", "swirl", "easy"],
  ["food-easy-cappuccino", "cappuccino", "froth", "easy"],
  ["food-easy-mocha", "mocha", "cozy", "easy"],
  ["food-easy-tea", "tea", "calm", "easy"],
  ["food-easy-green-tea", "green tea", "zen", "easy"],
  ["food-easy-iced-tea", "iced tea", "condensation", "easy"],
  ["food-easy-hot-chocolate", "hot chocolate", "cozy", "easy"],
  ["food-easy-chocolate-milk", "chocolate milk", "nostalgia", "easy"],
  ["food-easy-sports-drink", "sports drink", "sweat", "easy"],
  ["food-easy-energy-drink", "energy drink", "jitters", "easy"],
  ["food-easy-beer", "beer", "hangover", "easy"],
  ["food-easy-wine", "wine", "aging", "easy"],
  ["food-easy-champagne", "champagne", "toast", "easy"],
  ["food-easy-cocktail", "cocktail", "shaker", "easy"],
  ["food-easy-whiskey", "whiskey", "burn", "easy"],
  ["food-easy-vodka", "vodka", "burn", "easy"],
  ["food-easy-rum", "rum", "pirate", "easy"],
  ["food-easy-tequila", "tequila", "regret", "easy"],
  ["food-easy-gin", "gin", "botanical", "easy"],
  ["food-easy-vinegar", "vinegar", "sting", "easy"],
  ["food-easy-ketchup", "ketchup", "smear", "easy"],
  ["food-easy-mustard", "mustard", "zip", "easy"],
  ["food-easy-mayonnaise", "mayonnaise", "spread", "easy"],
  ["food-easy-soy-sauce", "soy sauce", "salty", "easy"],
  ["food-easy-ranch", "ranch", "dipping", "easy"],
  ["food-easy-syrup", "syrup", "drizzle", "easy"],
  ["food-easy-jam", "jam", "spread", "easy"],
  ["food-easy-jelly", "jelly", "wobble", "easy"],
  ["food-easy-peanut-butter", "peanut butter", "sticky", "easy"],
  ["food-easy-olive-oil", "olive oil", "slick", "easy"],
  ["food-easy-broth", "broth", "simmer", "easy"],
  ["food-easy-baking-soda", "baking soda", "fizz", "easy"],
  ["food-easy-brown-sugar", "brown sugar", "clumps", "easy"],
  ["food-easy-breadcrumbs", "breadcrumbs", "coating", "easy"],
  ["food-easy-maple-syrup", "maple syrup", "drizzle", "easy"],
  ["food-easy-frozen-yogurt", "frozen yogurt", "tangy", "easy"],
  ["food-easy-soft-serve", "soft serve", "swirl", "easy"],
  ["food-easy-sundae", "sundae", "splurge", "easy"],
  ["food-easy-ice-pop", "ice pop", "drip", "easy"],
  ["food-easy-instant-noodles", "instant noodles", "broke", "easy"],
  ["food-easy-cup-noodles", "cup noodles", "dorm", "easy"],
  ["food-easy-frozen-pizza", "frozen pizza", "lazy", "easy"],
  ["food-easy-lunchbox", "lunchbox", "packed", "easy"],
  ["food-medium-cantaloupe", "cantaloupe", "netted", "medium"],
  ["food-medium-papaya", "papaya", "buttery", "medium"],
  ["food-medium-date", "date", "wrinkle", "medium"],
  ["food-medium-tangerine", "tangerine", "peeling", "medium"],
  ["food-medium-grapefruit", "grapefruit", "bitterness", "medium"],
  ["food-medium-cranberry", "cranberry", "tart", "medium"],
  ["food-medium-kale", "kale", "virtue", "medium"],
  ["food-medium-zucchini", "zucchini", "spiral", "medium"],
  ["food-medium-radish", "radish", "peppery", "medium"],
  ["food-medium-beet", "beet", "stain", "medium"],
  ["food-medium-turnip", "turnip", "earthy", "medium"],
  ["food-medium-asparagus", "asparagus", "odor", "medium"],
  ["food-medium-squash", "squash", "roasting", "medium"],
  ["food-medium-yam", "yam", "sweetness", "medium"],
  ["food-medium-jalapeno", "jalapeno", "sweat", "medium"],
  ["food-medium-basil", "basil", "aroma", "medium"],
  ["food-medium-parsley", "parsley", "garnish", "medium"],
  ["food-medium-cilantro", "cilantro", "soap", "medium"],
  ["food-medium-oregano", "oregano", "aroma", "medium"],
  ["food-medium-nutmeg", "nutmeg", "warmth", "medium"],
  ["food-medium-maple", "maple", "amber", "medium"],
  ["food-medium-croissant", "croissant", "flaky", "medium"],
  ["food-medium-scone", "scone", "crumbly", "medium"],
  ["food-medium-crepe", "crepe", "thin", "medium"],
  ["food-medium-pita", "pita", "pocket", "medium"],
  ["food-medium-naan", "naan", "pillowy", "medium"],
  ["food-medium-sourdough", "sourdough", "tang", "medium"],
  ["food-medium-baguette", "baguette", "crusty", "medium"],
  ["food-medium-cornbread", "cornbread", "crumbly", "medium"],
  ["food-medium-quinoa", "quinoa", "pretentious", "medium"],
  ["food-medium-couscous", "couscous", "fluffy", "medium"],
  ["food-medium-lentil", "lentil", "hearty", "medium"],
  ["food-medium-chickpea", "chickpea", "roasted", "medium"],
  ["food-medium-cashew", "cashew", "creamy", "medium"],
  ["food-medium-pistachio", "pistachio", "shelling", "medium"],
  ["food-medium-pecan", "pecan", "sticky", "medium"],
  ["food-medium-hazelnut", "hazelnut", "toasty", "medium"],
  ["food-medium-sunflower", "sunflower", "sunny", "medium"],
  ["food-medium-sesame", "sesame", "sprinkle", "medium"],
  ["food-medium-cottage-cheese", "cottage cheese", "lumpy", "medium"],
  ["food-medium-mozzarella", "mozzarella", "stretch", "medium"],
  ["food-medium-feta", "feta", "crumbly", "medium"],
  ["food-medium-blue-cheese", "blue cheese", "stinky", "medium"],
  ["food-medium-goat-cheese", "goat cheese", "tangy", "medium"],
  ["food-medium-gelato", "gelato", "silky", "medium"],
  ["food-medium-sorbet", "sorbet", "icy", "medium"],
  ["food-medium-custard", "custard", "silky", "medium"],
  ["food-medium-cod", "cod", "flaky", "medium"],
  ["food-medium-trout", "trout", "stream", "medium"],
  ["food-medium-sardine", "sardine", "tin", "medium"],
  ["food-medium-oyster", "oyster", "pearl", "medium"],
  ["food-medium-clam", "clam", "digging", "medium"],
  ["food-medium-squid", "squid", "ink", "medium"],
  ["food-medium-octopus", "octopus", "escape", "medium"],
  ["food-medium-brisket", "brisket", "smoke", "medium"],
  ["food-medium-meatloaf", "meatloaf", "slice", "medium"],
  ["food-medium-quesadilla", "quesadilla", "folding", "medium"],
  ["food-medium-enchilada", "enchilada", "smothered", "medium"],
  ["food-medium-fajita", "fajita", "sizzle", "medium"],
  ["food-medium-tamale", "tamale", "wrapped", "medium"],
  ["food-medium-falafel", "falafel", "crispy", "medium"],
  ["food-medium-kebab", "kebab", "skewer", "medium"],
  ["food-medium-pho", "pho", "steam", "medium"],
  ["food-medium-wonton", "wonton", "pinch", "medium"],
  ["food-medium-spring-roll", "spring roll", "freshness", "medium"],
  ["food-medium-egg-roll", "egg roll", "crackle", "medium"],
  ["food-medium-pad-thai", "pad thai", "tangle", "medium"],
  ["food-medium-samosa", "samosa", "spiced", "medium"],
  ["food-medium-kimchi", "kimchi", "fermented", "medium"],
  ["food-medium-tempura", "tempura", "lightness", "medium"],
  ["food-medium-teriyaki", "teriyaki", "glossy", "medium"],
  ["food-medium-chowder", "chowder", "thick", "medium"],
  ["food-medium-gumbo", "gumbo", "bayou", "medium"],
  ["food-medium-coleslaw", "coleslaw", "shredded", "medium"],
  ["food-medium-scramble", "scramble", "messy", "medium"],
  ["food-medium-quiche", "quiche", "custardy", "medium"],
  ["food-medium-jerky", "jerky", "tough", "medium"],
  ["food-medium-shortbread", "shortbread", "crumbly", "medium"],
  ["food-medium-churro", "churro", "ridged", "medium"],
  ["food-medium-toffee", "toffee", "crack", "medium"],
  ["food-medium-taffy", "taffy", "stretch", "medium"],
  ["food-medium-licorice", "licorice", "twist", "medium"],
  ["food-medium-limeade", "limeade", "pucker", "medium"],
  ["food-medium-frappuccino", "frappuccino", "overpriced", "medium"],
  ["food-medium-chai", "chai", "spice", "medium"],
  ["food-medium-matcha", "matcha", "whisk", "medium"],
  ["food-medium-bubble-tea", "bubble tea", "chewy", "medium"],
  ["food-medium-coconut-water", "coconut water", "electrolytes", "medium"],
  ["food-medium-lager", "lager", "crisp", "medium"],
  ["food-medium-ale", "ale", "malty", "medium"],
  ["food-medium-sangria", "sangria", "fruity", "medium"],
  ["food-medium-martini", "martini", "sleek", "medium"],
  ["food-medium-margarita", "margarita", "rim", "medium"],
  ["food-medium-mojito", "mojito", "muddled", "medium"],
  ["food-medium-pesto", "pesto", "herby", "medium"],
  ["food-medium-marinara", "marinara", "simmer", "medium"],
  ["food-medium-alfredo", "alfredo", "richness", "medium"],
  ["food-medium-sriracha", "sriracha", "squeeze", "medium"],
  ["food-medium-wasabi", "wasabi", "sting", "medium"],
  ["food-medium-relish", "relish", "chunky", "medium"],
  ["food-medium-dressing", "dressing", "tossing", "medium"],
  ["food-medium-stock", "stock", "simmer", "medium"],
  ["food-medium-cornstarch", "cornstarch", "thickening", "medium"],
  ["food-medium-cornflakes", "cornflakes", "snap", "medium"],
  ["food-medium-seaweed", "seaweed", "briny", "medium"],
  ["food-medium-gelatin", "gelatin", "jiggle", "medium"],
  ["food-medium-buttermilk", "buttermilk", "tang", "medium"],
  ["food-medium-banana-split", "banana split", "splurge", "medium"],
  ["food-medium-waffle-cone", "waffle cone", "crisp", "medium"],
  ["food-hard-pomegranate", "pomegranate", "burst", "hard"],
  ["food-hard-honeydew", "honeydew", "pale", "hard"],
  ["food-hard-guava", "guava", "fragrant", "hard"],
  ["food-hard-fig", "fig", "ancient", "hard"],
  ["food-hard-apricot", "apricot", "velvet", "hard"],
  ["food-hard-nectarine", "nectarine", "smooth", "hard"],
  ["food-hard-passionfruit", "passionfruit", "wrinkled", "hard"],
  ["food-hard-dragonfruit", "dragonfruit", "scales", "hard"],
  ["food-hard-lychee", "lychee", "peeling", "hard"],
  ["food-hard-artichoke", "artichoke", "patience", "hard"],
  ["food-hard-leek", "leek", "mildness", "hard"],
  ["food-hard-okra", "okra", "slimy", "hard"],
  ["food-hard-turmeric", "turmeric", "staining", "hard"],
  ["food-hard-rosemary", "rosemary", "piney", "hard"],
  ["food-hard-thyme", "thyme", "earthy", "hard"],
  ["food-hard-sage", "sage", "wisdom", "hard"],
  ["food-hard-dill", "dill", "feathery", "hard"],
  ["food-hard-peppercorn", "peppercorn", "grinding", "hard"],
  ["food-hard-molasses", "molasses", "slow", "hard"],
  ["food-hard-brioche", "brioche", "buttery", "hard"],
  ["food-hard-cornmeal", "cornmeal", "gritty", "hard"],
  ["food-hard-barley", "barley", "chewy", "hard"],
  ["food-hard-bulgur", "bulgur", "nutty", "hard"],
  ["food-hard-macadamia", "macadamia", "buttery", "hard"],
  ["food-hard-chia", "chia", "swelling", "hard"],
  ["food-hard-flaxseed", "flaxseed", "fiber", "hard"],
  ["food-hard-ricotta", "ricotta", "softness", "hard"],
  ["food-hard-brie", "brie", "ooze", "hard"],
  ["food-hard-gouda", "gouda", "smoky", "hard"],
  ["food-hard-mussel", "mussel", "clinging", "hard"],
  ["food-hard-scallop", "scallop", "searing", "hard"],
  ["food-hard-shawarma", "shawarma", "spinning", "hard"],
  ["food-hard-gyro", "gyro", "spinning", "hard"],
  ["food-hard-calzone", "calzone", "folded", "hard"],
  ["food-hard-tortellini", "tortellini", "navel", "hard"],
  ["food-hard-gnocchi", "gnocchi", "pillows", "hard"],
  ["food-hard-risotto", "risotto", "stirring", "hard"],
  ["food-hard-paella", "paella", "saffron", "hard"],
  ["food-hard-sashimi", "sashimi", "delicate", "hard"],
  ["food-hard-udon", "udon", "thick", "hard"],
  ["food-hard-soba", "soba", "nutty", "hard"],
  ["food-hard-biryani", "biryani", "fragrant", "hard"],
  ["food-hard-tikka", "tikka", "char", "hard"],
  ["food-hard-dal", "dal", "comfort", "hard"],
  ["food-hard-miso", "miso", "umami", "hard"],
  ["food-hard-bibimbap", "bibimbap", "mixed", "hard"],
  ["food-hard-satay", "satay", "skewer", "hard"],
  ["food-hard-jambalaya", "jambalaya", "spicy", "hard"],
  ["food-hard-gazpacho", "gazpacho", "chilled", "hard"],
  ["food-hard-borscht", "borscht", "redness", "hard"],
  ["food-hard-minestrone", "minestrone", "hearty", "hard"],
  ["food-hard-miso-soup", "miso soup", "umami", "hard"],
  ["food-hard-caprese", "caprese", "freshness", "hard"],
  ["food-hard-bruschetta", "bruschetta", "toasty", "hard"],
  ["food-hard-frittata", "frittata", "baked", "hard"],
  ["food-hard-macaron", "macaron", "delicate", "hard"],
  ["food-hard-eclair", "eclair", "filled", "hard"],
  ["food-hard-cannoli", "cannoli", "crispy", "hard"],
  ["food-hard-baklava", "baklava", "layers", "hard"],
  ["food-hard-truffle", "truffle", "luxury", "hard"],
  ["food-hard-americano", "americano", "watered", "hard"],
  ["food-hard-macchiato", "macchiato", "stained", "hard"],
  ["food-hard-kombucha", "kombucha", "fermented", "hard"],
  ["food-hard-stout", "stout", "darkness", "hard"],
  ["food-hard-sake", "sake", "ceremony", "hard"],
  ["food-hard-marmalade", "marmalade", "bitterness", "hard"],
  ["food-hard-horseradish", "horseradish", "sting", "hard"],
  ["food-hard-aioli", "aioli", "creamy", "hard"],
  ["food-hard-balsamic", "balsamic", "acid", "hard"],
  ["food-hard-vinaigrette", "vinaigrette", "acid", "hard"],
  ["food-hard-bouillon", "bouillon", "concentrated", "hard"],
  ["food-hard-edamame", "edamame", "popping", "hard"],
  ["food-hard-mochi", "mochi", "chewy", "hard"],
] as const;
