export const languageCatalog = [
  ["afrikaans", "Afrikaans", "Afrikaans"],
  ["albanian", "Albanian", "Shqip"],
  ["amharic", "Amharic", "አማርኛ"],
  ["arabic", "Arabic", "العربية"],
  ["armenian", "Armenian", "Հայերեն"],
  ["assamese", "Assamese", "অসমীয়া"],
  ["aymara", "Aymara", "Aymar aru"],
  ["azerbaijani", "Azerbaijani", "Azərbaycanca"],
  ["bambara", "Bambara", "Bamanankan"],
  ["basque", "Basque", "Euskara"],
  ["belarusian", "Belarusian", "Беларуская"],
  ["bengali", "Bengali", "বাংলা"],
  ["bhojpuri", "Bhojpuri", "भोजपुरी"],
  ["bosnian", "Bosnian", "Bosanski"],
  ["bulgarian", "Bulgarian", "Български"],
  ["burmese", "Burmese", "မြန်မာစာ"],
  ["catalan", "Catalan", "Català"],
  ["cebuano", "Cebuano", "Cebuano"],
  ["chinese-simplified", "Chinese (Simplified)", "简体中文"],
  ["chinese-traditional", "Chinese (Traditional)", "繁體中文"],
  ["corsican", "Corsican", "Corsu"],
  ["croatian", "Croatian", "Hrvatski"],
  ["czech", "Czech", "Čeština"],
  ["danish", "Danish", "Dansk"],
  ["dhivehi", "Dhivehi", "ދިވެހި"],
  ["dogri", "Dogri", "डोगरी"],
  ["dutch", "Dutch", "Nederlands"],
  ["english", "English", "English"],
  ["esperanto", "Esperanto", "Esperanto"],
  ["estonian", "Estonian", "Eesti"],
  ["ewe", "Ewe", "Eʋegbe"],
  ["filipino", "Filipino", "Filipino"],
  ["finnish", "Finnish", "Suomi"],
  ["french", "French", "Français"],
  ["frisian", "Frisian", "Frysk"],
  ["galician", "Galician", "Galego"],
  ["georgian", "Georgian", "ქართული"],
  ["german", "German", "Deutsch"],
  ["greek", "Greek", "Ελληνικά"],
  ["guarani", "Guarani", "Avañeʼẽ"],
  ["gujarati", "Gujarati", "ગુજરાતી"],
  ["haitian-creole", "Haitian Creole", "Kreyòl ayisyen"],
  ["hausa", "Hausa", "Hausa"],
  ["hawaiian", "Hawaiian", "ʻŌlelo Hawaiʻi"],
  ["hebrew", "Hebrew", "עברית"],
  ["hindi", "Hindi", "हिन्दी"],
  ["hmong", "Hmong", "Hmoob"],
  ["hungarian", "Hungarian", "Magyar"],
  ["icelandic", "Icelandic", "Íslenska"],
  ["igbo", "Igbo", "Igbo"],
  ["ilocano", "Ilocano", "Ilokano"],
  ["indonesian", "Indonesian", "Bahasa Indonesia"],
  ["irish", "Irish", "Gaeilge"],
  ["italian", "Italian", "Italiano"],
  ["japanese", "Japanese", "日本語"],
  ["javanese", "Javanese", "Basa Jawa"],
  ["kannada", "Kannada", "ಕನ್ನಡ"],
  ["kazakh", "Kazakh", "Қазақша"],
  ["khmer", "Khmer", "ភាសាខ្មែរ"],
  ["kinyarwanda", "Kinyarwanda", "Ikinyarwanda"],
  ["konkani", "Konkani", "कोंकणी"],
  ["korean", "Korean", "한국어"],
  ["krio", "Krio", "Krio"],
  ["kurdish-kurmanji", "Kurdish (Kurmanji)", "Kurmancî"],
  ["kurdish-sorani", "Kurdish (Sorani)", "کوردیی ناوەندی"],
  ["kyrgyz", "Kyrgyz", "Кыргызча"],
  ["lao", "Lao", "ລາວ"],
  ["latin", "Latin", "Latina"],
  ["latvian", "Latvian", "Latviešu"],
  ["lingala", "Lingala", "Lingála"],
  ["lithuanian", "Lithuanian", "Lietuvių"],
  ["luganda", "Luganda", "Luganda"],
  ["luxembourgish", "Luxembourgish", "Lëtzebuergesch"],
  ["macedonian", "Macedonian", "Македонски"],
  ["maithili", "Maithili", "मैथिली"],
  ["malagasy", "Malagasy", "Malagasy"],
  ["malay", "Malay", "Bahasa Melayu"],
  ["malayalam", "Malayalam", "മലയാളം"],
  ["maltese", "Maltese", "Malti"],
  ["maori", "Maori", "Māori"],
  ["marathi", "Marathi", "मराठी"],
  ["meiteilon", "Meiteilon (Manipuri)", "ꯃꯤꯇꯩꯂꯣꯟ"],
  ["mizo", "Mizo", "Mizo ṭawng"],
  ["mongolian", "Mongolian", "Монгол"],
  ["nepali", "Nepali", "नेपाली"],
  ["norwegian", "Norwegian", "Norsk"],
  ["nyanja", "Nyanja", "Chichewa"],
  ["odia", "Odia", "ଓଡ଼ିଆ"],
  ["oromo", "Oromo", "Afaan Oromoo"],
  ["pashto", "Pashto", "پښتو"],
  ["persian", "Persian", "فارسی"],
  ["polish", "Polish", "Polski"],
  ["portuguese", "Portuguese", "Português"],
  ["punjabi", "Punjabi", "ਪੰਜਾਬੀ"],
  ["quechua", "Quechua", "Runasimi"],
  ["romanian", "Romanian", "Română"],
  ["russian", "Russian", "Русский"],
  ["samoan", "Samoan", "Gagana Samoa"],
  ["sanskrit", "Sanskrit", "संस्कृतम्"],
  ["scots-gaelic", "Scots Gaelic", "Gàidhlig"],
  ["sepedi", "Sepedi", "Sepedi"],
  ["serbian", "Serbian", "Српски"],
  ["sesotho", "Sesotho", "Sesotho"],
  ["shona", "Shona", "ChiShona"],
  ["sindhi", "Sindhi", "سنڌي"],
  ["sinhala", "Sinhala", "සිංහල"],
  ["slovak", "Slovak", "Slovenčina"],
  ["slovenian", "Slovenian", "Slovenščina"],
  ["somali", "Somali", "Soomaali"],
  ["spanish", "Spanish", "Español"],
  ["sundanese", "Sundanese", "Basa Sunda"],
  ["swahili", "Swahili", "Kiswahili"],
  ["swedish", "Swedish", "Svenska"],
  ["tajik", "Tajik", "Тоҷикӣ"],
  ["tamil", "Tamil", "தமிழ்"],
  ["tatar", "Tatar", "Татарча"],
  ["telugu", "Telugu", "తెలుగు"],
  ["thai", "Thai", "ไทย"],
  ["tigrinya", "Tigrinya", "ትግርኛ"],
  ["tsonga", "Tsonga", "Xitsonga"],
  ["turkish", "Turkish", "Türkçe"],
  ["turkmen", "Turkmen", "Türkmençe"],
  ["twi", "Twi", "Twi"],
  ["ukrainian", "Ukrainian", "Українська"],
  ["urdu", "Urdu", "اردو"],
  ["uyghur", "Uyghur", "ئۇيغۇرچە"],
  ["uzbek", "Uzbek", "Oʻzbekcha"],
  ["vietnamese", "Vietnamese", "Tiếng Việt"],
  ["welsh", "Welsh", "Cymraeg"],
  ["xhosa", "Xhosa", "isiXhosa"],
  ["yiddish", "Yiddish", "ייִדיש"],
  ["yoruba", "Yoruba", "Yorùbá"],
  ["zulu", "Zulu", "isiZulu"],
] as const;
