export const objectsCatalog = [
  ["objects-easy-chair", "chair", "posture", "easy"],
  ["objects-easy-table", "table", "elbows", "easy"],
  ["objects-easy-desk", "desk", "deadline", "easy"],
  ["objects-easy-couch", "couch", "slouch", "easy"],
  ["objects-easy-sofa", "sofa", "lounging", "easy"],
  ["objects-easy-bed", "bed", "dreams", "easy"],
  ["objects-easy-mattress", "mattress", "sinking", "easy"],
  ["objects-easy-pillow", "pillow", "drool", "easy"],
  ["objects-easy-blanket", "blanket", "cocoon", "easy"],
  ["objects-easy-sheet", "sheet", "wrinkles", "easy"],
  ["objects-easy-dresser", "dresser", "folding", "easy"],
  ["objects-easy-wardrobe", "wardrobe", "choices", "easy"],
  ["objects-easy-closet", "closet", "skeletons", "easy"],
  ["objects-easy-hanger", "hanger", "creases", "easy"],
  ["objects-easy-drawer", "drawer", "junk", "easy"],
  ["objects-easy-cabinet", "cabinet", "hiding", "easy"],
  ["objects-easy-shelf", "shelf", "balancing", "easy"],
  ["objects-easy-bookshelf", "bookshelf", "dust", "easy"],
  ["objects-easy-stool", "stool", "reach", "easy"],
  ["objects-easy-bench", "bench", "waiting", "easy"],
  ["objects-easy-lamp", "lamp", "moths", "easy"],
  ["objects-easy-lantern", "lantern", "wandering", "easy"],
  ["objects-easy-candle", "candle", "flicker", "easy"],
  ["objects-easy-flashlight", "flashlight", "darkness", "easy"],
  ["objects-easy-mirror", "mirror", "vanity", "easy"],
  ["objects-easy-rug", "rug", "tripping", "easy"],
  ["objects-easy-carpet", "carpet", "footprints", "easy"],
  ["objects-easy-mat", "mat", "muddy", "easy"],
  ["objects-easy-curtain", "curtain", "privacy", "easy"],
  ["objects-easy-blinds", "blinds", "squinting", "easy"],
  ["objects-easy-clock", "clock", "deadline", "easy"],
  ["objects-easy-alarm-clock", "alarm clock", "snooze", "easy"],
  ["objects-easy-calendar", "calendar", "countdown", "easy"],
  ["objects-easy-picture-frame", "picture frame", "memory", "easy"],
  ["objects-easy-poster", "poster", "teenager", "easy"],
  ["objects-easy-painting", "painting", "admiration", "easy"],
  ["objects-easy-vase", "vase", "wilting", "easy"],
  ["objects-easy-statue", "statue", "pigeon", "easy"],
  ["objects-easy-basket", "basket", "errands", "easy"],
  ["objects-easy-box", "box", "surprise", "easy"],
  ["objects-easy-crate", "crate", "shipping", "easy"],
  ["objects-easy-bin", "bin", "overflow", "easy"],
  ["objects-easy-trunk", "trunk", "secrets", "easy"],
  ["objects-easy-chest", "chest", "treasure", "easy"],
  ["objects-easy-safe", "safe", "paranoia", "easy"],
  ["objects-easy-door", "door", "knocking", "easy"],
  ["objects-easy-doorknob", "doorknob", "turning", "easy"],
  ["objects-easy-handle", "handle", "grip", "easy"],
  ["objects-easy-window", "window", "daydream", "easy"],
  ["objects-easy-screen", "screen", "smudges", "easy"],
  ["objects-easy-keychain", "keychain", "jingle", "easy"],
  ["objects-easy-keys", "keys", "panic", "easy"],
  ["objects-easy-lock", "lock", "secrecy", "easy"],
  ["objects-easy-switch", "switch", "darkness", "easy"],
  ["objects-easy-outlet", "outlet", "spark", "easy"],
  ["objects-easy-plug", "plug", "charging", "easy"],
  ["objects-easy-wire", "wire", "confusion", "easy"],
  ["objects-easy-cord", "cord", "tripping", "easy"],
  ["objects-easy-cable", "cable", "knots", "easy"],
  ["objects-easy-battery", "battery", "drain", "easy"],
  ["objects-easy-charger", "charger", "rescue", "easy"],
  ["objects-easy-fan", "fan", "breeze", "easy"],
  ["objects-easy-heater", "heater", "thawing", "easy"],
  ["objects-easy-air-conditioner", "air conditioner", "relief", "easy"],
  ["objects-easy-fireplace", "fireplace", "cozy", "easy"],
  ["objects-easy-remote", "remote", "arguing", "easy"],
  ["objects-easy-doorbell", "doorbell", "delivery", "easy"],
  ["objects-easy-mailbox", "mailbox", "anticipation", "easy"],
  ["objects-easy-package", "package", "tracking", "easy"],
  ["objects-easy-envelope", "envelope", "confession", "easy"],
  ["objects-easy-stamp", "stamp", "licking", "easy"],
  ["objects-easy-label", "label", "identity", "easy"],
  ["objects-easy-sticker", "sticker", "peeling", "easy"],
  ["objects-easy-magnet", "magnet", "attraction", "easy"],
  ["objects-easy-hook", "hook", "hanging", "easy"],
  ["objects-easy-rack", "rack", "organizing", "easy"],
  ["objects-easy-stand", "stand", "support", "easy"],
  ["objects-easy-ladder", "ladder", "climbing", "easy"],
  ["objects-easy-trash-can", "trash can", "stink", "easy"],
  ["objects-easy-bucket", "bucket", "sloshing", "easy"],
  ["objects-easy-plate", "plate", "clatter", "easy"],
  ["objects-easy-bowl", "bowl", "slurping", "easy"],
  ["objects-easy-cup", "cup", "sip", "easy"],
  ["objects-easy-mug", "mug", "warmth", "easy"],
  ["objects-easy-glass", "glass", "shatter", "easy"],
  ["objects-easy-spoon", "spoon", "scooping", "easy"],
  ["objects-easy-fork", "fork", "stabbing", "easy"],
  ["objects-easy-knife", "knife", "danger", "easy"],
  ["objects-easy-chopsticks", "chopsticks", "precision", "easy"],
  ["objects-easy-straw", "straw", "sipping", "easy"],
  ["objects-easy-napkin", "napkin", "mess", "easy"],
  ["objects-easy-tray", "tray", "balancing", "easy"],
  ["objects-easy-bottle", "bottle", "refill", "easy"],
  ["objects-easy-jar", "jar", "stubborn", "easy"],
  ["objects-easy-can", "can", "crush", "easy"],
  ["objects-easy-container", "container", "mystery", "easy"],
  ["objects-easy-lunchbox", "lunchbox", "recess", "easy"],
  ["objects-easy-pitcher", "pitcher", "pouring", "easy"],
  ["objects-easy-kettle", "kettle", "whistle", "easy"],
  ["objects-easy-teapot", "teapot", "steeping", "easy"],
  ["objects-easy-coffee-maker", "coffee maker", "dripping", "easy"],
  ["objects-easy-blender", "blender", "noise", "easy"],
  ["objects-easy-toaster", "toaster", "pop", "easy"],
  ["objects-easy-microwave", "microwave", "beeping", "easy"],
  ["objects-easy-oven", "oven", "preheat", "easy"],
  ["objects-easy-stove", "stove", "sizzle", "easy"],
  ["objects-easy-refrigerator", "refrigerator", "humming", "easy"],
  ["objects-easy-freezer", "freezer", "frost", "easy"],
  ["objects-easy-dishwasher", "dishwasher", "steam", "easy"],
  ["objects-easy-sink", "sink", "drain", "easy"],
  ["objects-easy-faucet", "faucet", "dripping", "easy"],
  ["objects-easy-pot", "pot", "boiling", "easy"],
  ["objects-easy-pan", "pan", "sizzle", "easy"],
  ["objects-easy-skillet", "skillet", "searing", "easy"],
  ["objects-easy-lid", "lid", "rattling", "easy"],
  ["objects-easy-spatula", "spatula", "flipping", "easy"],
  ["objects-easy-cutting-board", "cutting board", "chopping", "easy"],
  ["objects-easy-timer", "timer", "pressure", "easy"],
  ["objects-easy-apron", "apron", "splatter", "easy"],
  ["objects-easy-can-opener", "can opener", "struggle", "easy"],
  ["objects-easy-bottle-opener", "bottle opener", "cheers", "easy"],
  ["objects-easy-paper-towel", "paper towel", "rescue", "easy"],
  ["objects-easy-foil", "foil", "crinkle", "easy"],
  ["objects-easy-dish-soap", "dish soap", "bubbles", "easy"],
  ["objects-easy-sponge", "sponge", "squeezing", "easy"],
  ["objects-easy-toothbrush", "toothbrush", "dentist", "easy"],
  ["objects-easy-toothpaste", "toothpaste", "foam", "easy"],
  ["objects-easy-floss", "floss", "guilt", "easy"],
  ["objects-easy-mouthwash", "mouthwash", "burn", "easy"],
  ["objects-easy-soap", "soap", "slippery", "easy"],
  ["objects-easy-shampoo", "shampoo", "lather", "easy"],
  ["objects-easy-conditioner", "conditioner", "smoothness", "easy"],
  ["objects-easy-deodorant", "deodorant", "confidence", "easy"],
  ["objects-easy-razor", "razor", "nick", "easy"],
  ["objects-easy-towel", "towel", "soaking", "easy"],
  ["objects-easy-washcloth", "washcloth", "scrubbing", "easy"],
  ["objects-easy-bathrobe", "bathrobe", "lounging", "easy"],
  ["objects-easy-shower-curtain", "shower curtain", "mildew", "easy"],
  ["objects-easy-toilet-paper", "toilet paper", "panic", "easy"],
  ["objects-easy-tissue", "tissue", "sneezing", "easy"],
  ["objects-easy-plunger", "plunger", "disaster", "easy"],
  ["objects-easy-scale", "scale", "judgment", "easy"],
  ["objects-easy-thermometer", "thermometer", "fever", "easy"],
  ["objects-easy-medicine", "medicine", "relief", "easy"],
  ["objects-easy-pill", "pill", "swallow", "easy"],
  ["objects-easy-bandage", "bandage", "bleeding", "easy"],
  ["objects-easy-band-aid", "band aid", "scrape", "easy"],
  ["objects-easy-lotion", "lotion", "softness", "easy"],
  ["objects-easy-sunscreen", "sunscreen", "sunburn", "easy"],
  ["objects-easy-perfume", "perfume", "trail", "easy"],
  ["objects-easy-cologne", "cologne", "overdoing", "easy"],
  ["objects-easy-makeup", "makeup", "confidence", "easy"],
  ["objects-easy-lipstick", "lipstick", "smudge", "easy"],
  ["objects-easy-mascara", "mascara", "tears", "easy"],
  ["objects-easy-eyeliner", "eyeliner", "precision", "easy"],
  ["objects-easy-nail-polish", "nail polish", "patience", "easy"],
  ["objects-easy-comb", "comb", "tangles", "easy"],
  ["objects-easy-hairbrush", "hairbrush", "detangling", "easy"],
  ["objects-easy-hair-dryer", "hair dryer", "noise", "easy"],
  ["objects-easy-hair-tie", "hair tie", "snapping", "easy"],
  ["objects-easy-headband", "headband", "sweat", "easy"],
  ["objects-easy-hand-sanitizer", "hand sanitizer", "burn", "easy"],
  ["objects-easy-face-mask", "face mask", "muffled", "easy"],
  ["objects-easy-eye-drops", "eye drops", "blinking", "easy"],
  ["objects-easy-earplugs", "earplugs", "silence", "easy"],
  ["objects-easy-broom", "broom", "sweeping", "easy"],
  ["objects-easy-mop", "mop", "sloshing", "easy"],
  ["objects-easy-vacuum", "vacuum", "roar", "easy"],
  ["objects-easy-duster", "duster", "sneezing", "easy"],
  ["objects-easy-brush", "brush", "strokes", "easy"],
  ["objects-easy-rag", "rag", "wiping", "easy"],
  ["objects-easy-cloth", "cloth", "polishing", "easy"],
  ["objects-easy-glove", "glove", "gripping", "easy"],
  ["objects-easy-spray-bottle", "spray bottle", "misting", "easy"],
  ["objects-easy-detergent", "detergent", "freshness", "easy"],
  ["objects-easy-bleach", "bleach", "warning", "easy"],
  ["objects-easy-iron", "iron", "wrinkles", "easy"],
  ["objects-easy-washing-machine", "washing machine", "spinning", "easy"],
  ["objects-easy-dryer", "dryer", "lint", "easy"],
  ["objects-easy-needle", "needle", "prick", "easy"],
  ["objects-easy-thread", "thread", "stitching", "easy"],
  ["objects-easy-button", "button", "missing", "easy"],
  ["objects-easy-zipper", "zipper", "stuck", "easy"],
  ["objects-easy-safety-pin", "safety pin", "emergency", "easy"],
  ["objects-easy-tape-measure", "tape measure", "guessing", "easy"],
  ["objects-easy-phone", "phone", "scrolling", "easy"],
  ["objects-easy-smartphone", "smartphone", "doomscrolling", "easy"],
  ["objects-easy-laptop", "laptop", "deadline", "easy"],
  ["objects-easy-computer", "computer", "crashing", "easy"],
  ["objects-easy-tablet", "tablet", "swiping", "easy"],
  ["objects-easy-monitor", "monitor", "eyestrain", "easy"],
  ["objects-easy-keyboard", "keyboard", "clacking", "easy"],
  ["objects-easy-mouse", "mouse", "clicking", "easy"],
  ["objects-easy-speaker", "speaker", "bass", "easy"],
  ["objects-easy-headphones", "headphones", "isolation", "easy"],
  ["objects-easy-earbuds", "earbuds", "tangling", "easy"],
  ["objects-easy-microphone", "microphone", "karaoke", "easy"],
  ["objects-easy-camera", "camera", "posing", "easy"],
  ["objects-easy-webcam", "webcam", "awkward", "easy"],
  ["objects-easy-television", "television", "zoning", "easy"],
  ["objects-easy-radio", "radio", "static", "easy"],
  ["objects-easy-router", "router", "buffering", "easy"],
  ["objects-easy-printer", "printer", "jamming", "easy"],
  ["objects-easy-scanner", "scanner", "copying", "easy"],
  ["objects-easy-projector", "projector", "nerves", "easy"],
  ["objects-easy-game-controller", "game controller", "rage", "easy"],
  ["objects-easy-console", "console", "respawn", "easy"],
  ["objects-easy-calculator", "calculator", "cheating", "easy"],
  ["objects-easy-watch", "watch", "lateness", "easy"],
  ["objects-easy-usb-drive", "usb drive", "forgotten", "easy"],
  ["objects-easy-hard-drive", "hard drive", "crashing", "easy"],
  ["objects-easy-phone-case", "phone case", "cracked", "easy"],
  ["objects-easy-desk-lamp", "desk lamp", "focus", "easy"],
  ["objects-easy-alarm", "alarm", "panic", "easy"],
  ["objects-easy-smoke-detector", "smoke detector", "beeping", "easy"],
  ["objects-easy-security-camera", "security camera", "surveillance", "easy"],
  ["objects-easy-light-bulb", "light bulb", "idea", "easy"],
  ["objects-easy-book", "book", "escape", "easy"],
  ["objects-easy-notebook", "notebook", "scribbles", "easy"],
  ["objects-easy-journal", "journal", "secrets", "easy"],
  ["objects-easy-diary", "diary", "secrets", "easy"],
  ["objects-easy-planner", "planner", "stress", "easy"],
  ["objects-easy-folder", "folder", "paperwork", "easy"],
  ["objects-easy-binder", "binder", "cramming", "easy"],
  ["objects-easy-clipboard", "clipboard", "authority", "easy"],
  ["objects-easy-paper", "paper", "folding", "easy"],
  ["objects-easy-card", "card", "sentiment", "easy"],
  ["objects-easy-sticky-note", "sticky note", "reminder", "easy"],
  ["objects-easy-bookmark", "bookmark", "pause", "easy"],
  ["objects-easy-dictionary", "dictionary", "spelling", "easy"],
  ["objects-easy-map", "map", "lost", "easy"],
  ["objects-easy-pen", "pen", "signature", "easy"],
  ["objects-easy-pencil", "pencil", "scribbling", "easy"],
  ["objects-easy-marker", "marker", "stain", "easy"],
  ["objects-easy-highlighter", "highlighter", "neon", "easy"],
  ["objects-easy-crayon", "crayon", "scribbles", "easy"],
  ["objects-easy-eraser", "eraser", "mistakes", "easy"],
  ["objects-easy-sharpener", "sharpener", "shavings", "easy"],
  ["objects-easy-ruler", "ruler", "straightness", "easy"],
  ["objects-easy-scissors", "scissors", "snipping", "easy"],
  ["objects-easy-stapler", "stapler", "click", "easy"],
  ["objects-easy-paperclip", "paperclip", "bending", "easy"],
  ["objects-easy-rubber-band", "rubber band", "snap", "easy"],
  ["objects-easy-tape", "tape", "repair", "easy"],
  ["objects-easy-glue", "glue", "stickiness", "easy"],
  ["objects-easy-whiteboard", "whiteboard", "brainstorm", "easy"],
  ["objects-easy-chalkboard", "chalkboard", "screech", "easy"],
  ["objects-easy-chalk", "chalk", "dust", "easy"],
  ["objects-easy-mail", "mail", "bills", "easy"],
  ["objects-easy-letter", "letter", "heartfelt", "easy"],
  ["objects-easy-postcard", "postcard", "wanderlust", "easy"],
  ["objects-easy-receipt", "receipt", "regret", "easy"],
  ["objects-easy-coupon", "coupon", "savings", "easy"],
  ["objects-easy-ticket", "ticket", "anticipation", "easy"],
  ["objects-easy-passport", "passport", "border", "easy"],
  ["objects-easy-license", "license", "freedom", "easy"],
  ["objects-easy-id-card", "id card", "verification", "easy"],
  ["objects-easy-credit-card", "credit card", "debt", "easy"],
  ["objects-easy-debit-card", "debit card", "budget", "easy"],
  ["objects-easy-shirt", "shirt", "stain", "easy"],
  ["objects-easy-pants", "pants", "pockets", "easy"],
  ["objects-easy-jeans", "jeans", "fading", "easy"],
  ["objects-easy-shorts", "shorts", "sunburn", "easy"],
  ["objects-easy-dress", "dress", "twirl", "easy"],
  ["objects-easy-skirt", "skirt", "twirl", "easy"],
  ["objects-easy-sweater", "sweater", "cozy", "easy"],
  ["objects-easy-hoodie", "hoodie", "comfort", "easy"],
  ["objects-easy-jacket", "jacket", "pockets", "easy"],
  ["objects-easy-coat", "coat", "shivering", "easy"],
  ["objects-easy-belt", "belt", "tightness", "easy"],
  ["objects-easy-sock", "sock", "missing", "easy"],
  ["objects-easy-shoe", "shoe", "blister", "easy"],
  ["objects-easy-sneaker", "sneaker", "running", "easy"],
  ["objects-easy-boot", "boot", "mud", "easy"],
  ["objects-easy-slipper", "slipper", "lazy", "easy"],
  ["objects-easy-hat", "hat", "shade", "easy"],
  ["objects-easy-cap", "cap", "team", "easy"],
  ["objects-easy-gloves", "gloves", "fingerprints", "easy"],
  ["objects-easy-sunglasses", "sunglasses", "glare", "easy"],
  ["objects-easy-glasses", "glasses", "clarity", "easy"],
  ["objects-easy-ring", "ring", "proposal", "easy"],
  ["objects-easy-wallet", "wallet", "anxiety", "easy"],
  ["objects-easy-purse", "purse", "searching", "easy"],
  ["objects-easy-backpack", "backpack", "burden", "easy"],
  ["objects-easy-suitcase", "suitcase", "packing", "easy"],
  ["objects-easy-umbrella", "umbrella", "drizzle", "easy"],
  ["objects-easy-pajamas", "pajamas", "dreams", "easy"],
  ["objects-easy-toy", "toy", "imagination", "easy"],
  ["objects-easy-doll", "doll", "pretend", "easy"],
  ["objects-easy-teddy-bear", "teddy bear", "comfort", "easy"],
  ["objects-easy-ball", "ball", "bounce", "easy"],
  ["objects-easy-puzzle", "puzzle", "patience", "easy"],
  ["objects-easy-block", "block", "stacking", "easy"],
  ["objects-easy-kite", "kite", "wind", "easy"],
  ["objects-easy-dice", "dice", "chance", "easy"],
  ["objects-easy-board-game", "board game", "arguments", "easy"],
  ["objects-easy-bicycle", "bicycle", "balance", "easy"],
  ["objects-easy-bike", "bike", "pedaling", "easy"],
  ["objects-easy-basketball", "basketball", "height", "easy"],
  ["objects-easy-soccer-ball", "soccer ball", "shin", "easy"],
  ["objects-easy-tent", "tent", "mosquitoes", "easy"],
  ["objects-easy-water-bottle", "water bottle", "hydration", "easy"],
  ["objects-easy-whistle", "whistle", "attention", "easy"],
  ["objects-easy-diaper", "diaper", "stink", "easy"],
  ["objects-easy-stroller", "stroller", "folding", "easy"],
  ["objects-easy-pacifier", "pacifier", "quiet", "easy"],
  ["objects-easy-crib", "crib", "naps", "easy"],
  ["objects-easy-rattle", "rattle", "shaking", "easy"],
  ["objects-easy-leash", "leash", "pulling", "easy"],
  ["objects-easy-collar", "collar", "jingling", "easy"],
  ["objects-easy-hammer", "hammer", "pounding", "easy"],
  ["objects-easy-screwdriver", "screwdriver", "twisting", "easy"],
  ["objects-easy-wrench", "wrench", "tightening", "easy"],
  ["objects-easy-saw", "saw", "sawdust", "easy"],
  ["objects-easy-drill", "drill", "noise", "easy"],
  ["objects-easy-toolbox", "toolbox", "fixing", "easy"],
  ["objects-easy-nail", "nail", "puncture", "easy"],
  ["objects-easy-screw", "screw", "twisting", "easy"],
  ["objects-easy-rope", "rope", "knot", "easy"],
  ["objects-easy-string", "string", "tangle", "easy"],
  ["objects-easy-shovel", "shovel", "digging", "easy"],
  ["objects-easy-rake", "rake", "leaves", "easy"],
  ["objects-easy-grill", "grill", "smoke", "easy"],
  ["objects-easy-lighter", "lighter", "spark", "easy"],
  ["objects-easy-matches", "matches", "sulfur", "easy"],
  ["objects-easy-coin", "coin", "flipping", "easy"],
  ["objects-easy-cash", "cash", "temptation", "easy"],
  ["objects-easy-gift-box", "gift box", "surprise", "easy"],
  ["objects-easy-ribbon", "ribbon", "ceremony", "easy"],
  ["objects-easy-balloon", "balloon", "floating", "easy"],
  ["objects-easy-shopping-cart", "shopping cart", "wobble", "easy"],
  ["objects-easy-cart", "cart", "wobble", "easy"],
  ["objects-easy-bell", "bell", "attention", "easy"],
  ["objects-medium-comforter", "comforter", "cocoon", "medium"],
  ["objects-medium-quilt", "quilt", "patchwork", "medium"],
  ["objects-medium-headboard", "headboard", "bumping", "medium"],
  ["objects-medium-nightstand", "nightstand", "clutter", "medium"],
  ["objects-medium-lampshade", "lampshade", "softening", "medium"],
  ["objects-medium-nightlight", "nightlight", "monsters", "medium"],
  ["objects-medium-doormat", "doormat", "welcome", "medium"],
  ["objects-medium-shade", "shade", "relief", "medium"],
  ["objects-medium-figurine", "figurine", "collecting", "medium"],
  ["objects-medium-flowerpot", "flowerpot", "wilting", "medium"],
  ["objects-medium-padlock", "padlock", "secrecy", "medium"],
  ["objects-medium-extension-cord", "extension cord", "stretching", "medium"],
  ["objects-medium-adapter", "adapter", "compatibility", "medium"],
  ["objects-medium-coaster", "coaster", "rings", "medium"],
  ["objects-medium-step-ladder", "step ladder", "reaching", "medium"],
  ["objects-medium-hamper", "hamper", "overflow", "medium"],
  ["objects-medium-laundry-basket", "laundry basket", "overflow", "medium"],
  ["objects-medium-recycling-bin", "recycling bin", "guilt", "medium"],
  ["objects-medium-tumbler", "tumbler", "clink", "medium"],
  ["objects-medium-placemat", "placemat", "crumbs", "medium"],
  ["objects-medium-tablecloth", "tablecloth", "stains", "medium"],
  ["objects-medium-serving-tray", "serving tray", "balancing", "medium"],
  ["objects-medium-thermos", "thermos", "warmth", "medium"],
  ["objects-medium-cooler", "cooler", "melting", "medium"],
  ["objects-medium-mixer", "mixer", "whirring", "medium"],
  ["objects-medium-garbage-disposal", "garbage disposal", "grinding", "medium"],
  ["objects-medium-saucepan", "saucepan", "simmering", "medium"],
  ["objects-medium-whisk", "whisk", "whipping", "medium"],
  ["objects-medium-tongs", "tongs", "grabbing", "medium"],
  ["objects-medium-peeler", "peeler", "strips", "medium"],
  ["objects-medium-strainer", "strainer", "draining", "medium"],
  ["objects-medium-baking-sheet", "baking sheet", "burnt", "medium"],
  ["objects-medium-cake-pan", "cake pan", "rising", "medium"],
  ["objects-medium-measuring-cup", "measuring cup", "precision", "medium"],
  ["objects-medium-measuring-spoon", "measuring spoon", "exactness", "medium"],
  ["objects-medium-oven-mitt", "oven mitt", "burns", "medium"],
  ["objects-medium-corkscrew", "corkscrew", "twisting", "medium"],
  ["objects-medium-funnel", "funnel", "pouring", "medium"],
  ["objects-medium-pepper-grinder", "pepper grinder", "sneeze", "medium"],
  ["objects-medium-sugar-bowl", "sugar bowl", "grandma", "medium"],
  ["objects-medium-cookie-jar", "cookie jar", "temptation", "medium"],
  ["objects-medium-plastic-wrap", "plastic wrap", "cling", "medium"],
  ["objects-medium-storage-bag", "storage bag", "sealing", "medium"],
  ["objects-medium-scrubber", "scrubber", "scraping", "medium"],
  ["objects-medium-rice-cooker", "rice cooker", "fluffing", "medium"],
  ["objects-medium-slow-cooker", "slow cooker", "patience", "medium"],
  ["objects-medium-air-fryer", "air fryer", "crisping", "medium"],
  ["objects-medium-griddle", "griddle", "sizzle", "medium"],
  ["objects-medium-juicer", "juicer", "squeezing", "medium"],
  ["objects-medium-water-filter", "water filter", "purity", "medium"],
  ["objects-medium-toilet-brush", "toilet brush", "grossness", "medium"],
  ["objects-medium-cotton-swab", "cotton swab", "earwax", "medium"],
  ["objects-medium-cotton-ball", "cotton ball", "softness", "medium"],
  ["objects-medium-tweezers", "tweezers", "plucking", "medium"],
  ["objects-medium-nail-clipper", "nail clipper", "snipping", "medium"],
  ["objects-medium-nail-file", "nail file", "scraping", "medium"],
  ["objects-medium-shaving-cream", "shaving cream", "foam", "medium"],
  ["objects-medium-glasses-case", "glasses case", "scratches", "medium"],
  ["objects-medium-dustpan", "dustpan", "collecting", "medium"],
  ["objects-medium-rubber-glove", "rubber glove", "squeaky", "medium"],
  ["objects-medium-disinfectant", "disinfectant", "germs", "medium"],
  ["objects-medium-laundry-soap", "laundry soap", "stains", "medium"],
  ["objects-medium-sewing-kit", "sewing kit", "repairs", "medium"],
  ["objects-medium-modem", "modem", "buffering", "medium"],
  ["objects-medium-joystick", "joystick", "arcade", "medium"],
  ["objects-medium-smartwatch", "smartwatch", "steps", "medium"],
  ["objects-medium-charger-cable", "charger cable", "tangle", "medium"],
  ["objects-medium-phone-charger", "phone charger", "lifeline", "medium"],
  ["objects-medium-memory-card", "memory card", "backup", "medium"],
  ["objects-medium-screen-protector", "screen protector", "scratch", "medium"],
  ["objects-medium-laptop-case", "laptop case", "padding", "medium"],
  ["objects-medium-mousepad", "mousepad", "sliding", "medium"],
  ["objects-medium-power-bank", "power bank", "rescue", "medium"],
  [
    "objects-medium-electric-toothbrush",
    "electric toothbrush",
    "buzzing",
    "medium",
  ],
  ["objects-medium-electric-razor", "electric razor", "buzzing", "medium"],
  ["objects-medium-index-card", "index card", "memorizing", "medium"],
  ["objects-medium-globe", "globe", "spinning", "medium"],
  ["objects-medium-compass", "compass", "lost", "medium"],
  ["objects-medium-staple", "staple", "piercing", "medium"],
  ["objects-medium-pushpin", "pushpin", "puncture", "medium"],
  ["objects-medium-thumbtack", "thumbtack", "puncture", "medium"],
  ["objects-medium-glue-stick", "glue stick", "stickiness", "medium"],
  ["objects-medium-file-cabinet", "file cabinet", "bureaucracy", "medium"],
  ["objects-medium-desk-chair", "desk chair", "posture", "medium"],
  ["objects-medium-pencil-case", "pencil case", "rummage", "medium"],
  ["objects-medium-pencil-sharpener", "pencil sharpener", "shavings", "medium"],
  ["objects-medium-gift-card", "gift card", "indecision", "medium"],
  ["objects-medium-business-card", "business card", "networking", "medium"],
  ["objects-medium-name-tag", "name tag", "introductions", "medium"],
  ["objects-medium-badge", "badge", "authority", "medium"],
  ["objects-medium-raincoat", "raincoat", "drizzle", "medium"],
  ["objects-medium-suit", "suit", "interview", "medium"],
  ["objects-medium-tie", "tie", "choking", "medium"],
  ["objects-medium-sandal", "sandal", "toes", "medium"],
  ["objects-medium-beanie", "beanie", "cozy", "medium"],
  ["objects-medium-scarf", "scarf", "wrapping", "medium"],
  ["objects-medium-mittens", "mittens", "warmth", "medium"],
  ["objects-medium-reading-glasses", "reading glasses", "squinting", "medium"],
  ["objects-medium-necklace", "necklace", "compliment", "medium"],
  ["objects-medium-bracelet", "bracelet", "jingle", "medium"],
  ["objects-medium-earring", "earring", "piercing", "medium"],
  ["objects-medium-hair-clip", "hair clip", "pinching", "medium"],
  ["objects-medium-handbag", "handbag", "searching", "medium"],
  ["objects-medium-tote-bag", "tote bag", "errands", "medium"],
  ["objects-medium-luggage", "luggage", "overpacking", "medium"],
  ["objects-medium-duffel-bag", "duffel bag", "weekend", "medium"],
  ["objects-medium-fanny-pack", "fanny pack", "tourist", "medium"],
  ["objects-medium-mask", "mask", "disguise", "medium"],
  ["objects-medium-uniform", "uniform", "rules", "medium"],
  ["objects-medium-robe", "robe", "lounging", "medium"],
  ["objects-medium-underwear", "underwear", "embarrassment", "medium"],
  ["objects-medium-swimsuit", "swimsuit", "chlorine", "medium"],
  ["objects-medium-helmet", "helmet", "impact", "medium"],
  ["objects-medium-hard-hat", "hard hat", "hazard", "medium"],
  ["objects-medium-life-jacket", "life jacket", "floating", "medium"],
  ["objects-medium-yoyo", "yoyo", "looping", "medium"],
  ["objects-medium-marble", "marble", "rolling", "medium"],
  ["objects-medium-card-deck", "card deck", "shuffling", "medium"],
  ["objects-medium-jump-rope", "jump rope", "rhythm", "medium"],
  ["objects-medium-skateboard", "skateboard", "balance", "medium"],
  ["objects-medium-scooter", "scooter", "commuting", "medium"],
  ["objects-medium-roller-skates", "roller skates", "wobbling", "medium"],
  ["objects-medium-baseball", "baseball", "catching", "medium"],
  ["objects-medium-tennis-racket", "tennis racket", "swinging", "medium"],
  ["objects-medium-golf-club", "golf club", "swinging", "medium"],
  ["objects-medium-fishing-rod", "fishing rod", "patience", "medium"],
  ["objects-medium-sleeping-bag", "sleeping bag", "cocoon", "medium"],
  ["objects-medium-binoculars", "binoculars", "spy", "medium"],
  ["objects-medium-baby-bottle", "baby bottle", "soothing", "medium"],
  ["objects-medium-high-chair", "high chair", "crumbs", "medium"],
  ["objects-medium-pet-bowl", "pet bowl", "begging", "medium"],
  ["objects-medium-litter-box", "litter box", "odor", "medium"],
  ["objects-medium-dog-bed", "dog bed", "shedding", "medium"],
  ["objects-medium-pliers", "pliers", "gripping", "medium"],
  ["objects-medium-bolt", "bolt", "tightening", "medium"],
  ["objects-medium-nut", "nut", "loosening", "medium"],
  ["objects-medium-level", "level", "crooked", "medium"],
  ["objects-medium-sandpaper", "sandpaper", "smoothing", "medium"],
  ["objects-medium-paintbrush", "paintbrush", "strokes", "medium"],
  ["objects-medium-paint-roller", "paint roller", "strokes", "medium"],
  ["objects-medium-duct-tape", "duct tape", "fixes", "medium"],
  ["objects-medium-masking-tape", "masking tape", "edges", "medium"],
  ["objects-medium-electrical-tape", "electrical tape", "sparks", "medium"],
  ["objects-medium-chain", "chain", "clanking", "medium"],
  ["objects-medium-clamp", "clamp", "pressure", "medium"],
  ["objects-medium-workbench", "workbench", "sawdust", "medium"],
  ["objects-medium-tarp", "tarp", "rain", "medium"],
  ["objects-medium-watering-can", "watering can", "sprinkle", "medium"],
  ["objects-medium-garden-hose", "garden hose", "kink", "medium"],
  ["objects-medium-sprinkler", "sprinkler", "rainbow", "medium"],
  ["objects-medium-lawn-mower", "lawn mower", "noise", "medium"],
  ["objects-medium-wheelbarrow", "wheelbarrow", "hauling", "medium"],
  ["objects-medium-flower-vase", "flower vase", "wilting", "medium"],
  ["objects-medium-bird-feeder", "bird feeder", "chirping", "medium"],
  ["objects-medium-birdhouse", "birdhouse", "nesting", "medium"],
  ["objects-medium-charcoal", "charcoal", "smoke", "medium"],
  [
    "objects-medium-fire-extinguisher",
    "fire extinguisher",
    "emergency",
    "medium",
  ],
  [
    "objects-medium-combination-lock",
    "combination lock",
    "forgetting",
    "medium",
  ],
  ["objects-medium-confetti", "confetti", "mess", "medium"],
  ["objects-medium-hairpin", "hairpin", "lockpick", "medium"],
  ["objects-medium-bobby-pin", "bobby pin", "pinning", "medium"],
  ["objects-medium-magnifying-glass", "magnifying glass", "clues", "medium"],
  ["objects-medium-megaphone", "megaphone", "shouting", "medium"],
  ["objects-medium-snow-globe", "snow globe", "shaking", "medium"],
  ["objects-medium-music-box", "music box", "nostalgia", "medium"],
  ["objects-medium-hourglass", "hourglass", "countdown", "medium"],
  ["objects-medium-wristband", "wristband", "festival", "medium"],
  ["objects-medium-keypad", "keypad", "code", "medium"],
  ["objects-medium-intercom", "intercom", "buzzing", "medium"],
  ["objects-hard-duvet", "duvet", "cocoon", "hard"],
  ["objects-hard-ottoman", "ottoman", "feet", "hard"],
  ["objects-hard-footstool", "footstool", "resting", "hard"],
  ["objects-hard-lockbox", "lockbox", "valuables", "hard"],
  ["objects-hard-hinge", "hinge", "creak", "hard"],
  ["objects-hard-shutter", "shutter", "storm", "hard"],
  ["objects-hard-power-strip", "power strip", "overload", "hard"],
  ["objects-hard-thermostat", "thermostat", "arguments", "hard"],
  ["objects-hard-humidifier", "humidifier", "mist", "hard"],
  ["objects-hard-dehumidifier", "dehumidifier", "dryness", "hard"],
  ["objects-hard-air-purifier", "air purifier", "allergies", "hard"],
  ["objects-hard-radiator", "radiator", "clanking", "hard"],
  ["objects-hard-tripod", "tripod", "stability", "hard"],
  ["objects-hard-flask", "flask", "concealing", "hard"],
  ["objects-hard-wok", "wok", "tossing", "hard"],
  ["objects-hard-ladle", "ladle", "scooping", "hard"],
  ["objects-hard-grater", "grater", "shredding", "hard"],
  ["objects-hard-colander", "colander", "draining", "hard"],
  ["objects-hard-sieve", "sieve", "sifting", "hard"],
  ["objects-hard-rolling-pin", "rolling pin", "flattening", "hard"],
  ["objects-hard-muffin-tin", "muffin tin", "batching", "hard"],
  ["objects-hard-kitchen-scale", "kitchen scale", "accuracy", "hard"],
  ["objects-hard-squeeze-bottle", "squeeze bottle", "drizzle", "hard"],
  ["objects-hard-butter-dish", "butter dish", "softening", "hard"],
  ["objects-hard-breadbox", "breadbox", "freshness", "hard"],
  ["objects-hard-spice-rack", "spice rack", "aromas", "hard"],
  ["objects-hard-wax-paper", "wax paper", "sticking", "hard"],
  ["objects-hard-parchment-paper", "parchment paper", "cookies", "hard"],
  ["objects-hard-pressure-cooker", "pressure cooker", "hissing", "hard"],
  ["objects-hard-food-processor", "food processor", "chopping", "hard"],
  ["objects-hard-loofah", "loofah", "exfoliating", "hard"],
  ["objects-hard-hearing-aid", "hearing aid", "clarity", "hard"],
  ["objects-hard-contact-lens", "contact lens", "blinking", "hard"],
  ["objects-hard-fabric-softener", "fabric softener", "softness", "hard"],
  ["objects-hard-dryer-sheet", "dryer sheet", "static", "hard"],
  ["objects-hard-clothespin", "clothespin", "pinching", "hard"],
  ["objects-hard-ironing-board", "ironing board", "wrinkles", "hard"],
  ["objects-hard-lint-roller", "lint roller", "fur", "hard"],
  ["objects-hard-trackpad", "trackpad", "swiping", "hard"],
  ["objects-hard-sim-card", "sim card", "activation", "hard"],
  ["objects-hard-ring-light", "ring light", "selfie", "hard"],
  ["objects-hard-led-strip", "led strip", "ambience", "hard"],
  ["objects-hard-thesaurus", "thesaurus", "variety", "hard"],
  ["objects-hard-protractor", "protractor", "angles", "hard"],
  ["objects-hard-lanyard", "lanyard", "orientation", "hard"],
  ["objects-hard-brooch", "brooch", "vintage", "hard"],
  ["objects-hard-barrette", "barrette", "pinching", "hard"],
  ["objects-hard-chessboard", "chessboard", "strategy", "hard"],
  ["objects-hard-domino", "domino", "toppling", "hard"],
  ["objects-hard-pet-carrier", "pet carrier", "meowing", "hard"],
  ["objects-hard-cat-tree", "cat tree", "climbing", "hard"],
  ["objects-hard-washer", "washer", "fastening", "hard"],
  ["objects-hard-twine", "twine", "bundling", "hard"],
  ["objects-hard-bungee-cord", "bungee cord", "springing", "hard"],
  ["objects-hard-vise", "vise", "pressure", "hard"],
  ["objects-hard-trowel", "trowel", "planting", "hard"],
  ["objects-hard-bookend", "bookend", "leaning", "hard"],
  ["objects-hard-paperweight", "paperweight", "anchoring", "hard"],
  ["objects-hard-coin-purse", "coin purse", "jingling", "hard"],
  ["objects-hard-nameplate", "nameplate", "ownership", "hard"],
] as const;
