export const placesCatalog = [
  ["places-easy-home", "home", "belonging", "easy"],
  ["places-easy-house", "house", "mortgage", "easy"],
  ["places-easy-apartment", "apartment", "rent", "easy"],
  ["places-easy-room", "room", "privacy", "easy"],
  ["places-easy-bedroom", "bedroom", "dreams", "easy"],
  ["places-easy-bathroom", "bathroom", "urgency", "easy"],
  ["places-easy-kitchen", "kitchen", "chopping", "easy"],
  ["places-easy-basement", "basement", "mildew", "easy"],
  ["places-easy-attic", "attic", "cobwebs", "easy"],
  ["places-easy-garage", "garage", "clutter", "easy"],
  ["places-easy-closet", "closet", "skeletons", "easy"],
  ["places-easy-hallway", "hallway", "echoes", "easy"],
  ["places-easy-elevator", "elevator", "awkwardness", "easy"],
  ["places-easy-stairs", "stairs", "breathless", "easy"],
  ["places-easy-roof", "roof", "shingles", "easy"],
  ["places-easy-balcony", "balcony", "vertigo", "easy"],
  ["places-easy-backyard", "backyard", "sprinklers", "easy"],
  ["places-easy-garden", "garden", "pollination", "easy"],
  ["places-easy-yard", "yard", "mowing", "easy"],
  ["places-easy-entrance", "entrance", "greeting", "easy"],
  ["places-easy-doorway", "doorway", "hesitation", "easy"],
  ["places-easy-floor", "floor", "footsteps", "easy"],
  ["places-easy-classroom", "classroom", "boredom", "easy"],
  ["places-easy-school", "school", "homework", "easy"],
  ["places-easy-college", "college", "debt", "easy"],
  ["places-easy-university", "university", "lectures", "easy"],
  ["places-easy-campus", "campus", "backpacks", "easy"],
  ["places-easy-library", "library", "whispers", "easy"],
  ["places-easy-cafeteria", "cafeteria", "trays", "easy"],
  ["places-easy-playground", "playground", "recess", "easy"],
  ["places-easy-office", "office", "burnout", "easy"],
  ["places-easy-warehouse", "warehouse", "forklifts", "easy"],
  ["places-easy-factory", "factory", "machinery", "easy"],
  ["places-easy-laboratory", "laboratory", "goggles", "easy"],
  ["places-easy-hospital", "hospital", "anxiety", "easy"],
  ["places-easy-clinic", "clinic", "checkup", "easy"],
  ["places-easy-pharmacy", "pharmacy", "refills", "easy"],
  ["places-easy-bank", "bank", "balance", "easy"],
  ["places-easy-prison", "prison", "sentence", "easy"],
  ["places-easy-jail", "jail", "mugshot", "easy"],
  ["places-easy-church", "church", "hymns", "easy"],
  ["places-easy-temple", "temple", "incense", "easy"],
  ["places-easy-cemetery", "cemetery", "mourning", "easy"],
  ["places-easy-restaurant", "restaurant", "tipping", "easy"],
  ["places-easy-cafe", "cafe", "caffeine", "easy"],
  ["places-easy-bakery", "bakery", "aroma", "easy"],
  ["places-easy-supermarket", "supermarket", "aisles", "easy"],
  ["places-easy-market", "market", "bargaining", "easy"],
  ["places-easy-mall", "mall", "escalators", "easy"],
  ["places-easy-shop", "shop", "purchase", "easy"],
  ["places-easy-bookstore", "bookstore", "browsing", "easy"],
  ["places-easy-salon", "salon", "gossip", "easy"],
  ["places-easy-gym", "gym", "sweat", "easy"],
  ["places-easy-stadium", "stadium", "roaring", "easy"],
  ["places-easy-theater", "theater", "applause", "easy"],
  ["places-easy-cinema", "cinema", "trailers", "easy"],
  ["places-easy-museum", "museum", "artifacts", "easy"],
  ["places-easy-zoo", "zoo", "cages", "easy"],
  ["places-easy-aquarium", "aquarium", "glass", "easy"],
  ["places-easy-circus", "circus", "juggling", "easy"],
  ["places-easy-carnival", "carnival", "rides", "easy"],
  ["places-easy-casino", "casino", "losing", "easy"],
  ["places-easy-nightclub", "nightclub", "bass", "easy"],
  ["places-easy-bar", "bar", "stools", "easy"],
  ["places-easy-hotel", "hotel", "checkout", "easy"],
  ["places-easy-motel", "motel", "vacancy", "easy"],
  ["places-easy-hostel", "hostel", "bunkbeds", "easy"],
  ["places-easy-resort", "resort", "wristbands", "easy"],
  ["places-easy-spa", "spa", "relaxation", "easy"],
  ["places-easy-pool", "pool", "chlorine", "easy"],
  ["places-easy-arcade", "arcade", "tokens", "easy"],
  ["places-easy-airport", "airport", "delays", "easy"],
  ["places-easy-runway", "runway", "takeoff", "easy"],
  ["places-easy-subway", "subway", "underground", "easy"],
  ["places-easy-harbor", "harbor", "anchors", "easy"],
  ["places-easy-bridge", "bridge", "crossing", "easy"],
  ["places-easy-tunnel", "tunnel", "claustrophobia", "easy"],
  ["places-easy-highway", "highway", "speeding", "easy"],
  ["places-easy-road", "road", "potholes", "easy"],
  ["places-easy-street", "street", "curb", "easy"],
  ["places-easy-sidewalk", "sidewalk", "cracks", "easy"],
  ["places-easy-border", "border", "passport", "easy"],
  ["places-easy-checkpoint", "checkpoint", "inspection", "easy"],
  ["places-easy-campground", "campground", "mosquitoes", "easy"],
  ["places-easy-campsite", "campsite", "firepit", "easy"],
  ["places-easy-cabin", "cabin", "rustic", "easy"],
  ["places-easy-trail", "trail", "blisters", "easy"],
  ["places-easy-path", "path", "wandering", "easy"],
  ["places-easy-intersection", "intersection", "confusion", "easy"],
  ["places-easy-beach", "beach", "sunscreen", "easy"],
  ["places-easy-shore", "shore", "tide", "easy"],
  ["places-easy-coast", "coast", "erosion", "easy"],
  ["places-easy-island", "island", "isolation", "easy"],
  ["places-easy-mountain", "mountain", "altitude", "easy"],
  ["places-easy-hill", "hill", "incline", "easy"],
  ["places-easy-valley", "valley", "echoes", "easy"],
  ["places-easy-canyon", "canyon", "echo", "easy"],
  ["places-easy-cliff", "cliff", "danger", "easy"],
  ["places-easy-cave", "cave", "darkness", "easy"],
  ["places-easy-desert", "desert", "dehydration", "easy"],
  ["places-easy-oasis", "oasis", "relief", "easy"],
  ["places-easy-forest", "forest", "shade", "easy"],
  ["places-easy-jungle", "jungle", "humidity", "easy"],
  ["places-easy-rainforest", "rainforest", "canopy", "easy"],
  ["places-easy-woods", "woods", "rustling", "easy"],
  ["places-easy-meadow", "meadow", "wildflowers", "easy"],
  ["places-easy-field", "field", "distance", "easy"],
  ["places-easy-swamp", "swamp", "mosquitoes", "easy"],
  ["places-easy-lake", "lake", "ripples", "easy"],
  ["places-easy-pond", "pond", "frogs", "easy"],
  ["places-easy-river", "river", "current", "easy"],
  ["places-easy-stream", "stream", "babbling", "easy"],
  ["places-easy-waterfall", "waterfall", "roar", "easy"],
  ["places-easy-spring", "spring", "bubbling", "easy"],
  ["places-easy-ocean", "ocean", "waves", "easy"],
  ["places-easy-sea", "sea", "salt", "easy"],
  ["places-easy-bay", "bay", "shelter", "easy"],
  ["places-easy-glacier", "glacier", "melting", "easy"],
  ["places-easy-iceberg", "iceberg", "hidden", "easy"],
  ["places-easy-volcano", "volcano", "eruption", "easy"],
  ["places-easy-crater", "crater", "impact", "easy"],
  ["places-easy-reef", "reef", "snorkeling", "easy"],
  ["places-easy-continent", "continent", "massive", "easy"],
  ["places-easy-country", "country", "anthem", "easy"],
  ["places-easy-state", "state", "license", "easy"],
  ["places-easy-city", "city", "skyscrapers", "easy"],
  ["places-easy-town", "town", "gossip", "easy"],
  ["places-easy-village", "village", "cobblestone", "easy"],
  ["places-easy-neighborhood", "neighborhood", "mailboxes", "easy"],
  ["places-easy-suburb", "suburb", "lawns", "easy"],
  ["places-easy-downtown", "downtown", "sirens", "easy"],
  ["places-easy-capital", "capital", "politics", "easy"],
  ["places-easy-map", "map", "orientation", "easy"],
  ["places-easy-globe", "globe", "spinning", "easy"],
  ["places-easy-equator", "equator", "heat", "easy"],
  ["places-easy-north-pole", "north pole", "elves", "easy"],
  ["places-easy-south-pole", "south pole", "penguins", "easy"],
  ["places-easy-arctic", "arctic", "frostbite", "easy"],
  ["places-easy-antarctica", "antarctica", "isolation", "easy"],
  ["places-easy-earth", "earth", "gravity", "easy"],
  ["places-easy-world", "world", "humanity", "easy"],
  ["places-easy-moon", "moon", "tides", "easy"],
  ["places-easy-mars", "mars", "rust", "easy"],
  ["places-easy-planet", "planet", "orbit", "easy"],
  ["places-easy-space", "space", "vacuum", "easy"],
  ["places-easy-galaxy", "galaxy", "stardust", "easy"],
  ["places-easy-universe", "universe", "infinity", "easy"],
  ["places-easy-canada", "canada", "politeness", "easy"],
  ["places-easy-mexico", "mexico", "spice", "easy"],
  ["places-easy-brazil", "brazil", "samba", "easy"],
  ["places-easy-france", "france", "fashion", "easy"],
  ["places-easy-italy", "italy", "espresso", "easy"],
  ["places-easy-spain", "spain", "siesta", "easy"],
  ["places-easy-germany", "germany", "precision", "easy"],
  ["places-easy-england", "england", "umbrella", "easy"],
  ["places-easy-scotland", "scotland", "kilts", "easy"],
  ["places-easy-ireland", "ireland", "luck", "easy"],
  ["places-easy-greece", "greece", "myths", "easy"],
  ["places-easy-turkey", "turkey", "crossroads", "easy"],
  ["places-easy-russia", "russia", "endurance", "easy"],
  ["places-easy-ukraine", "ukraine", "resilience", "easy"],
  ["places-easy-egypt", "egypt", "mummies", "easy"],
  ["places-easy-india", "india", "spices", "easy"],
  ["places-easy-china", "china", "dragons", "easy"],
  ["places-easy-japan", "japan", "discipline", "easy"],
  ["places-easy-south-korea", "south korea", "idols", "easy"],
  ["places-easy-north-korea", "north korea", "secrecy", "easy"],
  ["places-easy-australia", "australia", "kangaroos", "easy"],
  ["places-easy-united-states", "united states", "freedom", "easy"],
  ["places-easy-united-kingdom", "united kingdom", "monarchy", "easy"],
  ["places-easy-africa", "africa", "safari", "easy"],
  ["places-easy-europe", "europe", "passports", "easy"],
  ["places-easy-asia", "asia", "megacities", "easy"],
  ["places-easy-america", "america", "highways", "easy"],
  ["places-easy-new-york", "new york", "hustle", "easy"],
  ["places-easy-los-angeles", "los angeles", "auditions", "easy"],
  ["places-easy-san-francisco", "san francisco", "fog", "easy"],
  ["places-easy-las-vegas", "las vegas", "jackpot", "easy"],
  ["places-easy-miami", "miami", "neon", "easy"],
  ["places-easy-chicago", "chicago", "wind", "easy"],
  ["places-easy-boston", "boston", "accents", "easy"],
  ["places-easy-seattle", "seattle", "drizzle", "easy"],
  ["places-easy-houston", "houston", "rockets", "easy"],
  ["places-easy-dallas", "dallas", "boots", "easy"],
  ["places-easy-atlanta", "atlanta", "peaches", "easy"],
  ["places-easy-orlando", "orlando", "magic", "easy"],
  ["places-easy-detroit", "detroit", "engines", "easy"],
  ["places-easy-philadelphia", "philadelphia", "liberty", "easy"],
  ["places-easy-washington-dc", "washington dc", "lobbying", "easy"],
  ["places-easy-london", "london", "umbrella", "easy"],
  ["places-easy-paris", "paris", "romance", "easy"],
  ["places-easy-rome", "rome", "ruins", "easy"],
  ["places-easy-venice", "venice", "sinking", "easy"],
  ["places-easy-berlin", "berlin", "techno", "easy"],
  ["places-easy-madrid", "madrid", "plazas", "easy"],
  ["places-easy-barcelona", "barcelona", "mosaics", "easy"],
  ["places-easy-athens", "athens", "democracy", "easy"],
  ["places-easy-istanbul", "istanbul", "bazaars", "easy"],
  ["places-easy-moscow", "moscow", "snow", "easy"],
  ["places-easy-dubai", "dubai", "luxury", "easy"],
  ["places-easy-cairo", "cairo", "sand", "easy"],
  ["places-easy-jerusalem", "jerusalem", "pilgrimage", "easy"],
  ["places-easy-mecca", "mecca", "devotion", "easy"],
  ["places-easy-tokyo", "tokyo", "neon", "easy"],
  ["places-easy-beijing", "beijing", "dynasties", "easy"],
  ["places-easy-shanghai", "shanghai", "skyline", "easy"],
  ["places-easy-delhi", "delhi", "spice", "easy"],
  ["places-easy-sydney", "sydney", "opera", "easy"],
  ["places-easy-eiffel-tower", "eiffel tower", "proposal", "easy"],
  ["places-easy-great-wall", "great wall", "fortification", "easy"],
  ["places-easy-taj-mahal", "taj mahal", "devotion", "easy"],
  ["places-easy-colosseum", "colosseum", "gladiators", "easy"],
  ["places-easy-machu-picchu", "machu picchu", "terraces", "easy"],
  ["places-easy-pyramids", "pyramids", "mummies", "easy"],
  ["places-easy-sphinx", "sphinx", "riddle", "easy"],
  ["places-easy-stonehenge", "stonehenge", "mystery", "easy"],
  ["places-easy-big-ben", "big ben", "punctuality", "easy"],
  ["places-easy-buckingham-palace", "buckingham palace", "monarchy", "easy"],
  ["places-easy-white-house", "white house", "presidency", "easy"],
  ["places-easy-capitol", "capitol", "legislation", "easy"],
  ["places-easy-golden-gate", "golden gate", "suspension", "easy"],
  ["places-easy-central-park", "central park", "picnics", "easy"],
  ["places-easy-times-square", "times square", "countdown", "easy"],
  ["places-easy-grand-canyon", "grand canyon", "vertigo", "easy"],
  ["places-easy-niagara-falls", "niagara falls", "mist", "easy"],
  ["places-easy-mount-everest", "mount everest", "summit", "easy"],
  ["places-easy-mount-fuji", "mount fuji", "symmetry", "easy"],
  ["places-easy-burj-khalifa", "burj khalifa", "height", "easy"],
  ["places-easy-louvre", "louvre", "paintings", "easy"],
  ["places-easy-disneyland", "disneyland", "childhood", "easy"],
  ["places-easy-hollywood", "hollywood", "auditions", "easy"],
  ["places-easy-sahara", "sahara", "dehydration", "easy"],
  ["places-easy-amazon", "amazon", "canopy", "easy"],
  ["places-easy-nile", "nile", "fertility", "easy"],
  ["places-easy-alps", "alps", "skiing", "easy"],
  ["places-easy-himalayas", "himalayas", "summits", "easy"],
  ["places-easy-california", "california", "sunshine", "easy"],
  ["places-easy-texas", "texas", "swagger", "easy"],
  ["places-easy-florida", "florida", "chaos", "easy"],
  ["places-easy-alaska", "alaska", "wilderness", "easy"],
  ["places-easy-hawaii", "hawaii", "leis", "easy"],
  ["places-easy-pantry", "pantry", "snacks", "easy"],
  ["places-easy-nursery", "nursery", "lullabies", "easy"],
  ["places-easy-playroom", "playroom", "toys", "easy"],
  ["places-easy-track", "track", "laps", "easy"],
  ["places-easy-laundromat", "laundromat", "quarters", "easy"],
  ["places-easy-treehouse", "treehouse", "childhood", "easy"],
  ["places-easy-farmhouse", "farmhouse", "porch", "easy"],
  ["places-easy-igloo", "igloo", "insulation", "easy"],
  ["places-medium-condo", "condo", "fees", "medium"],
  ["places-medium-staircase", "staircase", "spiraling", "medium"],
  ["places-medium-porch", "porch", "rocking", "medium"],
  ["places-medium-patio", "patio", "grilling", "medium"],
  ["places-medium-driveway", "driveway", "stains", "medium"],
  ["places-medium-lobby", "lobby", "receptionist", "medium"],
  ["places-medium-corridor", "corridor", "echoes", "medium"],
  ["places-medium-cubicle", "cubicle", "fluorescent", "medium"],
  ["places-medium-boardroom", "boardroom", "decisions", "medium"],
  ["places-medium-courthouse", "courthouse", "verdict", "medium"],
  ["places-medium-embassy", "embassy", "visas", "medium"],
  ["places-medium-mosque", "mosque", "prayers", "medium"],
  ["places-medium-synagogue", "synagogue", "candles", "medium"],
  ["places-medium-cathedral", "cathedral", "vaults", "medium"],
  ["places-medium-shrine", "shrine", "offerings", "medium"],
  ["places-medium-monastery", "monastery", "solitude", "medium"],
  ["places-medium-graveyard", "graveyard", "epitaphs", "medium"],
  ["places-medium-diner", "diner", "booths", "medium"],
  ["places-medium-barbershop", "barbershop", "fades", "medium"],
  ["places-medium-arena", "arena", "chanting", "medium"],
  ["places-medium-gallery", "gallery", "frames", "medium"],
  ["places-medium-fairground", "fairground", "ferris", "medium"],
  ["places-medium-pub", "pub", "pints", "medium"],
  ["places-medium-observatory", "observatory", "telescopes", "medium"],
  ["places-medium-planetarium", "planetarium", "constellations", "medium"],
  ["places-medium-terminal", "terminal", "layover", "medium"],
  ["places-medium-port", "port", "cargo", "medium"],
  ["places-medium-pier", "pier", "seagulls", "medium"],
  ["places-medium-marina", "marina", "yachts", "medium"],
  ["places-medium-dock", "dock", "ropes", "medium"],
  ["places-medium-lighthouse", "lighthouse", "warning", "medium"],
  ["places-medium-freeway", "freeway", "merging", "medium"],
  ["places-medium-avenue", "avenue", "storefronts", "medium"],
  ["places-medium-crosswalk", "crosswalk", "beeping", "medium"],
  ["places-medium-roundabout", "roundabout", "circling", "medium"],
  ["places-medium-customs", "customs", "declaration", "medium"],
  ["places-medium-coastline", "coastline", "erosion", "medium"],
  ["places-medium-peninsula", "peninsula", "surrounded", "medium"],
  ["places-medium-mountaintop", "mountaintop", "triumph", "medium"],
  ["places-medium-cavern", "cavern", "stalactites", "medium"],
  ["places-medium-dune", "dune", "shifting", "medium"],
  ["places-medium-woodland", "woodland", "shade", "medium"],
  ["places-medium-grassland", "grassland", "grazing", "medium"],
  ["places-medium-plain", "plain", "horizon", "medium"],
  ["places-medium-prairie", "prairie", "wind", "medium"],
  ["places-medium-savanna", "savanna", "lions", "medium"],
  ["places-medium-marsh", "marsh", "reeds", "medium"],
  ["places-medium-wetland", "wetland", "birds", "medium"],
  ["places-medium-creek", "creek", "trickle", "medium"],
  ["places-medium-gulf", "gulf", "warmth", "medium"],
  ["places-medium-lagoon", "lagoon", "turquoise", "medium"],
  ["places-medium-canal", "canal", "locks", "medium"],
  ["places-medium-geyser", "geyser", "eruption", "medium"],
  ["places-medium-delta", "delta", "branching", "medium"],
  ["places-medium-plateau", "plateau", "flatness", "medium"],
  ["places-medium-basin", "basin", "drainage", "medium"],
  ["places-medium-tundra", "tundra", "permafrost", "medium"],
  ["places-medium-wilderness", "wilderness", "survival", "medium"],
  ["places-medium-countryside", "countryside", "roosters", "medium"],
  ["places-medium-farmland", "farmland", "harvest", "medium"],
  ["places-medium-orchard", "orchard", "ladders", "medium"],
  ["places-medium-vineyard", "vineyard", "corks", "medium"],
  ["places-medium-ranch", "ranch", "saddles", "medium"],
  ["places-medium-farm", "farm", "tractor", "medium"],
  ["places-medium-barn", "barn", "hay", "medium"],
  ["places-medium-pasture", "pasture", "grazing", "medium"],
  ["places-medium-mine", "mine", "darkness", "medium"],
  ["places-medium-nation", "nation", "anthem", "medium"],
  ["places-medium-province", "province", "autonomy", "medium"],
  ["places-medium-metropolis", "metropolis", "density", "medium"],
  ["places-medium-district", "district", "zoning", "medium"],
  ["places-medium-region", "region", "climate", "medium"],
  ["places-medium-territory", "territory", "borders", "medium"],
  ["places-medium-landmark", "landmark", "selfies", "medium"],
  ["places-medium-destination", "destination", "anticipation", "medium"],
  ["places-medium-hemisphere", "hemisphere", "seasons", "medium"],
  ["places-medium-argentina", "argentina", "tango", "medium"],
  ["places-medium-chile", "chile", "earthquakes", "medium"],
  ["places-medium-peru", "peru", "inca", "medium"],
  ["places-medium-colombia", "colombia", "coffee", "medium"],
  ["places-medium-cuba", "cuba", "cigars", "medium"],
  ["places-medium-jamaica", "jamaica", "reggae", "medium"],
  ["places-medium-bahamas", "bahamas", "conch", "medium"],
  ["places-medium-wales", "wales", "dragons", "medium"],
  ["places-medium-poland", "poland", "pierogi", "medium"],
  ["places-medium-portugal", "portugal", "tiles", "medium"],
  ["places-medium-netherlands", "netherlands", "bicycles", "medium"],
  ["places-medium-belgium", "belgium", "waffles", "medium"],
  ["places-medium-switzerland", "switzerland", "neutrality", "medium"],
  ["places-medium-austria", "austria", "waltz", "medium"],
  ["places-medium-sweden", "sweden", "minimalism", "medium"],
  ["places-medium-norway", "norway", "fjords", "medium"],
  ["places-medium-denmark", "denmark", "hygge", "medium"],
  ["places-medium-finland", "finland", "saunas", "medium"],
  ["places-medium-iceland", "iceland", "geysers", "medium"],
  ["places-medium-croatia", "croatia", "limestone", "medium"],
  ["places-medium-romania", "romania", "vampires", "medium"],
  ["places-medium-hungary", "hungary", "paprika", "medium"],
  ["places-medium-czech-republic", "czech republic", "castles", "medium"],
  ["places-medium-morocco", "morocco", "lanterns", "medium"],
  ["places-medium-kenya", "kenya", "runners", "medium"],
  ["places-medium-nigeria", "nigeria", "nollywood", "medium"],
  ["places-medium-ghana", "ghana", "gold", "medium"],
  ["places-medium-ethiopia", "ethiopia", "beans", "medium"],
  ["places-medium-tanzania", "tanzania", "safari", "medium"],
  ["places-medium-south-africa", "south africa", "rainbow", "medium"],
  ["places-medium-madagascar", "madagascar", "lemurs", "medium"],
  ["places-medium-thailand", "thailand", "smiles", "medium"],
  ["places-medium-vietnam", "vietnam", "scooters", "medium"],
  ["places-medium-indonesia", "indonesia", "islands", "medium"],
  ["places-medium-philippines", "philippines", "karaoke", "medium"],
  ["places-medium-malaysia", "malaysia", "towers", "medium"],
  ["places-medium-singapore", "singapore", "cleanliness", "medium"],
  ["places-medium-pakistan", "pakistan", "cricket", "medium"],
  ["places-medium-bangladesh", "bangladesh", "delta", "medium"],
  ["places-medium-nepal", "nepal", "peaks", "medium"],
  ["places-medium-sri-lanka", "sri lanka", "tea", "medium"],
  ["places-medium-saudi-arabia", "saudi arabia", "oil", "medium"],
  ["places-medium-israel", "israel", "pilgrimage", "medium"],
  ["places-medium-iran", "iran", "carpets", "medium"],
  ["places-medium-iraq", "iraq", "ruins", "medium"],
  ["places-medium-qatar", "qatar", "luxury", "medium"],
  ["places-medium-new-zealand", "new zealand", "sheep", "medium"],
  ["places-medium-costa-rica", "costa rica", "sloths", "medium"],
  [
    "places-medium-dominican-republic",
    "dominican republic",
    "merengue",
    "medium",
  ],
  ["places-medium-vatican", "vatican", "pope", "medium"],
  ["places-medium-monaco", "monaco", "racing", "medium"],
  ["places-medium-maldives", "maldives", "overwater", "medium"],
  ["places-medium-greenland", "greenland", "icecaps", "medium"],
  ["places-medium-caribbean", "caribbean", "rum", "medium"],
  ["places-medium-middle-east", "middle east", "deserts", "medium"],
  ["places-medium-latin-america", "latin america", "salsa", "medium"],
  ["places-medium-pacific", "pacific", "vastness", "medium"],
  ["places-medium-atlantic", "atlantic", "crossings", "medium"],
  ["places-medium-mediterranean", "mediterranean", "olives", "medium"],
  ["places-medium-scandinavia", "scandinavia", "minimalism", "medium"],
  ["places-medium-toronto", "toronto", "politeness", "medium"],
  ["places-medium-vancouver", "vancouver", "drizzle", "medium"],
  ["places-medium-montreal", "montreal", "bilingual", "medium"],
  ["places-medium-mexico-city", "mexico city", "murals", "medium"],
  ["places-medium-rio", "rio", "carnival", "medium"],
  ["places-medium-sao-paulo", "sao paulo", "traffic", "medium"],
  ["places-medium-buenos-aires", "buenos aires", "tango", "medium"],
  ["places-medium-santiago", "santiago", "andes", "medium"],
  ["places-medium-lima", "lima", "ceviche", "medium"],
  ["places-medium-bogota", "bogota", "elevation", "medium"],
  ["places-medium-havana", "havana", "cigars", "medium"],
  ["places-medium-kingston", "kingston", "reggae", "medium"],
  ["places-medium-milan", "milan", "fashion", "medium"],
  ["places-medium-florence", "florence", "renaissance", "medium"],
  ["places-medium-munich", "munich", "pretzels", "medium"],
  ["places-medium-lisbon", "lisbon", "tiles", "medium"],
  ["places-medium-amsterdam", "amsterdam", "canals", "medium"],
  ["places-medium-vienna", "vienna", "classical", "medium"],
  ["places-medium-prague", "prague", "castles", "medium"],
  ["places-medium-dublin", "dublin", "pubs", "medium"],
  ["places-medium-edinburgh", "edinburgh", "festival", "medium"],
  ["places-medium-kyiv", "kyiv", "resilience", "medium"],
  ["places-medium-kyoto", "kyoto", "temples", "medium"],
  ["places-medium-hong-kong", "hong kong", "skyscrapers", "medium"],
  ["places-medium-seoul", "seoul", "idols", "medium"],
  ["places-medium-bangkok", "bangkok", "chaos", "medium"],
  ["places-medium-mumbai", "mumbai", "bollywood", "medium"],
  ["places-medium-melbourne", "melbourne", "flatwhite", "medium"],
  ["places-medium-honolulu", "honolulu", "leis", "medium"],
  ["places-medium-phoenix", "phoenix", "heat", "medium"],
  ["places-medium-denver", "denver", "milehigh", "medium"],
  ["places-medium-nashville", "nashville", "guitars", "medium"],
  ["places-medium-new-orleans", "new orleans", "jazz", "medium"],
  ["places-medium-portland", "portland", "weirdness", "medium"],
  ["places-medium-san-diego", "san diego", "beaches", "medium"],
  ["places-medium-manhattan", "manhattan", "taxis", "medium"],
  ["places-medium-brooklyn", "brooklyn", "stoops", "medium"],
  ["places-medium-silicon-valley", "silicon valley", "startups", "medium"],
  ["places-medium-wall-street", "wall street", "greed", "medium"],
  ["places-medium-bali", "bali", "meditation", "medium"],
  ["places-medium-phuket", "phuket", "partying", "medium"],
  ["places-medium-ibiza", "ibiza", "partying", "medium"],
  ["places-medium-santorini", "santorini", "sunsets", "medium"],
  ["places-medium-fiji", "fiji", "lagoons", "medium"],
  ["places-medium-bora-bora", "bora bora", "overwater", "medium"],
  ["places-medium-acropolis", "acropolis", "columns", "medium"],
  ["places-medium-leaning-tower", "leaning tower", "tilt", "medium"],
  ["places-medium-forbidden-city", "forbidden city", "emperors", "medium"],
  ["places-medium-mount-rushmore", "mount rushmore", "faces", "medium"],
  ["places-medium-notre-dame", "notre dame", "gargoyles", "medium"],
  ["places-medium-broadway", "broadway", "musicals", "medium"],
  ["places-medium-dead-sea", "dead sea", "floating", "medium"],
  ["places-medium-black-sea", "black sea", "shipping", "medium"],
  ["places-medium-red-sea", "red sea", "diving", "medium"],
  ["places-medium-galapagos", "galapagos", "evolution", "medium"],
  ["places-medium-yosemite", "yosemite", "granite", "medium"],
  ["places-medium-yellowstone", "yellowstone", "geysers", "medium"],
  ["places-medium-mississippi", "mississippi", "muddy", "medium"],
  ["places-medium-rockies", "rockies", "summits", "medium"],
  ["places-medium-andes", "andes", "peaks", "medium"],
  ["places-medium-kilimanjaro", "kilimanjaro", "summit", "medium"],
  ["places-medium-malibu", "malibu", "surfers", "medium"],
  ["places-medium-tuscany", "tuscany", "vineyards", "medium"],
  ["places-medium-siberia", "siberia", "exile", "medium"],
  ["places-medium-patagonia", "patagonia", "wind", "medium"],
  ["places-medium-amazon-rainforest", "amazon rainforest", "canopy", "medium"],
  ["places-medium-crete", "crete", "myths", "medium"],
  ["places-medium-giza", "giza", "pyramids", "medium"],
  ["places-medium-pompeii", "pompeii", "ash", "medium"],
  ["places-medium-arizona", "arizona", "dryness", "medium"],
  ["places-medium-nevada", "nevada", "casinos", "medium"],
  ["places-medium-colorado", "colorado", "peaks", "medium"],
  ["places-medium-washington", "washington", "evergreens", "medium"],
  ["places-medium-oregon", "oregon", "evergreens", "medium"],
  ["places-medium-maine", "maine", "lobsters", "medium"],
  ["places-medium-louisiana", "louisiana", "jazz", "medium"],
  ["places-medium-georgia", "georgia", "peaches", "medium"],
  ["places-medium-tennessee", "tennessee", "guitars", "medium"],
  ["places-medium-carolina", "carolina", "barbecue", "medium"],
  ["places-medium-dormitory", "dormitory", "ramen", "medium"],
  ["places-medium-mailroom", "mailroom", "sorting", "medium"],
  ["places-medium-reservoir", "reservoir", "drought", "medium"],
  ["places-medium-guesthouse", "guesthouse", "hospitality", "medium"],
  ["places-medium-north-america", "north america", "highways", "medium"],
  ["places-medium-south-america", "south america", "rainforest", "medium"],
  ["places-medium-korea", "korea", "kimchi", "medium"],
  ["places-medium-taiwan", "taiwan", "boba", "medium"],
  ["places-hard-islet", "islet", "tiny", "hard"],
  ["places-hard-archipelago", "archipelago", "scattered", "hard"],
  ["places-hard-bog", "bog", "sinking", "hard"],
  ["places-hard-strait", "strait", "narrowness", "hard"],
  ["places-hard-fjord", "fjord", "cliffs", "hard"],
  ["places-hard-atoll", "atoll", "ring", "hard"],
  ["places-hard-lowland", "lowland", "flatness", "hard"],
  ["places-hard-highland", "highland", "mist", "hard"],
  ["places-hard-steppe", "steppe", "winds", "hard"],
  ["places-hard-quarry", "quarry", "blasting", "hard"],
  ["places-hard-serbia", "serbia", "balkans", "hard"],
  ["places-hard-uganda", "uganda", "gorillas", "hard"],
  ["places-hard-el-salvador", "el salvador", "surfing", "hard"],
  ["places-hard-baltic", "baltic", "amber", "hard"],
  ["places-hard-hamburg", "hamburg", "harbor", "hard"],
  ["places-hard-brussels", "brussels", "bureaucracy", "hard"],
  ["places-hard-budapest", "budapest", "baths", "hard"],
  ["places-hard-warsaw", "warsaw", "resilience", "hard"],
  ["places-hard-stockholm", "stockholm", "design", "hard"],
  ["places-hard-oslo", "oslo", "nobel", "hard"],
  ["places-hard-copenhagen", "copenhagen", "cycling", "hard"],
  ["places-hard-helsinki", "helsinki", "design", "hard"],
  ["places-hard-reykjavik", "reykjavik", "volcanoes", "hard"],
  ["places-hard-doha", "doha", "skyscrapers", "hard"],
  ["places-hard-alexandria", "alexandria", "library", "hard"],
  ["places-hard-tel-aviv", "tel aviv", "nightlife", "hard"],
  ["places-hard-casablanca", "casablanca", "cinema", "hard"],
  ["places-hard-marrakesh", "marrakesh", "souks", "hard"],
  ["places-hard-nairobi", "nairobi", "safaris", "hard"],
  ["places-hard-lagos", "lagos", "hustle", "hard"],
  ["places-hard-accra", "accra", "gold", "hard"],
  ["places-hard-cape-town", "cape town", "penguins", "hard"],
  ["places-hard-osaka", "osaka", "streetfood", "hard"],
  ["places-hard-hanoi", "hanoi", "scooters", "hard"],
  ["places-hard-manila", "manila", "jeepneys", "hard"],
  ["places-hard-jakarta", "jakarta", "flooding", "hard"],
  ["places-hard-kuala-lumpur", "kuala lumpur", "towers", "hard"],
  ["places-hard-kolkata", "kolkata", "poets", "hard"],
  ["places-hard-brisbane", "brisbane", "sunburn", "hard"],
  ["places-hard-auckland", "auckland", "harbors", "hard"],
  ["places-hard-queens", "queens", "airports", "hard"],
  ["places-hard-bronx", "bronx", "yankees", "hard"],
  ["places-hard-venice-beach", "venice beach", "skating", "hard"],
  ["places-hard-santa-monica", "santa monica", "pier", "hard"],
  ["places-hard-kremlin", "kremlin", "power", "hard"],
  ["places-hard-red-square", "red square", "parades", "hard"],
  ["places-hard-sagrada-familia", "sagrada familia", "unfinished", "hard"],
  ["places-hard-petra", "petra", "sandstone", "hard"],
  ["places-hard-angkor-wat", "angkor wat", "ruins", "hard"],
  ["places-hard-alcatraz", "alcatraz", "escape", "hard"],
  ["places-hard-versailles", "versailles", "opulence", "hard"],
  ["places-hard-hoover-dam", "hoover dam", "concrete", "hard"],
  ["places-hard-blue-mosque", "blue mosque", "domes", "hard"],
  ["places-hard-golden-temple", "golden temple", "reflection", "hard"],
  ["places-hard-tower-bridge", "tower bridge", "raising", "hard"],
  ["places-hard-hyde-park", "hyde park", "speakers", "hard"],
  ["places-hard-wimbledon", "wimbledon", "strawberries", "hard"],
  ["places-hard-abbey-road", "abbey road", "crossing", "hard"],
  ["places-hard-lake-superior", "lake superior", "coldness", "hard"],
  ["places-hard-lake-victoria", "lake victoria", "source", "hard"],
  ["places-hard-lake-como", "lake como", "villas", "hard"],
  ["places-hard-loch-ness", "loch ness", "monster", "hard"],
  ["places-hard-everglades", "everglades", "alligators", "hard"],
  ["places-hard-danube", "danube", "blue", "hard"],
  ["places-hard-thames", "thames", "bridges", "hard"],
  ["places-hard-monte-carlo", "monte carlo", "roulette", "hard"],
  ["places-hard-cannes", "cannes", "premieres", "hard"],
  ["places-hard-normandy", "normandy", "landing", "hard"],
  ["places-hard-provence", "provence", "lavender", "hard"],
  ["places-hard-suez-canal", "suez canal", "shortcut", "hard"],
  ["places-hard-panama-canal", "panama canal", "locks", "hard"],
  ["places-hard-bermuda", "bermuda", "triangle", "hard"],
  ["places-hard-aruba", "aruba", "breezes", "hard"],
  ["places-hard-guam", "guam", "military", "hard"],
  ["places-hard-tahiti", "tahiti", "paradise", "hard"],
  ["places-hard-seychelles", "seychelles", "granite", "hard"],
  ["places-hard-capri", "capri", "grottos", "hard"],
  ["places-hard-mykonos", "mykonos", "windmills", "hard"],
  ["places-hard-sinai", "sinai", "tablets", "hard"],
  ["places-hard-uluru", "uluru", "sacred", "hard"],
  ["places-hard-chichen-itza", "chichen itza", "calendar", "hard"],
  ["places-hard-banff", "banff", "glacial", "hard"],
  ["places-hard-zanzibar", "zanzibar", "spices", "hard"],
  ["places-hard-trailhead", "trailhead", "anticipation", "hard"],
  ["places-hard-boathouse", "boathouse", "oars", "hard"],
  ["places-hard-houseboat", "houseboat", "floating", "hard"],
  ["places-hard-yurt", "yurt", "canvas", "hard"],
  ["places-hard-puerto-rico", "puerto rico", "coqui", "hard"],
  ["places-hard-abu-dhabi", "abu dhabi", "wealth", "hard"],
  ["places-hard-taipei", "taipei", "boba", "hard"],
  ["places-hard-zurich", "zurich", "banking", "hard"],
  ["places-hard-geneva", "geneva", "diplomacy", "hard"],
] as const;
