export const sportsCatalog = [
  ["sports-easy-soccer", "soccer", "diving", "easy"],
  ["sports-easy-football", "football", "collision", "easy"],
  ["sports-easy-basketball", "basketball", "vertical", "easy"],
  ["sports-easy-baseball", "baseball", "nostalgia", "easy"],
  ["sports-easy-volleyball", "volleyball", "bruises", "easy"],
  ["sports-easy-hockey", "hockey", "teeth", "easy"],
  ["sports-easy-cricket", "cricket", "patience", "easy"],
  ["sports-easy-dodgeball", "dodgeball", "panic", "easy"],
  ["sports-easy-tennis", "tennis", "grunting", "easy"],
  ["sports-easy-table-tennis", "table tennis", "reflexes", "easy"],
  ["sports-easy-badminton", "badminton", "feathers", "easy"],
  ["sports-easy-golf", "golf", "frustration", "easy"],
  ["sports-easy-mini-golf", "mini golf", "obstacles", "easy"],
  ["sports-easy-bowling", "bowling", "gutters", "easy"],
  ["sports-easy-darts", "darts", "accuracy", "easy"],
  ["sports-easy-boxing", "boxing", "swelling", "easy"],
  ["sports-easy-wrestling", "wrestling", "pinning", "easy"],
  ["sports-easy-karate", "karate", "discipline", "easy"],
  ["sports-easy-kung-fu", "kung fu", "choreography", "easy"],
  ["sports-easy-martial-arts", "martial arts", "discipline", "easy"],
  ["sports-easy-weightlifting", "weightlifting", "strain", "easy"],
  ["sports-easy-arm-wrestling", "arm wrestling", "pride", "easy"],
  ["sports-easy-running", "running", "breathless", "easy"],
  ["sports-easy-jogging", "jogging", "rhythm", "easy"],
  ["sports-easy-sprinting", "sprinting", "adrenaline", "easy"],
  ["sports-easy-marathon", "marathon", "endurance", "easy"],
  ["sports-easy-cycling", "cycling", "balance", "easy"],
  ["sports-easy-biking", "biking", "freedom", "easy"],
  ["sports-easy-racing", "racing", "speed", "easy"],
  ["sports-easy-track", "track", "laps", "easy"],
  ["sports-easy-gymnastics", "gymnastics", "flexibility", "easy"],
  ["sports-easy-trampoline", "trampoline", "bouncing", "easy"],
  ["sports-easy-skateboarding", "skateboarding", "pavement", "easy"],
  ["sports-easy-roller-skating", "roller skating", "wobbling", "easy"],
  ["sports-easy-breakdancing", "breakdancing", "spinning", "easy"],
  ["sports-easy-archery", "archery", "focus", "easy"],
  ["sports-easy-rock-climbing", "rock climbing", "grip", "easy"],
  ["sports-easy-climbing", "climbing", "heights", "easy"],
  ["sports-easy-swimming", "swimming", "breath", "easy"],
  ["sports-easy-diving", "diving", "splash", "easy"],
  ["sports-easy-surfing", "surfing", "wipeout", "easy"],
  ["sports-easy-sailing", "sailing", "wind", "easy"],
  ["sports-easy-snorkeling", "snorkeling", "coral", "easy"],
  ["sports-easy-scuba-diving", "scuba diving", "pressure", "easy"],
  ["sports-easy-fishing", "fishing", "patience", "easy"],
  ["sports-easy-skiing", "skiing", "slopes", "easy"],
  ["sports-easy-snowboarding", "snowboarding", "carving", "easy"],
  ["sports-easy-skating", "skating", "balance", "easy"],
  ["sports-easy-ice-skating", "ice skating", "blades", "easy"],
  ["sports-easy-sledding", "sledding", "downhill", "easy"],
  ["sports-easy-hiking", "hiking", "blisters", "easy"],
  ["sports-easy-hunting", "hunting", "silence", "easy"],
  ["sports-easy-horse-racing", "horse racing", "betting", "easy"],
  ["sports-easy-formula-one", "formula one", "engine", "easy"],
  ["sports-easy-team", "team", "chemistry", "easy"],
  ["sports-easy-player", "player", "pressure", "easy"],
  ["sports-easy-coach", "coach", "yelling", "easy"],
  ["sports-easy-referee", "referee", "blame", "easy"],
  ["sports-easy-captain", "captain", "leadership", "easy"],
  ["sports-easy-fan", "fan", "loyalty", "easy"],
  ["sports-easy-mascot", "mascot", "costume", "easy"],
  ["sports-easy-stadium", "stadium", "roar", "easy"],
  ["sports-easy-arena", "arena", "echo", "easy"],
  ["sports-easy-scoreboard", "scoreboard", "suspense", "easy"],
  ["sports-easy-trophy", "trophy", "bragging", "easy"],
  ["sports-easy-medal", "medal", "pride", "easy"],
  ["sports-easy-uniform", "uniform", "identity", "easy"],
  ["sports-easy-helmet", "helmet", "impact", "easy"],
  ["sports-easy-whistle", "whistle", "interruption", "easy"],
  ["sports-easy-bench", "bench", "patience", "easy"],
  ["sports-easy-overtime", "overtime", "tension", "easy"],
  ["sports-easy-timeout", "timeout", "reset", "easy"],
  ["sports-easy-serve", "serve", "pressure", "easy"],
  ["sports-easy-ace", "ace", "precision", "easy"],
  ["sports-easy-match", "match", "rivalry", "easy"],
  ["sports-easy-set", "set", "momentum", "easy"],
  ["sports-easy-quarter", "quarter", "countdown", "easy"],
  ["sports-easy-period", "period", "countdown", "easy"],
  ["sports-easy-lap", "lap", "repetition", "easy"],
  ["sports-easy-championship", "championship", "legacy", "easy"],
  ["sports-easy-playoffs", "playoffs", "pressure", "easy"],
  ["sports-easy-finals", "finals", "stakes", "easy"],
  ["sports-easy-tournament", "tournament", "elimination", "easy"],
  ["sports-easy-league", "league", "standings", "easy"],
  ["sports-easy-trade", "trade", "rumors", "easy"],
  ["sports-easy-practice", "practice", "repetition", "easy"],
  ["sports-easy-training", "training", "soreness", "easy"],
  ["sports-easy-warmup", "warmup", "preparation", "easy"],
  ["sports-easy-workout", "workout", "soreness", "easy"],
  ["sports-easy-record", "record", "legacy", "easy"],
  ["sports-easy-ranking", "ranking", "ego", "easy"],
  ["sports-easy-comeback", "comeback", "hope", "easy"],
  ["sports-easy-tie", "tie", "unresolved", "easy"],
  ["sports-easy-draw", "draw", "stalemate", "easy"],
  ["sports-easy-loss", "loss", "silence", "easy"],
  ["sports-easy-win", "win", "celebration", "easy"],
  ["sports-easy-victory", "victory", "relief", "easy"],
  ["sports-easy-defeat", "defeat", "humility", "easy"],
  ["sports-easy-score", "score", "proof", "easy"],
  ["sports-easy-points", "points", "advantage", "easy"],
  ["sports-easy-ball", "ball", "bounce", "easy"],
  ["sports-easy-bat", "bat", "swing", "easy"],
  ["sports-easy-racket", "racket", "strings", "easy"],
  ["sports-easy-glove", "glove", "catching", "easy"],
  ["sports-easy-skates", "skates", "blades", "easy"],
  ["sports-easy-goggles", "goggles", "fogging", "easy"],
  ["sports-easy-net", "net", "barrier", "easy"],
  ["sports-easy-surfboard", "surfboard", "balance", "easy"],
  ["sports-easy-skateboard", "skateboard", "pavement", "easy"],
  ["sports-easy-snowboard", "snowboard", "carving", "easy"],
  ["sports-easy-skis", "skis", "slopes", "easy"],
  ["sports-easy-paddle", "paddle", "splash", "easy"],
  ["sports-easy-bow", "bow", "tension", "easy"],
  ["sports-easy-arrow", "arrow", "trajectory", "easy"],
  ["sports-easy-target", "target", "focus", "easy"],
  ["sports-easy-frisbee", "frisbee", "flying", "easy"],
  ["sports-easy-yo-yo", "yo-yo", "rebound", "easy"],
  ["sports-easy-jump-rope", "jump rope", "rhythm", "easy"],
  ["sports-easy-hula-hoop", "hula hoop", "hips", "easy"],
  ["sports-easy-chess", "chess", "strategy", "easy"],
  ["sports-easy-checkers", "checkers", "jumps", "easy"],
  ["sports-easy-monopoly", "monopoly", "bankruptcy", "easy"],
  ["sports-easy-scrabble", "scrabble", "vocabulary", "easy"],
  ["sports-easy-dominoes", "dominoes", "chain", "easy"],
  ["sports-easy-bingo", "bingo", "luck", "easy"],
  ["sports-easy-poker", "poker", "bluffing", "easy"],
  ["sports-easy-blackjack", "blackjack", "risk", "easy"],
  ["sports-easy-solitaire", "solitaire", "loneliness", "easy"],
  ["sports-easy-uno", "uno", "betrayal", "easy"],
  ["sports-easy-war", "war", "randomness", "easy"],
  ["sports-easy-go-fish", "go fish", "asking", "easy"],
  ["sports-easy-memory", "memory", "concentration", "easy"],
  ["sports-easy-jenga", "jenga", "collapse", "easy"],
  ["sports-easy-connect-four", "connect four", "gravity", "easy"],
  ["sports-easy-battleship", "battleship", "coordinates", "easy"],
  ["sports-easy-twister", "twister", "awkwardness", "easy"],
  ["sports-easy-pictionary", "pictionary", "sketches", "easy"],
  ["sports-easy-charades", "charades", "gestures", "easy"],
  ["sports-easy-hangman", "hangman", "letters", "easy"],
  ["sports-easy-guess-who", "guess who", "faces", "easy"],
  ["sports-easy-crossword", "crossword", "clues", "easy"],
  ["sports-easy-sudoku", "sudoku", "logic", "easy"],
  ["sports-easy-wordle", "wordle", "streak", "easy"],
  ["sports-easy-puzzle", "puzzle", "patience", "easy"],
  ["sports-easy-jigsaw", "jigsaw", "edges", "easy"],
  ["sports-easy-maze", "maze", "confusion", "easy"],
  ["sports-easy-riddle", "riddle", "twist", "easy"],
  ["sports-easy-trivia", "trivia", "knowledge", "easy"],
  ["sports-easy-quiz", "quiz", "pressure", "easy"],
  ["sports-easy-tag", "tag", "chasing", "easy"],
  ["sports-easy-hide-and-seek", "hide-and-seek", "silence", "easy"],
  ["sports-easy-hopscotch", "hopscotch", "chalk", "easy"],
  ["sports-easy-marbles", "marbles", "rolling", "easy"],
  ["sports-easy-musical-chairs", "musical chairs", "panic", "easy"],
  ["sports-easy-simon-says", "simon says", "obedience", "easy"],
  ["sports-easy-hot-potato", "hot potato", "panic", "easy"],
  ["sports-easy-telephone", "telephone", "distortion", "easy"],
  ["sports-easy-truth-or-dare", "truth-or-dare", "embarrassment", "easy"],
  [
    "sports-easy-rock-paper-scissors",
    "rock-paper-scissors",
    "decision",
    "easy",
  ],
  ["sports-easy-duck-duck-goose", "duck-duck-goose", "suspense", "easy"],
  ["sports-easy-floor-is-lava", "floor-is-lava", "imagination", "easy"],
  ["sports-easy-scavenger-hunt", "scavenger hunt", "clues", "easy"],
  ["sports-easy-escape-room", "escape room", "locks", "easy"],
  ["sports-easy-pretend", "pretend", "imagination", "easy"],
  ["sports-easy-minecraft", "minecraft", "creativity", "easy"],
  ["sports-easy-fortnite", "fortnite", "building", "easy"],
  ["sports-easy-roblox", "roblox", "chaos", "easy"],
  ["sports-easy-tetris", "tetris", "stacking", "easy"],
  ["sports-easy-mario", "mario", "mushrooms", "easy"],
  ["sports-easy-zelda", "zelda", "adventure", "easy"],
  ["sports-easy-pokemon", "pokemon", "evolution", "easy"],
  ["sports-easy-sonic", "sonic", "speed", "easy"],
  ["sports-easy-pac-man", "pac-man", "hunger", "easy"],
  ["sports-easy-mario-kart", "mario kart", "betrayal", "easy"],
  ["sports-easy-super-mario", "super mario", "mushrooms", "easy"],
  ["sports-easy-pokemon-go", "pokemon go", "wandering", "easy"],
  ["sports-easy-among-us", "among us", "suspicion", "easy"],
  ["sports-easy-fifa", "fifa", "rage", "easy"],
  ["sports-easy-candy-crush", "candy crush", "addiction", "easy"],
  ["sports-easy-angry-birds", "angry birds", "slingshot", "easy"],
  ["sports-easy-pinball", "pinball", "ricochet", "easy"],
  ["sports-easy-controller", "controller", "thumbs", "easy"],
  ["sports-easy-joystick", "joystick", "tilt", "easy"],
  ["sports-easy-keyboard", "keyboard", "shortcuts", "easy"],
  ["sports-easy-headset", "headset", "shouting", "easy"],
  ["sports-easy-level", "level", "progress", "easy"],
  ["sports-easy-boss", "boss", "challenge", "easy"],
  ["sports-easy-rematch", "rematch", "revenge", "easy"],
  ["sports-easy-lives", "lives", "chances", "easy"],
  ["sports-easy-coins", "coins", "rewards", "easy"],
  ["sports-easy-timer", "timer", "urgency", "easy"],
  ["sports-easy-turns", "turns", "patience", "easy"],
  ["sports-easy-dice", "dice", "luck", "easy"],
  ["sports-easy-cards", "cards", "bluffing", "easy"],
  ["sports-easy-pieces", "pieces", "strategy", "easy"],
  ["sports-easy-board", "board", "setup", "easy"],
  ["sports-easy-lottery", "lottery", "hope", "easy"],
  ["sports-easy-super-bowl", "super bowl", "commercials", "easy"],
  ["sports-easy-world-cup", "world cup", "flags", "easy"],
  ["sports-easy-olympics", "olympics", "torch", "easy"],
  ["sports-medium-softball", "softball", "underhand", "medium"],
  ["sports-medium-rugby", "rugby", "tackles", "medium"],
  ["sports-medium-lacrosse", "lacrosse", "scooping", "medium"],
  ["sports-medium-handball", "handball", "walls", "medium"],
  ["sports-medium-polo", "polo", "horses", "medium"],
  ["sports-medium-water-polo", "water polo", "splashing", "medium"],
  ["sports-medium-ice-hockey", "ice hockey", "teeth", "medium"],
  ["sports-medium-field-hockey", "field hockey", "sticks", "medium"],
  ["sports-medium-beach-volleyball", "beach volleyball", "diving", "medium"],
  ["sports-medium-flag-football", "flag football", "grabbing", "medium"],
  ["sports-medium-kickball", "kickball", "rubber", "medium"],
  ["sports-medium-ultimate-frisbee", "ultimate frisbee", "layout", "medium"],
  ["sports-medium-disc-golf", "disc golf", "baskets", "medium"],
  ["sports-medium-pickleball", "pickleball", "paddle", "medium"],
  ["sports-medium-squash", "squash", "ricochet", "medium"],
  ["sports-medium-racquetball", "racquetball", "walls", "medium"],
  ["sports-medium-billiards", "billiards", "angles", "medium"],
  ["sports-medium-snooker", "snooker", "precision", "medium"],
  ["sports-medium-foosball", "foosball", "spinning", "medium"],
  ["sports-medium-air-hockey", "air hockey", "friction", "medium"],
  ["sports-medium-laser-tag", "laser tag", "ambush", "medium"],
  ["sports-medium-paintball", "paintball", "bruises", "medium"],
  ["sports-medium-horseshoes", "horseshoes", "clanging", "medium"],
  ["sports-medium-croquet", "croquet", "mallets", "medium"],
  ["sports-medium-judo", "judo", "throws", "medium"],
  ["sports-medium-taekwondo", "taekwondo", "kicking", "medium"],
  ["sports-medium-mma", "mma", "cage", "medium"],
  ["sports-medium-kickboxing", "kickboxing", "shins", "medium"],
  ["sports-medium-fencing", "fencing", "lunges", "medium"],
  ["sports-medium-sumo", "sumo", "pushing", "medium"],
  ["sports-medium-jiu-jitsu", "jiu jitsu", "grappling", "medium"],
  ["sports-medium-powerlifting", "powerlifting", "strain", "medium"],
  ["sports-medium-bodybuilding", "bodybuilding", "posing", "medium"],
  ["sports-medium-strongman", "strongman", "grunting", "medium"],
  ["sports-medium-triathlon", "triathlon", "endurance", "medium"],
  ["sports-medium-relay", "relay", "baton", "medium"],
  ["sports-medium-hurdles", "hurdles", "jumping", "medium"],
  ["sports-medium-high-jump", "high jump", "clearance", "medium"],
  ["sports-medium-long-jump", "long jump", "landing", "medium"],
  ["sports-medium-pole-vault", "pole vault", "launch", "medium"],
  ["sports-medium-shot-put", "shot put", "heavy", "medium"],
  ["sports-medium-javelin", "javelin", "throwing", "medium"],
  ["sports-medium-cross-country", "cross country", "mud", "medium"],
  ["sports-medium-decathlon", "decathlon", "versatility", "medium"],
  ["sports-medium-cheerleading", "cheerleading", "stunts", "medium"],
  ["sports-medium-parkour", "parkour", "rooftops", "medium"],
  ["sports-medium-rollerblading", "rollerblading", "wobbling", "medium"],
  ["sports-medium-mountaineering", "mountaineering", "altitude", "medium"],
  ["sports-medium-rowing", "rowing", "synchronization", "medium"],
  ["sports-medium-kayaking", "kayaking", "rapids", "medium"],
  ["sports-medium-canoeing", "canoeing", "paddling", "medium"],
  ["sports-medium-water-skiing", "water skiing", "spray", "medium"],
  ["sports-medium-wakeboarding", "wakeboarding", "spray", "medium"],
  ["sports-medium-rafting", "rafting", "rapids", "medium"],
  ["sports-medium-paddleboarding", "paddleboarding", "balance", "medium"],
  ["sports-medium-windsurfing", "windsurfing", "gusts", "medium"],
  ["sports-medium-jet-skiing", "jet skiing", "spray", "medium"],
  ["sports-medium-figure-skating", "figure skating", "elegance", "medium"],
  ["sports-medium-speed-skating", "speed skating", "blades", "medium"],
  ["sports-medium-bobsled", "bobsled", "gravity", "medium"],
  ["sports-medium-curling", "curling", "sweeping", "medium"],
  ["sports-medium-snowshoeing", "snowshoeing", "sinking", "medium"],
  ["sports-medium-ski-jumping", "ski jumping", "flight", "medium"],
  ["sports-medium-snowmobiling", "snowmobiling", "engine", "medium"],
  ["sports-medium-rodeo", "rodeo", "bucking", "medium"],
  ["sports-medium-bull-riding", "bull riding", "danger", "medium"],
  ["sports-medium-show-jumping", "show jumping", "elegance", "medium"],
  ["sports-medium-nascar", "nascar", "drafting", "medium"],
  ["sports-medium-motocross", "motocross", "mud", "medium"],
  ["sports-medium-rally-racing", "rally racing", "drift", "medium"],
  ["sports-medium-drag-racing", "drag racing", "launch", "medium"],
  ["sports-medium-go-karting", "go karting", "drifting", "medium"],
  ["sports-medium-monster-trucks", "monster trucks", "crushing", "medium"],
  ["sports-medium-motor-racing", "motor racing", "engine", "medium"],
  ["sports-medium-bike-racing", "bike racing", "drafting", "medium"],
  ["sports-medium-boat-racing", "boat racing", "wake", "medium"],
  ["sports-medium-umpire", "umpire", "ejection", "medium"],
  ["sports-medium-goalkeeper", "goalkeeper", "diving", "medium"],
  ["sports-medium-goalie", "goalie", "reflexes", "medium"],
  ["sports-medium-quarterback", "quarterback", "pressure", "medium"],
  ["sports-medium-pitcher", "pitcher", "curveball", "medium"],
  ["sports-medium-catcher", "catcher", "squatting", "medium"],
  ["sports-medium-batter", "batter", "timing", "medium"],
  ["sports-medium-striker", "striker", "finishing", "medium"],
  ["sports-medium-defender", "defender", "blocking", "medium"],
  ["sports-medium-midfielder", "midfielder", "stamina", "medium"],
  ["sports-medium-jersey", "jersey", "identity", "medium"],
  ["sports-medium-halftime", "halftime", "reset", "medium"],
  ["sports-medium-kickoff", "kickoff", "anticipation", "medium"],
  ["sports-medium-touchdown", "touchdown", "celebration", "medium"],
  ["sports-medium-rally", "rally", "momentum", "medium"],
  ["sports-medium-inning", "inning", "patience", "medium"],
  ["sports-medium-draft", "draft", "prospects", "medium"],
  ["sports-medium-streak", "streak", "momentum", "medium"],
  ["sports-medium-seed", "seed", "placement", "medium"],
  ["sports-medium-bracket", "bracket", "chaos", "medium"],
  ["sports-medium-underdog", "underdog", "upset", "medium"],
  ["sports-medium-shutout", "shutout", "dominance", "medium"],
  ["sports-medium-puck", "puck", "sliding", "medium"],
  ["sports-medium-cleats", "cleats", "traction", "medium"],
  ["sports-medium-goalpost", "goalpost", "heartbreak", "medium"],
  ["sports-medium-mouthguard", "mouthguard", "impact", "medium"],
  ["sports-medium-oar", "oar", "leverage", "medium"],
  ["sports-medium-clue", "clue", "suspicion", "medium"],
  ["sports-medium-risk", "risk", "conquest", "medium"],
  ["sports-medium-catan", "catan", "sheep", "medium"],
  ["sports-medium-backgammon", "backgammon", "doubling", "medium"],
  ["sports-medium-mahjong", "mahjong", "tiles", "medium"],
  ["sports-medium-rummy", "rummy", "melding", "medium"],
  ["sports-medium-bridge", "bridge", "partnership", "medium"],
  ["sports-medium-hearts", "hearts", "avoidance", "medium"],
  ["sports-medium-spades", "spades", "bidding", "medium"],
  ["sports-medium-gin", "gin", "knocking", "medium"],
  ["sports-medium-crazy-eights", "crazy eights", "switching", "medium"],
  ["sports-medium-old-maid", "old maid", "avoidance", "medium"],
  ["sports-medium-snap", "snap", "reflexes", "medium"],
  ["sports-medium-operation", "operation", "buzzing", "medium"],
  ["sports-medium-yahtzee", "yahtzee", "luck", "medium"],
  ["sports-medium-trouble", "trouble", "popping", "medium"],
  ["sports-medium-sorry", "sorry", "revenge", "medium"],
  ["sports-medium-life", "life", "choices", "medium"],
  ["sports-medium-mastermind", "mastermind", "deduction", "medium"],
  ["sports-medium-mancala", "mancala", "counting", "medium"],
  ["sports-medium-mousetrap", "mousetrap", "contraption", "medium"],
  ["sports-medium-taboo", "taboo", "forbidden", "medium"],
  ["sports-medium-codenames", "codenames", "whispers", "medium"],
  ["sports-medium-pandemic", "pandemic", "cooperation", "medium"],
  ["sports-medium-sequence", "sequence", "patterns", "medium"],
  [
    "sports-medium-exploding-kittens",
    "exploding kittens",
    "paranoia",
    "medium",
  ],
  ["sports-medium-trivial-pursuit", "trivial pursuit", "knowledge", "medium"],
  ["sports-medium-scattergories", "scattergories", "pressure", "medium"],
  ["sports-medium-boggle", "boggle", "scrambling", "medium"],
  ["sports-medium-ticket-to-ride", "ticket-to-ride", "routes", "medium"],
  ["sports-medium-spelling-bee", "spelling bee", "nerves", "medium"],
  ["sports-medium-brain-teaser", "brain teaser", "confusion", "medium"],
  ["sports-medium-red-rover", "red rover", "collision", "medium"],
  ["sports-medium-four-square", "four square", "bounce", "medium"],
  ["sports-medium-heads-up", "heads up", "guessing", "medium"],
  ["sports-medium-seven-up", "seven up", "thumbs", "medium"],
  ["sports-medium-capture-the-flag", "capture-the-flag", "sneaking", "medium"],
  ["sports-medium-flashlight-tag", "flashlight tag", "shadows", "medium"],
  ["sports-medium-freeze-tag", "freeze tag", "stiffness", "medium"],
  ["sports-medium-keep-away", "keep away", "teasing", "medium"],
  ["sports-medium-king-of-the-hill", "king-of-the-hill", "dominance", "medium"],
  ["sports-medium-murder-mystery", "murder mystery", "suspicion", "medium"],
  ["sports-medium-roleplay", "roleplay", "pretending", "medium"],
  ["sports-medium-wii-sports", "wii sports", "swinging", "medium"],
  ["sports-medium-fall-guys", "fall guys", "chaos", "medium"],
  ["sports-medium-halo", "halo", "armor", "medium"],
  ["sports-medium-doom", "doom", "demons", "medium"],
  ["sports-medium-madden", "madden", "audibles", "medium"],
  ["sports-medium-nba-2k", "nba 2k", "dribbling", "medium"],
  ["sports-medium-rocket-league", "rocket league", "aerials", "medium"],
  ["sports-medium-apex-legends", "apex legends", "squads", "medium"],
  ["sports-medium-overwatch", "overwatch", "teamwork", "medium"],
  ["sports-medium-valorant", "valorant", "headshots", "medium"],
  ["sports-medium-warzone", "warzone", "gulag", "medium"],
  ["sports-medium-counter-strike", "counter-strike", "defuse", "medium"],
  ["sports-medium-clash-royale", "clash royale", "elixir", "medium"],
  ["sports-medium-temple-run", "temple run", "chasing", "medium"],
  ["sports-medium-subway-surfers", "subway surfers", "dodging", "medium"],
  ["sports-medium-fruit-ninja", "fruit ninja", "slicing", "medium"],
  ["sports-medium-flappy-bird", "flappy bird", "frustration", "medium"],
  ["sports-medium-minesweeper", "minesweeper", "guessing", "medium"],
  ["sports-medium-space-invaders", "space invaders", "aliens", "medium"],
  ["sports-medium-street-fighter", "street fighter", "combos", "medium"],
  ["sports-medium-mortal-kombat", "mortal kombat", "fatality", "medium"],
  ["sports-medium-tekken", "tekken", "combos", "medium"],
  ["sports-medium-donkey-kong", "donkey kong", "barrels", "medium"],
  ["sports-medium-animal-crossing", "animal crossing", "debt", "medium"],
  ["sports-medium-stardew-valley", "stardew valley", "farming", "medium"],
  ["sports-medium-the-sims", "the sims", "control", "medium"],
  ["sports-medium-simcity", "simcity", "planning", "medium"],
  ["sports-medium-civilization", "civilization", "diplomacy", "medium"],
  ["sports-medium-skyrim", "skyrim", "dragons", "medium"],
  ["sports-medium-fallout", "fallout", "radiation", "medium"],
  ["sports-medium-gta", "gta", "chaos", "medium"],
  ["sports-medium-red-dead", "red dead", "outlaw", "medium"],
  ["sports-medium-cyberpunk", "cyberpunk", "neon", "medium"],
  ["sports-medium-elden-ring", "elden ring", "suffering", "medium"],
  ["sports-medium-dark-souls", "dark souls", "punishment", "medium"],
  ["sports-medium-dota", "dota", "toxicity", "medium"],
  ["sports-medium-pubg", "pubg", "looting", "medium"],
  ["sports-medium-free-fire", "free fire", "survival", "medium"],
  ["sports-medium-genshin-impact", "genshin impact", "wishes", "medium"],
  ["sports-medium-terraria", "terraria", "digging", "medium"],
  ["sports-medium-undertale", "undertale", "mercy", "medium"],
  ["sports-medium-portal", "portal", "momentum", "medium"],
  ["sports-medium-bioshock", "bioshock", "dystopia", "medium"],
  ["sports-medium-metroid", "metroid", "isolation", "medium"],
  ["sports-medium-kirby", "kirby", "sucking", "medium"],
  ["sports-medium-splatoon", "splatoon", "ink", "medium"],
  ["sports-medium-diablo", "diablo", "demons", "medium"],
  ["sports-medium-warcraft", "warcraft", "factions", "medium"],
  ["sports-medium-starcraft", "starcraft", "rushing", "medium"],
  ["sports-medium-bejeweled", "bejeweled", "gems", "medium"],
  ["sports-medium-plants-vs-zombies", "plants-vs-zombies", "brains", "medium"],
  ["sports-medium-farmville", "farmville", "chores", "medium"],
  ["sports-medium-just-dance", "just dance", "sweat", "medium"],
  ["sports-medium-guitar-hero", "guitar hero", "strumming", "medium"],
  ["sports-medium-rock-band", "rock band", "drums", "medium"],
  ["sports-medium-dance-revolution", "dance revolution", "footsteps", "medium"],
  ["sports-medium-gran-turismo", "gran turismo", "realism", "medium"],
  ["sports-medium-forza", "forza", "speed", "medium"],
  ["sports-medium-need-for-speed", "need-for-speed", "nitro", "medium"],
  ["sports-medium-assassin-s-creed", "assassin's creed", "stealth", "medium"],
  ["sports-medium-tomb-raider", "tomb raider", "archaeology", "medium"],
  ["sports-medium-resident-evil", "resident evil", "zombies", "medium"],
  ["sports-medium-kingdom-hearts", "kingdom hearts", "nostalgia", "medium"],
  ["sports-medium-final-fantasy", "final fantasy", "crystals", "medium"],
  ["sports-medium-monster-hunter", "monster hunter", "grinding", "medium"],
  ["sports-medium-quest", "quest", "adventure", "medium"],
  ["sports-medium-loot", "loot", "greed", "medium"],
  ["sports-medium-checkpoint", "checkpoint", "relief", "medium"],
  ["sports-medium-avatar", "avatar", "identity", "medium"],
  ["sports-medium-skin", "skin", "vanity", "medium"],
  ["sports-medium-multiplayer", "multiplayer", "chaos", "medium"],
  ["sports-medium-singleplayer", "singleplayer", "immersion", "medium"],
  ["sports-medium-lobby", "lobby", "impatience", "medium"],
  ["sports-medium-esports", "esports", "sponsors", "medium"],
  ["sports-medium-streamer", "streamer", "donation", "medium"],
  ["sports-medium-gameplay", "gameplay", "mechanics", "medium"],
  ["sports-medium-leaderboard", "leaderboard", "ego", "medium"],
  ["sports-medium-tokens", "tokens", "currency", "medium"],
  ["sports-medium-roulette", "roulette", "spin", "medium"],
  ["sports-medium-slots", "slots", "jackpot", "medium"],
  ["sports-medium-scratchcard", "scratchcard", "scratching", "medium"],
  ["sports-medium-fantasy-football", "fantasy football", "obsession", "medium"],
  ["sports-medium-fantasy-sports", "fantasy sports", "statistics", "medium"],
  ["sports-medium-sports-betting", "sports betting", "odds", "medium"],
  ["sports-medium-march-madness", "march madness", "brackets", "medium"],
  ["sports-medium-x-games", "x games", "extreme", "medium"],
  ["sports-medium-paralympics", "paralympics", "resilience", "medium"],
  ["sports-hard-netball", "netball", "passing", "hard"],
  ["sports-hard-futsal", "futsal", "indoors", "hard"],
  ["sports-hard-tetherball", "tetherball", "circling", "hard"],
  ["sports-hard-padel", "padel", "glass", "hard"],
  ["sports-hard-cornhole", "cornhole", "bags", "hard"],
  ["sports-hard-bocce", "bocce", "rolling", "hard"],
  ["sports-hard-shuffleboard", "shuffleboard", "sliding", "hard"],
  ["sports-hard-aikido", "aikido", "redirection", "hard"],
  ["sports-hard-capoeira", "capoeira", "rhythm", "hard"],
  ["sports-hard-muay-thai", "muay thai", "elbows", "hard"],
  ["sports-hard-discus", "discus", "spinning", "hard"],
  ["sports-hard-racewalking", "racewalking", "hips", "hard"],
  ["sports-hard-heptathlon", "heptathlon", "versatility", "hard"],
  ["sports-hard-pentathlon", "pentathlon", "variety", "hard"],
  ["sports-hard-orienteering", "orienteering", "compass", "hard"],
  ["sports-hard-luge", "luge", "sled", "hard"],
  ["sports-hard-biathlon", "biathlon", "rifles", "hard"],
  ["sports-hard-dressage", "dressage", "elegance", "hard"],
  ["sports-hard-equestrian", "equestrian", "reins", "hard"],
  ["sports-hard-demolition-derby", "demolition derby", "wreckage", "hard"],
  ["sports-hard-go", "go", "territory", "hard"],
  ["sports-hard-cribbage", "cribbage", "pegs", "hard"],
  ["sports-hard-canasta", "canasta", "melds", "hard"],
  ["sports-hard-euchre", "euchre", "trump", "hard"],
  ["sports-hard-perfection", "perfection", "anxiety", "hard"],
  ["sports-hard-azul", "azul", "tiles", "hard"],
  ["sports-hard-balderdash", "balderdash", "nonsense", "hard"],
  ["sports-hard-rummikub", "rummikub", "runs", "hard"],
  ["sports-hard-dixit", "dixit", "imagination", "hard"],
  ["sports-hard-carcassonne", "carcassonne", "tiles", "hard"],
  ["sports-hard-splendor", "splendor", "gems", "hard"],
  ["sports-hard-wingspan", "wingspan", "birds", "hard"],
  ["sports-hard-terraforming-mars", "terraforming mars", "oxygen", "hard"],
  ["sports-hard-gloomhaven", "gloomhaven", "campaign", "hard"],
  ["sports-hard-sardines", "sardines", "hiding", "hard"],
  ["sports-hard-runescape", "runescape", "grinding", "hard"],
  ["sports-hard-silent-hill", "silent hill", "fog", "hard"],
  ["sports-hard-dragon-quest", "dragon quest", "slime", "hard"],
  ["sports-hard-speedrun", "speedrun", "optimization", "hard"],
  ["sports-hard-craps", "craps", "roll", "hard"],
  ["sports-hard-baccarat", "baccarat", "banker", "hard"],
  ["sports-hard-keno", "keno", "selection", "hard"],
] as const;
