export type LanguageOption = {
  id: string;
  name: string;
  nativeName: string;
};

export const LANGUAGES: LanguageOption[] = [
  { id: 'afrikaans', name: 'Afrikaans', nativeName: 'Afrikaans' },
  { id: 'albanian', name: 'Albanian', nativeName: 'Shqip' },
  { id: 'amharic', name: 'Amharic', nativeName: 'አማርኛ' },
  { id: 'arabic', name: 'Arabic', nativeName: 'العربية' },
  { id: 'armenian', name: 'Armenian', nativeName: 'Հայերեն' },
  { id: 'assamese', name: 'Assamese', nativeName: 'অসমীয়া' },
  { id: 'aymara', name: 'Aymara', nativeName: 'Aymar aru' },
  { id: 'azerbaijani', name: 'Azerbaijani', nativeName: 'Azərbaycanca' },
  { id: 'bambara', name: 'Bambara', nativeName: 'Bamanankan' },
  { id: 'basque', name: 'Basque', nativeName: 'Euskara' },
  { id: 'belarusian', name: 'Belarusian', nativeName: 'Беларуская' },
  { id: 'bengali', name: 'Bengali', nativeName: 'বাংলা' },
  { id: 'bhojpuri', name: 'Bhojpuri', nativeName: 'भोजपुरी' },
  { id: 'bosnian', name: 'Bosnian', nativeName: 'Bosanski' },
  { id: 'bulgarian', name: 'Bulgarian', nativeName: 'Български' },
  { id: 'burmese', name: 'Burmese', nativeName: 'မြန်မာစာ' },
  { id: 'catalan', name: 'Catalan', nativeName: 'Català' },
  { id: 'cebuano', name: 'Cebuano', nativeName: 'Cebuano' },
  { id: 'chinese-simplified', name: 'Chinese (Simplified)', nativeName: '简体中文' },
  { id: 'chinese-traditional', name: 'Chinese (Traditional)', nativeName: '繁體中文' },
  { id: 'corsican', name: 'Corsican', nativeName: 'Corsu' },
  { id: 'croatian', name: 'Croatian', nativeName: 'Hrvatski' },
  { id: 'czech', name: 'Czech', nativeName: 'Čeština' },
  { id: 'danish', name: 'Danish', nativeName: 'Dansk' },
  { id: 'dhivehi', name: 'Dhivehi', nativeName: 'ދިވެހި' },
  { id: 'dogri', name: 'Dogri', nativeName: 'डोगरी' },
  { id: 'dutch', name: 'Dutch', nativeName: 'Nederlands' },
  { id: 'english', name: 'English', nativeName: 'English' },
  { id: 'esperanto', name: 'Esperanto', nativeName: 'Esperanto' },
  { id: 'estonian', name: 'Estonian', nativeName: 'Eesti' },
  { id: 'ewe', name: 'Ewe', nativeName: 'Eʋegbe' },
  { id: 'filipino', name: 'Filipino', nativeName: 'Filipino' },
  { id: 'finnish', name: 'Finnish', nativeName: 'Suomi' },
  { id: 'french', name: 'French', nativeName: 'Français' },
  { id: 'frisian', name: 'Frisian', nativeName: 'Frysk' },
  { id: 'galician', name: 'Galician', nativeName: 'Galego' },
  { id: 'georgian', name: 'Georgian', nativeName: 'ქართული' },
  { id: 'german', name: 'German', nativeName: 'Deutsch' },
  { id: 'greek', name: 'Greek', nativeName: 'Ελληνικά' },
  { id: 'guarani', name: 'Guarani', nativeName: 'Avañeʼẽ' },
  { id: 'gujarati', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { id: 'haitian-creole', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen' },
  { id: 'hausa', name: 'Hausa', nativeName: 'Hausa' },
  { id: 'hawaiian', name: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi' },
  { id: 'hebrew', name: 'Hebrew', nativeName: 'עברית' },
  { id: 'hindi', name: 'Hindi', nativeName: 'हिन्दी' },
  { id: 'hmong', name: 'Hmong', nativeName: 'Hmoob' },
  { id: 'hungarian', name: 'Hungarian', nativeName: 'Magyar' },
  { id: 'icelandic', name: 'Icelandic', nativeName: 'Íslenska' },
  { id: 'igbo', name: 'Igbo', nativeName: 'Igbo' },
  { id: 'ilocano', name: 'Ilocano', nativeName: 'Ilokano' },
  { id: 'indonesian', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { id: 'irish', name: 'Irish', nativeName: 'Gaeilge' },
  { id: 'italian', name: 'Italian', nativeName: 'Italiano' },
  { id: 'japanese', name: 'Japanese', nativeName: '日本語' },
  { id: 'javanese', name: 'Javanese', nativeName: 'Basa Jawa' },
  { id: 'kannada', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { id: 'kazakh', name: 'Kazakh', nativeName: 'Қазақша' },
  { id: 'khmer', name: 'Khmer', nativeName: 'ភាសាខ្មែរ' },
  { id: 'kinyarwanda', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda' },
  { id: 'konkani', name: 'Konkani', nativeName: 'कोंकणी' },
  { id: 'korean', name: 'Korean', nativeName: '한국어' },
  { id: 'krio', name: 'Krio', nativeName: 'Krio' },
  { id: 'kurdish-kurmanji', name: 'Kurdish (Kurmanji)', nativeName: 'Kurmancî' },
  { id: 'kurdish-sorani', name: 'Kurdish (Sorani)', nativeName: 'کوردیی ناوەندی' },
  { id: 'kyrgyz', name: 'Kyrgyz', nativeName: 'Кыргызча' },
  { id: 'lao', name: 'Lao', nativeName: 'ລາວ' },
  { id: 'latin', name: 'Latin', nativeName: 'Latina' },
  { id: 'latvian', name: 'Latvian', nativeName: 'Latviešu' },
  { id: 'lingala', name: 'Lingala', nativeName: 'Lingála' },
  { id: 'lithuanian', name: 'Lithuanian', nativeName: 'Lietuvių' },
  { id: 'luganda', name: 'Luganda', nativeName: 'Luganda' },
  { id: 'luxembourgish', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch' },
  { id: 'macedonian', name: 'Macedonian', nativeName: 'Македонски' },
  { id: 'maithili', name: 'Maithili', nativeName: 'मैथिली' },
  { id: 'malagasy', name: 'Malagasy', nativeName: 'Malagasy' },
  { id: 'malay', name: 'Malay', nativeName: 'Bahasa Melayu' },
  { id: 'malayalam', name: 'Malayalam', nativeName: 'മലയാളം' },
  { id: 'maltese', name: 'Maltese', nativeName: 'Malti' },
  { id: 'maori', name: 'Maori', nativeName: 'Māori' },
  { id: 'marathi', name: 'Marathi', nativeName: 'मराठी' },
  { id: 'meiteilon', name: 'Meiteilon (Manipuri)', nativeName: 'ꯃꯤꯇꯩꯂꯣꯟ' },
  { id: 'mizo', name: 'Mizo', nativeName: 'Mizo ṭawng' },
  { id: 'mongolian', name: 'Mongolian', nativeName: 'Монгол' },
  { id: 'nepali', name: 'Nepali', nativeName: 'नेपाली' },
  { id: 'norwegian', name: 'Norwegian', nativeName: 'Norsk' },
  { id: 'nyanja', name: 'Nyanja', nativeName: 'Chichewa' },
  { id: 'odia', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { id: 'oromo', name: 'Oromo', nativeName: 'Afaan Oromoo' },
  { id: 'pashto', name: 'Pashto', nativeName: 'پښتو' },
  { id: 'persian', name: 'Persian', nativeName: 'فارسی' },
  { id: 'polish', name: 'Polish', nativeName: 'Polski' },
  { id: 'portuguese', name: 'Portuguese', nativeName: 'Português' },
  { id: 'punjabi', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { id: 'quechua', name: 'Quechua', nativeName: 'Runasimi' },
  { id: 'romanian', name: 'Romanian', nativeName: 'Română' },
  { id: 'russian', name: 'Russian', nativeName: 'Русский' },
  { id: 'samoan', name: 'Samoan', nativeName: 'Gagana Samoa' },
  { id: 'sanskrit', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { id: 'scots-gaelic', name: 'Scots Gaelic', nativeName: 'Gàidhlig' },
  { id: 'sepedi', name: 'Sepedi', nativeName: 'Sepedi' },
  { id: 'serbian', name: 'Serbian', nativeName: 'Српски' },
  { id: 'sesotho', name: 'Sesotho', nativeName: 'Sesotho' },
  { id: 'shona', name: 'Shona', nativeName: 'ChiShona' },
  { id: 'sindhi', name: 'Sindhi', nativeName: 'سنڌي' },
  { id: 'sinhala', name: 'Sinhala', nativeName: 'සිංහල' },
  { id: 'slovak', name: 'Slovak', nativeName: 'Slovenčina' },
  { id: 'slovenian', name: 'Slovenian', nativeName: 'Slovenščina' },
  { id: 'somali', name: 'Somali', nativeName: 'Soomaali' },
  { id: 'spanish', name: 'Spanish', nativeName: 'Español' },
  { id: 'sundanese', name: 'Sundanese', nativeName: 'Basa Sunda' },
  { id: 'swahili', name: 'Swahili', nativeName: 'Kiswahili' },
  { id: 'swedish', name: 'Swedish', nativeName: 'Svenska' },
  { id: 'tajik', name: 'Tajik', nativeName: 'Тоҷикӣ' },
  { id: 'tamil', name: 'Tamil', nativeName: 'தமிழ்' },
  { id: 'tatar', name: 'Tatar', nativeName: 'Татарча' },
  { id: 'telugu', name: 'Telugu', nativeName: 'తెలుగు' },
  { id: 'thai', name: 'Thai', nativeName: 'ไทย' },
  { id: 'tigrinya', name: 'Tigrinya', nativeName: 'ትግርኛ' },
  { id: 'tsonga', name: 'Tsonga', nativeName: 'Xitsonga' },
  { id: 'turkish', name: 'Turkish', nativeName: 'Türkçe' },
  { id: 'turkmen', name: 'Turkmen', nativeName: 'Türkmençe' },
  { id: 'twi', name: 'Twi', nativeName: 'Twi' },
  { id: 'ukrainian', name: 'Ukrainian', nativeName: 'Українська' },
  { id: 'urdu', name: 'Urdu', nativeName: 'اردو' },
  { id: 'uyghur', name: 'Uyghur', nativeName: 'ئۇيغۇرچە' },
  { id: 'uzbek', name: 'Uzbek', nativeName: 'Oʻzbekcha' },
  { id: 'vietnamese', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { id: 'welsh', name: 'Welsh', nativeName: 'Cymraeg' },
  { id: 'xhosa', name: 'Xhosa', nativeName: 'isiXhosa' },
  { id: 'yiddish', name: 'Yiddish', nativeName: 'ייִדיש' },
  { id: 'yoruba', name: 'Yoruba', nativeName: 'Yorùbá' },
  { id: 'zulu', name: 'Zulu', nativeName: 'isiZulu' },
];

export const DEFAULT_LANGUAGE_ID = 'english';
