export type LanguageOption = {
  id: string;
  name: string;
  nativeName: string;
  flagCountryCode: string;
};

export const LANGUAGES: LanguageOption[] = [
  { id: 'afrikaans', name: 'Afrikaans', nativeName: 'Afrikaans', flagCountryCode: 'ZA' },
  { id: 'albanian', name: 'Albanian', nativeName: 'Shqip', flagCountryCode: 'AL' },
  { id: 'amharic', name: 'Amharic', nativeName: 'አማርኛ', flagCountryCode: 'ET' },
  { id: 'arabic', name: 'Arabic', nativeName: 'العربية', flagCountryCode: 'SA' },
  { id: 'armenian', name: 'Armenian', nativeName: 'Հայերեն', flagCountryCode: 'AM' },
  { id: 'assamese', name: 'Assamese', nativeName: 'অসমীয়া', flagCountryCode: 'IN' },
  { id: 'aymara', name: 'Aymara', nativeName: 'Aymar aru', flagCountryCode: 'BO' },
  { id: 'azerbaijani', name: 'Azerbaijani', nativeName: 'Azərbaycanca', flagCountryCode: 'AZ' },
  { id: 'bambara', name: 'Bambara', nativeName: 'Bamanankan', flagCountryCode: 'ML' },
  { id: 'basque', name: 'Basque', nativeName: 'Euskara', flagCountryCode: 'ES' },
  { id: 'belarusian', name: 'Belarusian', nativeName: 'Беларуская', flagCountryCode: 'BY' },
  { id: 'bengali', name: 'Bengali', nativeName: 'বাংলা', flagCountryCode: 'BD' },
  { id: 'bhojpuri', name: 'Bhojpuri', nativeName: 'भोजपुरी', flagCountryCode: 'IN' },
  { id: 'bosnian', name: 'Bosnian', nativeName: 'Bosanski', flagCountryCode: 'BA' },
  { id: 'bulgarian', name: 'Bulgarian', nativeName: 'Български', flagCountryCode: 'BG' },
  { id: 'burmese', name: 'Burmese', nativeName: 'မြန်မာစာ', flagCountryCode: 'MM' },
  { id: 'catalan', name: 'Catalan', nativeName: 'Català', flagCountryCode: 'ES' },
  { id: 'cebuano', name: 'Cebuano', nativeName: 'Cebuano', flagCountryCode: 'PH' },
  { id: 'chinese-simplified', name: 'Chinese (Simplified)', nativeName: '简体中文', flagCountryCode: 'CN' },
  { id: 'chinese-traditional', name: 'Chinese (Traditional)', nativeName: '繁體中文', flagCountryCode: 'TW' },
  { id: 'corsican', name: 'Corsican', nativeName: 'Corsu', flagCountryCode: 'FR' },
  { id: 'croatian', name: 'Croatian', nativeName: 'Hrvatski', flagCountryCode: 'HR' },
  { id: 'czech', name: 'Czech', nativeName: 'Čeština', flagCountryCode: 'CZ' },
  { id: 'danish', name: 'Danish', nativeName: 'Dansk', flagCountryCode: 'DK' },
  { id: 'dhivehi', name: 'Dhivehi', nativeName: 'ދިވެހި', flagCountryCode: 'MV' },
  { id: 'dogri', name: 'Dogri', nativeName: 'डोगरी', flagCountryCode: 'IN' },
  { id: 'dutch', name: 'Dutch', nativeName: 'Nederlands', flagCountryCode: 'NL' },
  { id: 'english', name: 'English', nativeName: 'English', flagCountryCode: 'US' },
  { id: 'esperanto', name: 'Esperanto', nativeName: 'Esperanto', flagCountryCode: 'PL' },
  { id: 'estonian', name: 'Estonian', nativeName: 'Eesti', flagCountryCode: 'EE' },
  { id: 'ewe', name: 'Ewe', nativeName: 'Eʋegbe', flagCountryCode: 'GH' },
  { id: 'filipino', name: 'Filipino', nativeName: 'Filipino', flagCountryCode: 'PH' },
  { id: 'finnish', name: 'Finnish', nativeName: 'Suomi', flagCountryCode: 'FI' },
  { id: 'french', name: 'French', nativeName: 'Français', flagCountryCode: 'FR' },
  { id: 'frisian', name: 'Frisian', nativeName: 'Frysk', flagCountryCode: 'NL' },
  { id: 'galician', name: 'Galician', nativeName: 'Galego', flagCountryCode: 'ES' },
  { id: 'georgian', name: 'Georgian', nativeName: 'ქართული', flagCountryCode: 'GE' },
  { id: 'german', name: 'German', nativeName: 'Deutsch', flagCountryCode: 'DE' },
  { id: 'greek', name: 'Greek', nativeName: 'Ελληνικά', flagCountryCode: 'GR' },
  { id: 'guarani', name: 'Guarani', nativeName: 'Avañeʼẽ', flagCountryCode: 'PY' },
  { id: 'gujarati', name: 'Gujarati', nativeName: 'ગુજરાતી', flagCountryCode: 'IN' },
  { id: 'haitian-creole', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen', flagCountryCode: 'HT' },
  { id: 'hausa', name: 'Hausa', nativeName: 'Hausa', flagCountryCode: 'NG' },
  { id: 'hawaiian', name: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi', flagCountryCode: 'US' },
  { id: 'hebrew', name: 'Hebrew', nativeName: 'עברית', flagCountryCode: 'IL' },
  { id: 'hindi', name: 'Hindi', nativeName: 'हिन्दी', flagCountryCode: 'IN' },
  { id: 'hmong', name: 'Hmong', nativeName: 'Hmoob', flagCountryCode: 'LA' },
  { id: 'hungarian', name: 'Hungarian', nativeName: 'Magyar', flagCountryCode: 'HU' },
  { id: 'icelandic', name: 'Icelandic', nativeName: 'Íslenska', flagCountryCode: 'IS' },
  { id: 'igbo', name: 'Igbo', nativeName: 'Igbo', flagCountryCode: 'NG' },
  { id: 'ilocano', name: 'Ilocano', nativeName: 'Ilokano', flagCountryCode: 'PH' },
  { id: 'indonesian', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flagCountryCode: 'ID' },
  { id: 'irish', name: 'Irish', nativeName: 'Gaeilge', flagCountryCode: 'IE' },
  { id: 'italian', name: 'Italian', nativeName: 'Italiano', flagCountryCode: 'IT' },
  { id: 'japanese', name: 'Japanese', nativeName: '日本語', flagCountryCode: 'JP' },
  { id: 'javanese', name: 'Javanese', nativeName: 'Basa Jawa', flagCountryCode: 'ID' },
  { id: 'kannada', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flagCountryCode: 'IN' },
  { id: 'kazakh', name: 'Kazakh', nativeName: 'Қазақша', flagCountryCode: 'KZ' },
  { id: 'khmer', name: 'Khmer', nativeName: 'ភាសាខ្មែរ', flagCountryCode: 'KH' },
  { id: 'kinyarwanda', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', flagCountryCode: 'RW' },
  { id: 'konkani', name: 'Konkani', nativeName: 'कोंकणी', flagCountryCode: 'IN' },
  { id: 'korean', name: 'Korean', nativeName: '한국어', flagCountryCode: 'KR' },
  { id: 'krio', name: 'Krio', nativeName: 'Krio', flagCountryCode: 'SL' },
  { id: 'kurdish-kurmanji', name: 'Kurdish (Kurmanji)', nativeName: 'Kurmancî', flagCountryCode: 'TR' },
  { id: 'kurdish-sorani', name: 'Kurdish (Sorani)', nativeName: 'کوردیی ناوەندی', flagCountryCode: 'IQ' },
  { id: 'kyrgyz', name: 'Kyrgyz', nativeName: 'Кыргызча', flagCountryCode: 'KG' },
  { id: 'lao', name: 'Lao', nativeName: 'ລາວ', flagCountryCode: 'LA' },
  { id: 'latin', name: 'Latin', nativeName: 'Latina', flagCountryCode: 'VA' },
  { id: 'latvian', name: 'Latvian', nativeName: 'Latviešu', flagCountryCode: 'LV' },
  { id: 'lingala', name: 'Lingala', nativeName: 'Lingála', flagCountryCode: 'CD' },
  { id: 'lithuanian', name: 'Lithuanian', nativeName: 'Lietuvių', flagCountryCode: 'LT' },
  { id: 'luganda', name: 'Luganda', nativeName: 'Luganda', flagCountryCode: 'UG' },
  { id: 'luxembourgish', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', flagCountryCode: 'LU' },
  { id: 'macedonian', name: 'Macedonian', nativeName: 'Македонски', flagCountryCode: 'MK' },
  { id: 'maithili', name: 'Maithili', nativeName: 'मैथिली', flagCountryCode: 'IN' },
  { id: 'malagasy', name: 'Malagasy', nativeName: 'Malagasy', flagCountryCode: 'MG' },
  { id: 'malay', name: 'Malay', nativeName: 'Bahasa Melayu', flagCountryCode: 'MY' },
  { id: 'malayalam', name: 'Malayalam', nativeName: 'മലയാളം', flagCountryCode: 'IN' },
  { id: 'maltese', name: 'Maltese', nativeName: 'Malti', flagCountryCode: 'MT' },
  { id: 'maori', name: 'Maori', nativeName: 'Māori', flagCountryCode: 'NZ' },
  { id: 'marathi', name: 'Marathi', nativeName: 'मराठी', flagCountryCode: 'IN' },
  { id: 'meiteilon', name: 'Meiteilon (Manipuri)', nativeName: 'ꯃꯤꯇꯩꯂꯣꯟ', flagCountryCode: 'IN' },
  { id: 'mizo', name: 'Mizo', nativeName: 'Mizo ṭawng', flagCountryCode: 'IN' },
  { id: 'mongolian', name: 'Mongolian', nativeName: 'Монгол', flagCountryCode: 'MN' },
  { id: 'nepali', name: 'Nepali', nativeName: 'नेपाली', flagCountryCode: 'NP' },
  { id: 'norwegian', name: 'Norwegian', nativeName: 'Norsk', flagCountryCode: 'NO' },
  { id: 'nyanja', name: 'Nyanja', nativeName: 'Chichewa', flagCountryCode: 'MW' },
  { id: 'odia', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flagCountryCode: 'IN' },
  { id: 'oromo', name: 'Oromo', nativeName: 'Afaan Oromoo', flagCountryCode: 'ET' },
  { id: 'pashto', name: 'Pashto', nativeName: 'پښتو', flagCountryCode: 'AF' },
  { id: 'persian', name: 'Persian', nativeName: 'فارسی', flagCountryCode: 'IR' },
  { id: 'polish', name: 'Polish', nativeName: 'Polski', flagCountryCode: 'PL' },
  { id: 'portuguese', name: 'Portuguese', nativeName: 'Português', flagCountryCode: 'PT' },
  { id: 'punjabi', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flagCountryCode: 'IN' },
  { id: 'quechua', name: 'Quechua', nativeName: 'Runasimi', flagCountryCode: 'PE' },
  { id: 'romanian', name: 'Romanian', nativeName: 'Română', flagCountryCode: 'RO' },
  { id: 'russian', name: 'Russian', nativeName: 'Русский', flagCountryCode: 'RU' },
  { id: 'samoan', name: 'Samoan', nativeName: 'Gagana Samoa', flagCountryCode: 'WS' },
  { id: 'sanskrit', name: 'Sanskrit', nativeName: 'संस्कृतम्', flagCountryCode: 'IN' },
  { id: 'scots-gaelic', name: 'Scots Gaelic', nativeName: 'Gàidhlig', flagCountryCode: 'GB' },
  { id: 'sepedi', name: 'Sepedi', nativeName: 'Sepedi', flagCountryCode: 'ZA' },
  { id: 'serbian', name: 'Serbian', nativeName: 'Српски', flagCountryCode: 'RS' },
  { id: 'sesotho', name: 'Sesotho', nativeName: 'Sesotho', flagCountryCode: 'LS' },
  { id: 'shona', name: 'Shona', nativeName: 'ChiShona', flagCountryCode: 'ZW' },
  { id: 'sindhi', name: 'Sindhi', nativeName: 'سنڌي', flagCountryCode: 'PK' },
  { id: 'sinhala', name: 'Sinhala', nativeName: 'සිංහල', flagCountryCode: 'LK' },
  { id: 'slovak', name: 'Slovak', nativeName: 'Slovenčina', flagCountryCode: 'SK' },
  { id: 'slovenian', name: 'Slovenian', nativeName: 'Slovenščina', flagCountryCode: 'SI' },
  { id: 'somali', name: 'Somali', nativeName: 'Soomaali', flagCountryCode: 'SO' },
  { id: 'spanish', name: 'Spanish', nativeName: 'Español', flagCountryCode: 'ES' },
  { id: 'sundanese', name: 'Sundanese', nativeName: 'Basa Sunda', flagCountryCode: 'ID' },
  { id: 'swahili', name: 'Swahili', nativeName: 'Kiswahili', flagCountryCode: 'TZ' },
  { id: 'swedish', name: 'Swedish', nativeName: 'Svenska', flagCountryCode: 'SE' },
  { id: 'tajik', name: 'Tajik', nativeName: 'Тоҷикӣ', flagCountryCode: 'TJ' },
  { id: 'tamil', name: 'Tamil', nativeName: 'தமிழ்', flagCountryCode: 'IN' },
  { id: 'tatar', name: 'Tatar', nativeName: 'Татарча', flagCountryCode: 'RU' },
  { id: 'telugu', name: 'Telugu', nativeName: 'తెలుగు', flagCountryCode: 'IN' },
  { id: 'thai', name: 'Thai', nativeName: 'ไทย', flagCountryCode: 'TH' },
  { id: 'tigrinya', name: 'Tigrinya', nativeName: 'ትግርኛ', flagCountryCode: 'ER' },
  { id: 'tsonga', name: 'Tsonga', nativeName: 'Xitsonga', flagCountryCode: 'ZA' },
  { id: 'turkish', name: 'Turkish', nativeName: 'Türkçe', flagCountryCode: 'TR' },
  { id: 'turkmen', name: 'Turkmen', nativeName: 'Türkmençe', flagCountryCode: 'TM' },
  { id: 'twi', name: 'Twi', nativeName: 'Twi', flagCountryCode: 'GH' },
  { id: 'ukrainian', name: 'Ukrainian', nativeName: 'Українська', flagCountryCode: 'UA' },
  { id: 'urdu', name: 'Urdu', nativeName: 'اردو', flagCountryCode: 'PK' },
  { id: 'uyghur', name: 'Uyghur', nativeName: 'ئۇيغۇرچە', flagCountryCode: 'CN' },
  { id: 'uzbek', name: 'Uzbek', nativeName: 'Oʻzbekcha', flagCountryCode: 'UZ' },
  { id: 'vietnamese', name: 'Vietnamese', nativeName: 'Tiếng Việt', flagCountryCode: 'VN' },
  { id: 'welsh', name: 'Welsh', nativeName: 'Cymraeg', flagCountryCode: 'GB' },
  { id: 'xhosa', name: 'Xhosa', nativeName: 'isiXhosa', flagCountryCode: 'ZA' },
  { id: 'yiddish', name: 'Yiddish', nativeName: 'ייִדיש', flagCountryCode: 'IL' },
  { id: 'yoruba', name: 'Yoruba', nativeName: 'Yorùbá', flagCountryCode: 'NG' },
  { id: 'zulu', name: 'Zulu', nativeName: 'isiZulu', flagCountryCode: 'ZA' },
];

const REGIONAL_INDICATOR_SYMBOL_OFFSET = 127397;

export const getLanguageFlagEmoji = ({
  flagCountryCode,
}: Pick<LanguageOption, 'flagCountryCode'>) =>
  Array.from(flagCountryCode.trim().toUpperCase())
    .map((letter) => String.fromCodePoint(letter.charCodeAt(0) + REGIONAL_INDICATOR_SYMBOL_OFFSET))
    .join('');

export const DEFAULT_LANGUAGE_ID = 'english';
